# Systematic Search Term Identification for Literature Review

**Pipeline position:** Stage 2 of 3

This notebook performs systematic identification of search terms for the literature review. It is original code based on the workflow of [ananse](https://baasare.github.io/ananse/_build/html/index.html) (not used due to bug), which mirrors the R package [litsearchr](https://elizagrames.github.io/litsearchr/) (not used due to R).

**Process:**
1. Import naive search results (CSV files from 02_processed/)
2. Deduplicate and combine to one single dataframe
3. Keyword extraction:
   - 3.1 KeyBERT
   - 3.2 YAKE
   - 3.3 Save intermediate results

**Outputs:** Intermediate CSV files in `02_processed/intermediate/` for use by Stage 3 (03_final_dataset_assembly.ipynb)

## 0. documentation naive search runs

several search runs iwht relevant keywords concerning the nexus of _welfare/social policy and crisis_, _welfare/social policy and covid/great recession_, _welfare state resilience_ and _welfare state change_ were run, each both on scopus and web of science. due to the nature of my research question, years of publication vary dependening on keywords (i.e. no searches for "covid" for publications before 2019). there are minor differences between the two platforms concering query designs and combinations. the exact queries are documented below. in separate keyword extraction runs, naive search runs are added that have only been done one web of science after the termination of the university's scopus access (concerning more niche naive search terms like distributional impact, inequality, unemployment and global south; seee below).

### scopus
1.  ((TITLE("social policy") AND TITLE("crisis" OR "crises") AND PUBYEAR > 1999 AND PUBYEAR < 2026 ) AND ( LIMIT-TO ( SRCTYPE,"j" ) )  AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( DOCTYPE,"ar" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) ) )
2. ((TITLE("welfare state") AND TITLE ("crisis" OR "crises") AND NOT("crisis of the welfare state" OR "crisis in the welfare state" )) AND PUBYEAR > 1999 AND PUBYEAR < 2025 AND ( LIMIT-TO ( SRCTYPE,"j" ) )  AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( DOCTYPE,"ar" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) )  AND ( EXCLUDE ( EXACTKEYWORD,"Church Of Sweden" ) ) )
3.  (((TITLE("welfare state" OR "social policy") AND TITLE-ABS ("resilience" OR "resilient")) AND PUBYEAR > 1999 AND PUBYEAR < 2026 ) AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) ) )
4.  (((TITLE ( "social policy") AND TITLE-ABS ( "covid" OR "COVID" OR "covid-19" OR "COVID-19" OR "coronavirus" OR "SARS-CoV2" OR "global pandemic" OR "corona" OR "pandemic" ) AND PUBYEAR > 2018 AND PUBYEAR < 2026 ) ) AND ( LIMIT-TO ( SRCTYPE,"j" ) )  AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( DOCTYPE,"ar" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) ) )
5. ((TITLE ( "social policy" ) AND TITLE-ABS("great recession" OR "subprime mortgage" OR "subprime" OR "sovereign debt" OR "housing bubble" OR ("Wall Street crash" AND "2008")) AND PUBYEAR > 2006 AND PUBYEAR < 2026 ) AND ( LIMIT-TO ( SRCTYPE,"j" ) )  AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( DOCTYPE,"ar" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) ) )
6. ((TITLE ( "welfare state" ) AND TITLE-ABS( "covid" OR "COVID" or "covid-19" OR "COVID-19" OR "coronavirus" OR "SARS-CoV2" OR "global pandemic" OR "corona" OR "pandemic" ) AND PUBYEAR > 2018 AND PUBYEAR < 2026 ) AND ( LIMIT-TO ( SRCTYPE,"j" ) )  AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( DOCTYPE,"ar" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) )  AND ( EXCLUDE ( EXACTKEYWORD,"Ethnographic Content Analysis" ) OR EXCLUDE ( EXACTKEYWORD,"Alt. Health Influencers" ) ) )
7. ((TITLE ( "welfare state" ) AND TITLE-ABS("great recession" OR "subprime mortgage" OR "subprime" OR "sovereign debt" OR "housing bubble" OR ("Wall Street crash" AND "2008")) AND PUBYEAR > 2006 AND PUBYEAR < 2026 ) AND ( LIMIT-TO ( SRCTYPE,"j" ) )  AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( DOCTYPE,"ar" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) ) )
8. ((TITLE ( "welfare state" ) AND TITLE ("welfare state change" OR "path dependency" OR "diffusion" OR "policy learning" or "paradigm shift" OR "retrenchment" OR "expansion") AND PUBYEAR > 2000 AND PUBYEAR < 2026 ) AND ( LIMIT-TO ( PUBSTAGE,"final" ) )  AND ( LIMIT-TO ( SUBJAREA,"SOCI" ) OR LIMIT-TO ( SUBJAREA,"ECON" ) )  AND ( LIMIT-TO ( LANGUAGE,"English" ) OR LIMIT-TO ( LANGUAGE,"German" ) ) )



### web of science (query links)

1. socialpolicy & crisis: https://www.webofscience.com/wos/woscc/summary/9f2b00ae-d7eb-4455-91cc-ef33b0f5bb0d-019666468f/relevance/1
2. welfare state & crisis: https://www.webofscience.com/wos/woscc/summary/927bf955-ec1c-4ff3-a846-32b5682e6c92-0196674fa6/relevance/1
3. resilience: https://www.webofscience.com/wos/woscc/summary/5faeb338-acb7-4bc5-979f-90305c44e61c-0196688e0f/relevance/1
4. welfare state & covid: https://www.webofscience.com/wos/woscc/summary/b12340ec-dfed-4e57-996d-563dba9ef037-01966f9301/relevance/1
5. socialpolicy & great recession: https://www.webofscience.com/wos/woscc/summary/ce470719-3235-4922-a5d7-9eb85ec568c3-01966d6869/relevance/1
6. welfare state & covid: https://www.webofscience.com/wos/woscc/summary/b12340ec-dfed-4e57-996d-563dba9ef037-01966f9301/relevance/1
7. welfare state & great recession (ti): https://www.webofscience.com/wos/woscc/summary/b72d217b-49f9-45d4-b300-28b0a30877bc-01966ec909/relevance/0
8. welfare state & great recession (abs): https://www.webofscience.com/wos/woscc/summary/ccdf2dbe-c750-45c2-a0f6-c4412b16addb-01966efe9c/relevance/1
9. welfare state change: https://www.webofscience.com/wos/woscc/summary/0a5c67ed-1f7c-4281-9f67-f5b4f16b290f-01966ff49d/relevance/1

#### web of science, other search terms not run on scopus (after 2025-12-31) (query links)


10. global south synonyms & covid/great recession & socialpolicy/welfare/inequality/poverty/unemployment: https://www.webofscience.com/wos/woscc/summary/5c021865-3a41-4041-accc-96dda2a5e00f-01989499a2/relevance/1
11. global south countrylist & covid/great recession & socialpolicy/welfare: https://www.webofscience.com/wos/woscc/summary/447b4660-208e-4e89-b3ab-537923c3d81a-01989397de/relevance/1
12. global south countrylist & covid/great recession & inequality/poverty/unemployment: https://www.webofscience.com/wos/woscc/summary/458aef5c-a4c1-425a-a259-fa4e48314fe1-0198941c9b/relevance/1
13. publicpolicy & covid/great recession & unemployment/inequality: https://www.webofscience.com/wos/woscc/summary/c855737e-40bb-4cc1-9048-c323eb4c4323-019ba117d6/relevance/1
14. distributional impact & crisis: https://www.webofscience.com/wos/woscc/summary/76591292-7d5b-4ae7-aa28-b4002c824e95-019897a843/relevance/1

In [3]:
from pathlib import Path
from datetime import date
import pandas as pd
from keybert import KeyBERT # before: pip install keybert 
from yake import KeywordExtractor #before: pip install yake
from collections import Counter

## 1. import and parse naive search results

In [6]:
input_dir = Path("../02_processed")  # reads scopus/ and webofscience/ subfolders

all_dfs = []

# defining desired output columns (they equal those in the scopus files)
scopus_cols = [
    "title", "abstract", "eid", "authors", "journal", "issue",
    "volume", "keywords", "doctype", "year", "doi",
    "pagestart", "pageend"
]

# macthing current to desired column names for wos files
wos_to_scopus = {
    "Article Title": "title",
    "Abstract": "abstract",
    "UT (Unique WOS ID)": "eid",
    "Authors": "authors",
    "Source Title": "journal",
    "Issue": "issue",
    "Volume": "volume",
    "Author Keywords": "keywords",
    "Document Type": "doctype",
    "Publication Year": "year",
    "DOI": "doi",
    "Start Page": "pagestart",
    "End Page": "pageend",
}

# loop over scopus files (only *_adapt_columns.csv files from Stage 1)
for csv_path in (input_dir / "scopus").glob("*_adapt_columns.csv"):
    df = pd.read_csv(csv_path)
    
    # normalize column names
    df.columns = df.columns.str.lower()

    # keep only desired columns
    df = df[[c for c in scopus_cols if c in df.columns]]
    
    #create column for "database" (scopus or wos)
    df["database"] = "scopus"

    # add a column "search run" (terms used)
    name= csv_path.stem
    search_run = name.replace("scopus_", "").split("_", 1)[1]
    search_run = search_run.replace("_adapt_columns", "")
    df["search_run"]=search_run
    
    #add a column "title_normalized"
    df["title_normalized"]= df["title"].str.lower().str.strip()

    #add a column "abs_normalized"
    df["abs_normalized"]= df["abstract"].str.lower().str.strip()
    
    all_dfs.append(df)

# loop over wos files
for csv_path in (input_dir / "webofscience").glob("*.csv"):
    df = pd.read_csv(csv_path)
    
    # rename wos columns to scopus schema
    df = df.rename(columns=wos_to_scopus)

    # keep only mapped columns
    df = df[[c for c in scopus_cols if c in df.columns]]

    #add to column for "database" (scopus or wos)
    df["database"] = "wos"

    #add to column "search_run"
    name= csv_path.stem
    search_run = name.replace("wos_", "").split("_", 1)[1]
    df["search_run"]=search_run

    #add a column "title_normalized"
    df["title_normalized"]= df["title"].str.lower().str.strip()

    #add a column "abs_normalized"
    df["abs_normalized"]= df["abstract"].str.lower().str.strip()
    
    all_dfs.append(df)

# compile to one dataframe
allresults_df = pd.concat(all_dfs, ignore_index=True)

print(f"Combined dataframe shape: {allresults_df.shape}")
allresults_df.head(100) #show part of df

Combined dataframe shape: (853, 17)

,title,abstract,eid,authors,journal,issue,volume,keywords,doctype,year,doi,pagestart,pageend,database,search_run,title_normalized,abs_normalized
0,National eco-social policies in the framework ...,"This article examines two questions. First, ho...",2-s2.0-105001646135,"Theodoropoulou, S.; Sabato, S.; Akgüç, M.",Global Social Policy,1,25.0,Climate change; eco-social policies; environme...,Article,2025,10.1177/14680181241291122,86.0,111,scopus,resilience,national eco-social policies in the framework ...,"this article examines two questions. first, ho..."
1,Resilience in the face of ecological challenge...,"Africa faces severe ecological crises, such as...",2-s2.0-85197686411,"Adebayo, W.G.",Sustainable Development,1,33.0,adaptive social policies; Africa; climate chan...,Article,2025,10.1002/sd.3113,203.0,220,scopus,resilience,resilience in the face of ecological challenge...,"africa faces severe ecological crises, such as..."
2,One and the Same or Worlds Apart? Linking Tran...,This paper explores the intersection between t...,2-s2.0-85215811031,"Neuhuber, T.",Sustainability (Switzerland),2,17.0,just transition; social infrastructure; social...,Review,2025,10.3390/su17020637,NaN,NaN,scopus,resilience,one and the same or worlds apart? linking tran...,this paper explores the intersection between t...
3,Regulating the Blue Economy: The Importance of...,This chapter aims to examine how ocean governa...,2-s2.0-105023719807,"Uppiah, M.V.; Henriette-Bolli, D.G.",NaN,NaN,NaN,NaN,NaN,2025,NaN,312.0,327,scopus,resilience,regulating the blue economy: the importance of...,this chapter aims to examine how ocean governa...
4,"Conclusion to Families, Welfare States and Res...",This chapter provides an overview of the findi...,2-s2.0-105019909740,"Daly, M.",NaN,NaN,NaN,Care Trilemma; Coping Practices; Meaning of Fa...,Book chapter,2025,NaN,176.0,191,scopus,resilience,"conclusion to families, welfare states and res...",this chapter provides an overview of the findi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,A Transformative Social Policy Perspective on ...,Land and agrarian reform in former settler col...,NaN,"Chipenda, C.",Africa Spectrum,1,59.0,NaN,NaN,2024,10.1177/00020397241234024,89,118,scopus,socialpolicy_covid,a transformative social policy perspective on ...,land and agrarian reform in former settler col...
96,Food Insecurity and Social Policy: A Comparati...,We sought to determine whether a country's soc...,2-s2.0-85179689020,"Berkowitz, S.A.; Drake, C.; Byhoff, E.",International Journal of Social Determinants o...,2,54.0,economics; food insecurity; international comp...,Article,2024,10.1177/27551938231219200,76,86,scopus,socialpolicy_covid,food insecurity and social policy: a comparati...,we sought to determine whether a country's soc...
97,The de-ideologization of welfare politics: Pol...,"During the global COVID-19 pandemic, many coun...",2-s2.0-85211744933,"Peltoniemi, J.; Ketonen, E.-L.; Hiilamo, H.",Journal of International and Comparative Socia...,1,40.0,COVID-19 pandemic; incumbents; political ideol...,Article,2024,10.1017/ics.2024.10,24,41,scopus,socialpolicy_covid,the de-ideologization of welfare politics: pol...,"during the global covid-19 pandemic, many coun..."
98,Crisis? What crisis? Social policy when crises...,"In this article, we analyse how different gove...",2-s2.0-85183935391,"Saxonberg, S.; Sirovátka, T.; Csudai, E.",Social Policy and Administration,2,58.0,Central Europe; crisis; path dependency; windo...,Article,2024,10.1111/spol.13004,228,247,scopus,socialpolicy_covid,crisis? what crisis? social policy when crises...,"in this article, we analyse how different gove..."
99,Understanding the Inflation and Social Policy ...,The cost-of-living crisis that began in the af...,2-s2.0-85176099232,"Béland, D.; Cantillon, B.; Greve, B.; Hick, R....",Social Policy and Society,1,23.0,cost-of-living; COVID-19; crisis; inflation; s...,Article,2024,10.1017/S1474746423000349,149,162,scopus,socialpolicy_covid,understanding the inflation and social policy ...,the cost-of-living crisis that began in the af...

In [7]:
categories = allresults_df["search_run"].unique()
print(categories)

['resilience' 'socialpolicy_covid' 'socialpolicy_crisis'
 'socialpolicy_greatrecession' 'welfarestatechange' 'welfarestate_covid'
 'welfarestate_crisis' 'welfarestate_greatrecession'
 'ti_resilience_abs_welfarestate' 'ti_welfarestate_abs_greatrecession'
 'ti_welfarestate_ti_greatrecession' 'distributionalimpact_crisis'
 'globalsouth_countrylist_inequality_poverty_covid_greatrecession'
 'globalsouth_countrylist_socialpolicy_covid_greatrecession'
 'globalsouth_synon_socialpolicy_inequality_welfarestate_covid_greatrecession_csv']

## 2. deduplicate and combine to df

### 2.1 deduplication

In [10]:
# count entries before deduplication
print(f"before deduplication, the dataframe allresults_df contains {len(allresults_df)} entries.")

# 1st deduplicate, by doi
## count number of missings in column "doi"
print(f"out of {len(allresults_df)} entries, there are {allresults_df['doi'].isna().sum()} entries with the doi missing.")

##using doi as anchor for deduplication
### deduplicate rows with a DOI
dedup_with_doi = (
    allresults_df[allresults_df['doi'].notna()]
    .assign(is_globalsouth=allresults_df['search_run'].str.startswith("globalsouth_", na=False)) #prioritizes entries from search_runs on "globalsouth_"; i later want to be able to analyse them separately and therefore do not want this easy identifier dropped in deduplication (rather drop their duplicates from other search runs)
    .sort_values('is_globalsouth', ascending=False)
    .drop_duplicates(subset='doi', keep='first')
)

### keep rows with missing DOI
missing_doi_df = allresults_df[allresults_df['doi'].isna()]

### combine both
unique_results_df = pd.concat([dedup_with_doi, missing_doi_df], ignore_index=True)

### print counts
print(f"after deduplication, unique_results_df contains {len(unique_results_df)} entries, including {unique_results_df['doi'].isna().sum()} with missing doi.")

before deduplication, the dataframe allresults_df contains 853 entries.
out of 853 entries, there are 103 entries with the doi missing.
after deduplication, unique_results_df contains 621 entries, including 103 with missing doi.

In [11]:
# 2nd deduplication, by title
## check for duplicate titles in unique_results_df
duplicate_titles = unique_results_df[unique_results_df.duplicated(subset='title_normalized', keep=False)]
print(f"number of entries with duplicate titles: {len(duplicate_titles)}")
if not duplicate_titles.empty:
    print("duplicate titles and their counts:")
    print(duplicate_titles.groupby('title').size().sort_values(ascending=False))

duplicate_titles.head()

## deduplicate by title 
### sort so rows with a doi come first within each title
unique_results_tmp = unique_results_df.copy()
unique_results_tmp['_has_doi'] = unique_results_tmp['doi'].notna()

### deduplicate by title, keeping rows with doi preferentially
final_results_df = (
    unique_results_tmp.sort_values(['_has_doi', 'is_globalsouth'], ascending=False)
       .drop_duplicates(subset='title_normalized', keep='first')
       .drop(columns='_has_doi')
       .reset_index(drop=True)
)


print(f"the final dataframe final_results_df has been deduplicated by title_normalized and doi, and has {len(final_results_df)} entries, including {final_results_df['doi'].isna().sum()} with missing doi.")
del unique_results_tmp

number of entries with duplicate titles: 23
duplicate titles and their counts:
title
The expansion and contraction of the American welfare state                                                                       4
Welfare state changes in China since 1949                                                                                         4
The state of the welfare state: German social policy between macroeconomic retrenchment and microeconomic recalibration           3
Election Campaigns and Welfare State Change: Democratic Linkage and Leadership Under Pressure                                     2
The coronavirus disease (COVID-19) pandemic and social policy narratives in Costa Rica: story of a (brief) opportunity            2
Another Inconvenient Truth: Fragile Families and the Looming Financial Crisis for the Welfare State                               1
Another inconvenient truth: Fragile families and the looming financial crisis for the welfare state                               1
PRIVATIZING RISK WITHOUT PRIVATIZING THE WELFARE STATE: THE HIDDEN POLITICS OF SOCIAL POLICY RETRENCHMENT IN THE UNITED STATES    1
Privatizing risk without privatizing the welfare state: The hidden politics of social policy retrenchment in the United States    1
SOCIAL POLICY AND SOCIAL WORK IN THE ECONOMIC CRISIS TIMES IN THE REPUBLIC OF MACEDONIA                                           1
Social policy and social work in the economic crisis times in the Republic of Macedonia                                           1
The Influence of the Crisis on the Pillars of the Welfare State. The opinion of EU citizens                                       1
The influence of the crisis on the pillars of the welfare state. The opinion of EU citizens                                       1
dtype: int64
the final dataframe final_results_df has been deduplicated by title_normalized and doi, and has 607 entries, including 89 with missing doi.

### 2.2 separate "welfare state change" literature

this step is domain specific and specific to my naive search process since i included searches regarding welfare state change. however, this is a separate part of my literature review and requires a separate search strategy alltogether since the naive results likely only contain empirical studies, but not necessarily the foundational publications on keywords like retrenchment, social learning etc.. i therefore separate the results of that search into a new dataframe and delete them from final_results_df.

In [12]:
# create subset of results that excludes results stemming from the search term "welfarestatechange" (side topic)

# Create a new column 'is_wschange' 
## 1 if 'welfarestatechange' appears in 'search_run', 0 otherwise
final_results_df['is_wschange'] = final_results_df['search_run'].str.contains( #str.contains(checks a field and returns boolean)
    'welfarestatechange', case=False, na=False #case for lower/upper case sensitivity / NA treated as false
).astype(int) #true/false expressed as 1/0

##count how many entries stem from welfarestate change as search term
final_results_df['is_wschange'].value_counts()

## new dataframe with only welfare state change entries
finres_wschange=final_results_df[final_results_df["is_wschange"]==1].copy()

## drop rows with welfare state change from final_results_df

final_results_df=final_results_df[final_results_df["is_wschange"]!=1]


print(f"the final dataframe final_results_df has {len(final_results_df)} entries after the exclusion of entries from the search runs on welfarestate change, these were {len(finres_wschange)}")

the final dataframe final_results_df has 456 entries after the exclusion of entries from the search runs on welfarestate change, these were 151

In [13]:
#drop column "is_wschange" in final_results_df

final_results_df=final_results_df.drop(columns=["is_wschange"])

## 3. key word extraction

in this section, two keyword extraction methods, keyBERT and yake, are applied to the title and abstract of each entry in the dataframe final_results_df separately. the resulting 5 most relevant keywords/keyphrases are stored in new columns "keybird" and "yake". the keyword come in tuples with their score (document-interal relevance). for score interpretation see descriptions in 3.1 and 3.2, respectively.

in a next step, these keywords, for keybird and yake, respectively, are combined over all entries into the most relevant keywords alltogether simply on the basis of highest frequency.

## 3.1 keyBERT
link: https://github.com/MaartenGr/KeyBERT?tab=readme-ov-file#llms

the first out of two keyword extraction methods used is keyBERT. it uitlizes "BERT-embeddings and simple cosine simiarity to find the subphrased in a document that are the most simiar to the document itself. first, it extracts document-level embeddings to get a document-level representation. then, word embeddings are extracted for N-gram words/phrases. cosine similarity is used to find words/phrases that are most similar to the document."

- score interpretation: higher score means higher representation of overall document/text

- citation bibtex:
@misc{grootendorst2020keybert,
  author       = {Maarten Grootendorst},
  title        = {KeyBERT: Minimal keyword extraction with BERT.},
  year         = 2020,
  publisher    = {Zenodo},
  version      = {v0.3.0},
  doi          = {10.5281/zenodo.4461265},
  url          = {https://doi.org/10.5281/zenodo.4461265}
}

In [15]:
# build new variable that combines title and abstract into one (for keyword extraction)

final_results_df["title_abstract"] = (
    final_results_df["title_normalized"].fillna("") + " " +
    final_results_df["abstract"].fillna("")
)

# count missings in "title_abstract" (should be 0, every entry has at least a title)
print(f"there are {final_results_df['abstract'].isna().sum()} abstracts missing in final_results_df, so for them key word extraction will be based on the title only. {final_results_df['title_abstract'].isna().sum()} missings in title") 


# initialize keybert model
model = KeyBERT('distilbert-base-nli-mean-tokens')


#apply keyword extraction on every row separately for column "title_abstract"
final_results_df["keybert"] = final_results_df['title_abstract'].apply( #.apply() applies the function lamda on an all cells in title_abstracts
    lambda text: model.extract_keywords(text, keyphrase_ngram_range=(1,1)) if isinstance(text, str) and text.strip() else [] #keyphrase range set to (1,1), meaning only one-word phrases. for 2-word phrases, set to (1,2)
) # only applied when (if is instance...else) cell content is a string object, otherwise just fills in nothing


# quick sanity check
final_results_df[["title_normalized", "abstract", "keybert"]].head(100)

there are 36 abstracts missing in final_results_df, so for them key word extraction will be based on the title only. 0 missings in title

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

c:\Users\Lenovo\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lenovo\.cache\huggingface\hub\models--sentence-transformers--distilbert-base-nli-mean-tokens. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/450 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

,title_normalized,abstract,keybert
0,socioeconomic inequality in latin america and ...,"Inequality is a global, structural problem tha...","[(pandemic, 0.304), (poorest, 0.251), (inequal..."
1,"since the market is closed, there is no more m...",The COVID-19 pandemic is expected to widen ine...,"[(pandemic, 0.2243), (poverty, 0.2024), (inequ..."
2,estimation of the fundamental learning loss an...,There is evidence of learning loss due to the ...,"[(mexico, 0.2674), (mathematics, 0.1368), (pan..."
3,rural china under the covid-19 pandemic: diffe...,We use field data collected in a village in no...,"[(china, 0.1664), (pandemic, 0.1591), (rural, ..."
4,effect of covid-19 on household food insecurit...,Following the outbreak of COVID-19 and its hea...,"[(pandemic, 0.3951), (poverty, 0.301), (insecu..."
...,...,...,...
95,social policy responses and social development...,The COVID-19 pandemic has had daunting economi...,"[(pandemic, 0.4068), (disadvantaged, 0.2844), ..."
96,social policy responses to covid-19 in canada ...,Canada and the United States are often grouped...,"[(canada, 0.3815), (canadian, 0.367), (pandemi..."
97,assessing public support for social policy in ...,The 2021 American Rescue Plan included the tem...,"[(2021, 0.1477), (tax, 0.1203), (americans, 0...."
98,destinations matter: social policy and migrant...,The national lockdown of India announced on Ma...,"[(pandemic, 0.1333), (lockdown, 0.0547), (seas..."
99,russians' views on the necessary social policy...,The article is based on data from All-Russian ...,"[(pandemic, 0.2659), (russians, 0.2485), (pate..."

In [16]:
# most common keywords over all final_results_df (keybert)

#flatten all keywords, ignore score by taking kw out of tuple into new object
all_kw_keybert=[kw for row in final_results_df["keybert"] for kw, score in row]

#count frequencies
keyword_counts_k=Counter(all_kw_keybert) #from collections library

#get most common-50 and -20 words

top_50_keybert= [kw for kw, count in keyword_counts_k.most_common(50)]
top_20_keybert= [kw for kw, count in keyword_counts_k.most_common(20)]

print(top_50_keybert)
print(top_20_keybert)

['pandemic', 'economic', 'crisis', 'recession', 'inequality', 'poverty', '2020', 'unemployment', 'political', 'politics', 'coronavirus', 'europe', 'china', 'global', 'germany', '2021', 'reforms', 'crises', 'retrenchment', 'social', 'democratic', 'european', 'decades', 'economy', 'policymakers', 'policy', 'macroeconomic', 'globalization', '2022', 'capitalism', 'socioeconomic', 'covid', 'german', 'brazil', 'healthcare', 'women', 'reform', '1990s', 'italy', 'economies', 'severe', 'welfare', 'sweden', 'italian', 'policies', 'virus', '2013', 'decade', 'policymaking', 'democracies']
['pandemic', 'economic', 'crisis', 'recession', 'inequality', 'poverty', '2020', 'unemployment', 'political', 'politics', 'coronavirus', 'europe', 'china', 'global', 'germany', '2021', 'reforms', 'crises', 'retrenchment', 'social']

## 3.2 yake

link: https://github.com/INESCTEC/yake

the second keyword extraction method used is yake. it "is a lightweight unsupervised automatic keyword extraction method that uses text statistical features to select the most important keywords from a document"

- score interpretation: the lower (!) the score, the more relevant the keyword.

- citation bibtex: @InProceedings{10.1007/978-3-319-76941-7_80,
author="Campos, Ricardo
and Mangaravite, V{\'i}tor
and Pasquali, Arian
and Jorge, Al{\'i}pio M{\'a}rio
and Nunes, C{\'e}lia
and Jatowt, Adam",
editor="Pasi, Gabriella
and Piwowarski, Benjamin
and Azzopardi, Leif
and Hanbury, Allan",
title="YAKE! Collection-Independent Automatic Keyword Extractor",
booktitle="Advances in Information Retrieval",
year="2018",
publisher="Springer International Publishing",
address="Cham",
pages="806--810"
}

In [17]:
# create instance of keyword extractor

yake_extract =KeywordExtractor(top=5, n=3) #customized to top-5 keywords, n is ngram size set to 3 (3-word phrases, default))

#apply keyword extraction on every row separately for column "title_abstract"
final_results_df["yake"] = final_results_df["title_abstract"].apply(
    lambda text: yake_extract.extract_keywords(text) if isinstance(text, str) and text.strip() else [] 
)

#quick sanity check
final_results_df[["title", "abstract", "keybert", "yake"]].head(100)

,title,abstract,keybert,yake
0,Socioeconomic inequality in Latin America and ...,"Inequality is a global, structural problem tha...","[(pandemic, 0.304), (poorest, 0.251), (inequal...","[(world poorest countries, 0.00256179646874533..."
1,"Since the market is closed, there is no more m...",The COVID-19 pandemic is expected to widen ine...,"[(pandemic, 0.2243), (poverty, 0.2024), (inequ...","[(burkina faso, 0.01172960435918361), (sierra ..."
2,Estimation of the fundamental learning loss an...,There is evidence of learning loss due to the ...,"[(mexico, 0.2674), (mathematics, 0.1368), (pan...","[(learning loss, 0.028424376561722156), (learn..."
3,Rural China under the COVID-19 pandemic: Diffe...,We use field data collected in a village in no...,"[(china, 0.1664), (pandemic, 0.1591), (rural, ...","[(field data collected, 0.004870762018071421),..."
4,Effect of COVID-19 on Household Food Insecurit...,Following the outbreak of COVID-19 and its hea...,"[(pandemic, 0.3951), (poverty, 0.301), (insecu...","[(Sustainable Development Goals, 0.00029321435..."
...,...,...,...,...
95,Social policy responses and social development...,The COVID-19 pandemic has had daunting economi...,"[(pandemic, 0.4068), (disadvantaged, 0.2844), ...",[(socio-economically disadvantaged individuals...
96,Social policy responses to COVID-19 in Canada ...,Canada and the United States are often grouped...,"[(canada, 0.3815), (canadian, 0.367), (pandemi...","[(state regimes Canada, 0.002611881599994128),..."
97,Assessing public support for social policy in ...,The 2021 American Rescue Plan included the tem...,"[(2021, 0.1477), (tax, 0.1203), (americans, 0....","[(child tax credit, 0.0001145100488303065), (i..."
98,Destinations Matter: Social Policy and Migrant...,The national lockdown of India announced on Ma...,"[(pandemic, 0.1333), (lockdown, 0.0547), (seas...","[(announced on March, 0.010454217254106576), (..."
99,RUSSIANS' VIEWS ON THE NECESSARY SOCIAL POLICY...,The article is based on data from All-Russian ...,"[(pandemic, 0.2659), (russians, 0.2485), (pate...","[(FCTAS RAS 2006-2020, 0.0006464939030751998),..."

In [18]:
# most common keywords over all final_results_df (yake)

#flatten all keywords, ignore score by taking kw out of tuple into new object
all_kw_yake=[kw for row in final_results_df["yake"] for kw, score in row]

#count frequencies
keyword_counts_y=Counter(all_kw_yake) #from collections library

#get most common-50 and -20 words

top_70_yake= [kw for kw, count in keyword_counts_y.most_common(70)]
top_20_yake= [kw for kw, count in keyword_counts_y.most_common(20)]

print(top_70_yake)
print(top_20_yake)

['welfare state', 'social policy', 'social', 'poverty', 'social policy responses', 'economic crisis', 'welfare states', 'pandemic', 'great recession', 'welfare', 'state', 'social policies', 'latin america', 'financial crisis', 'European Union', 'social policy response', 'global economic crisis', 'global social policy', 'global financial crisis', 'european welfare states', 'European welfare states', 'Great Recession', 'policy responses', 'United Kingdom', 'global economic', 'crisis', 'social policy digest', 'global social', 'policy digest', 'labour market', 'great', 'Asian financial crisis', 'welfare state reforms', 'policy', 'european welfare', 'resilience', 'food', 'Latin American countries', 'social protection', 'inequality', 'eastern europe', 'European Social Survey', 'welfare state regimes', 'social investment', 'european welfare state', 'german welfare state', 'german welfare', 'Middle East', 'German welfare state', 'welfare state crisis', 'mexico', 'india', 'social protection programs', 'social media', 'health crises', 'coronavirus disease', 'china', 'opportunity', 'Latin America', 'impact', 'income inequality', 'united states', 'public health emergency', 'central and eastern', 'latin', 'human capital', 'health', 'food insecurity', 'World Health Organization', 'young people']
['welfare state', 'social policy', 'social', 'poverty', 'social policy responses', 'economic crisis', 'welfare states', 'pandemic', 'great recession', 'welfare', 'state', 'social policies', 'latin america', 'financial crisis', 'European Union', 'social policy response', 'global economic crisis', 'global social policy', 'global financial crisis', 'european welfare states']

## 3.3 save intermediate results (for next pipeline stage)

this section saves the processed data with keywords for use in the next pipeline stage (03_final_dataset_assembly.ipynb), where manual search results are merged and final deduplication happens.

In [19]:
# save intermediate results for Stage 3 (final dataset assembly)

today = date.today().strftime("%Y-%m-%d")
output_dir = Path("../02_processed/intermediate")
output_dir.mkdir(parents=True, exist_ok=True)

# save main results with keywords
output_file = output_dir / f"{today}_naive_search_with_keywords.csv"
final_results_df.to_csv(output_file, index=False)
print(f"Saved: {output_file.name} ({len(final_results_df)} entries)")

# save welfare state change subset
wschange_file = output_dir / f"{today}_wschange_naive.csv"
finres_wschange.to_csv(wschange_file, index=False)
print(f"Saved: {wschange_file.name} ({len(finres_wschange)} entries)")

print(f"\nIntermediate results saved to {output_dir}/")
print("Next step: Run 03_final_dataset_assembly.ipynb to merge manual searches and create final dataset.")

Saved: 2026-01-27_naive_search_with_keywords.csv (456 entries)
Saved: 2026-01-27_wschange_naive.csv (151 entries)

Intermediate results saved to ..\02_processed\intermediate/
Next step: Run 03_final_dataset_assembly.ipynb to merge manual searches and create final dataset.