# literature review analysis

**Pipeline position:** stage 4 of 4

this notebook analyzes the final deduplicated dataset from stage 3.

**input:** `02_processed/combined/{date}_final_results.csv`

In [9]:
from pathlib import Path
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from openai import OpenAI
from dotenv import load_dotenv #to load .env file and retrieve api key
import json #for structured output format in response to llm prompt
from tqdm import tqdm #shows progress bars when looping over entries 
import os
from datetime import date

# Define paths (relative to notebooks/ folder)

output_path = Path("../03_analysis")
output_path.mkdir(exist_ok=True)

In [10]:
# load most recent final results
data_dir = Path("../02_processed/combined")
files = sorted(data_dir.glob("*_final_results.csv"))
latest_file = files[-1]

df = pd.read_csv(latest_file)
print(f"loaded: {latest_file.name}")
print(f"total entries: {len(df)}")
print(f"\nsearch runs:")
print(df['search_run'].value_counts())

loaded: 2026-01-27_final_results.csv
total entries: 502

search runs:
search_run
socialpolicy_covid                                                                 82
globalsouth_countrylist_inequality_poverty_covid_greatrecession                    75
welfarestate_crisis                                                                72
resilience                                                                         67
socialpolicy_crisis                                                                62
welfarestate_covid                                                                 41
manual_wschange                                                                    14
manual_resilience                                                                  14
globalsouth_synon_socialpolicy_inequality_welfarestate_covid_greatrecession_csv    13
ti_resilience_abs_welfarestate                                                     13
welfarestate_greatrecession                                                         9
manual_greatrecession                                                               9
socialpolicy_greatrecession                                                         9
manual_covid                                                                        8
globalsouth_countrylist_socialpolicy_covid_greatrecession                           5
distributionalimpact_crisis                                                         5
ti_welfarestate_abs_greatrecession                                                  2
manual_globalsouth                                                                  2
Name: count, dtype: int64

## 0. generate abstract summaries with llm

In [ ]:
# configurations

##load .env file

load_dotenv()

#retrieve and store key in object, key remains hidden
abssumm_key=os.getenv("openai_abssumm_key") 

#initialize openai client

client=OpenAI(api_key=abssumm_key)

#define model

#model="gpt-5-nano"

#structured output schema

json_schema= {
    "name": "abssumm_schema",
    "schema": {
        "type": "object", #defines type of schema; allowed: string, number, boolean, object...
        "properties": {
            "abssummary": {"type": "string"} #depends on desired nature of output -> abssummaries are strings
        },
        "required": ["abssummary"],
        "additionalProperties": False
    },
    "strict": True #deterministic with regard to output schema
}

In [14]:
# function to summarize abstracts using llm

def summarize_abstracts(df: pd.DataFrame, model:str, abstract_col: str = "abstract") -> pd.DataFrame:
    """
    this function uses an llm to summarize abstracts (column in df) of journal articles (rows in df)

    args:
        df: pandas dataframe containing journal articles with bibliographic info and abstracts as columns.
        model: specifies llm (official name) we want to use, e.g. gpt-4.1-nano 
        abstract_col: specifies name of column we want to draw from 

    returns:
        dict: a dictionary (json) containing each article with an abstract summary
    """
    
    summaries = []
    
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="summarizing abstracts"):
        abstract = row[abstract_col]
        
        # skip if abstract is missing
        if pd.isna(abstract) or str(abstract).strip() == "":
            summaries.append(None)
            continue
        
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system",
                     "content": "you are an expert in summarizing the abstracts of scientific journal articles in a high-quality manner"},
                    {"role": "user",
                     "content": f"summarize this journal article abstract in maximum two sentences in a very concise manner that captures the essential research question, data and results if mentioned:\n\n{abstract}"}
                ],
                response_format={"type": "json_schema", "json_schema": json_schema},
            )
            
            result = json.loads(response.choices[0].message.content)
            summaries.append(result.get("abssummary", None))
            
        except Exception as e:
            print(f"error at index {idx}: {e}")
            summaries.append(None)
    
    df[f"abs_summ_{model}"] = summaries
    return df

In [15]:
#execute function for summaries with gpt-4.1-nano [API call!!] for 2026-01-27_final_results.csv (stored in "df", above)
df=summarize_abstracts(df=df, model="gpt-4.1-nano")

summarizing abstracts: 100%|██████████| 502/502 [08:08<00:00,  1.03it/s]

In [16]:
# save finres_with_abssumm_df to 03_analysis

df.to_csv(output_path / f"{date.today()}_finres_with_abssumm.csv", index=False)
print(f"saved to {output_path / f'{date.today()}_finres_with_abssumm.csv'}")

saved to ..\03_analysis\2026-01-29_finres_with_abssumm.csv

## 1. explore resilience entries

filter and analyze entries from the resilience search. literature from the manual resilience search run was already studied and integrated into the litrev typst-document and therefore excluded here.

In [17]:
# load enriched finres df with abstract summaries
analysis_dir = Path("../03_analysis")
analysis_files = sorted(analysis_dir.glob("*_finres_with_abssumm.csv"))
latest_analysis_file = analysis_files[-1]

df_enriched = pd.read_csv(latest_analysis_file)
print(f"loaded: {latest_analysis_file.name}")
print(f"total entries: {len(df_enriched)}")

loaded: 2026-01-29_finres_with_abssumm.csv
total entries: 502

In [20]:
# filter manual_resilience entries
resilience_df = df_enriched[df_enriched['search_run'] == 'resilience'].copy()
print(f"resilience entries: {len(resilience_df)}")

# display titles
resilience_df[['title', 'year', 'journal']].head(20)

resilience entries: 67

,title,year,journal
77,Resilience in the face of ecological challenge...,2025,Sustainable Development
87,National eco-social policies in the framework ...,2025,Global Social Policy
110,West European welfare states: The old politics...,2000,European Journal of Political Research
111,Social policy in harsh times. Social security ...,2000,International Journal of Social Welfare
112,Dismantling the social democratic welfare mode...,2001,Scandinavian Political Studies
113,Review essay: Welfare State Challenges and Res...,2001,Acta Sociologica
114,Coping with permanent austerity: Welfare state...,2002,Revue Francaise de Sociologie
115,The silver age of the welfare state: Perspecti...,2002,Journal of Social Policy
116,Risk and Resilience in the Life Course: Implic...,2003,Journal of Youth Studies
122,Political partisanship and welfare state refor...,2004,American Journal of Political Science
154,"Research, advocacy, and social policy: Lessons...",2007,Social Work Research
155,Devolution and neoliberalism in the Canadian w...,2007,Global Social Policy
156,"On consensus, constraint and choice: Economic ...",2009,Journal of European Public Policy
157,An absent presence: Experiences of the 'welfar...,2011,Contemporary South Asia
158,Explaining welfare state adaptation in East As...,2012,Asian Journal of Social Science
159,"Blinded by neuroscience: Social policy, the fa...",2012,"Families, Relationships and Societies"
160,Theoretical visions versus policymaking realit...,2006,Comparative Sociology
161,Workplace work-family interventions: Italy in ...,2013,International Journal of Sociology and Social ...
162,Welfare States and Social Cohesion in Europe: ...,2015,Journal of Social Policy
163,The south European welfare state in the new Mi...,2016,World Economy and International Relations

Classify publications by their conceptual understanding of resilience (manually, see litrev typstdocument):
- **a) Persistence framing**: Resilience as welfare state persistence against retrenchment, austerity, or neoliberal threats
- **b) Capacities framing**: Resilience as absorptive, adaptive, and transformative capacities (Keck & Sakdapolrak; Pereirinha & Pereira; Daly)
- **c) Neither**: Does not fit either framing

## 2. explore great recession entries

In [21]:
# Filter for Great Recession and related entries
searchruns_filter_gr = [
    "welfarestate_greatrecession",
    "manual_greatrecession",
    "socialpolicy_greatrecession",
    "ti_welfarestate_abs_greatrecession"
]

greatrecession_df = df_enriched[df_enriched['search_run'].isin(search_runs_filter)].copy()
print(f"Great Recession related entries: {len(greatrecession_df)}")
print(f"\nBreakdown by search run:")
print(greatrecession_df['search_run'].value_counts())
greatrecession_df

Great Recession related entries: 29

Breakdown by search run:
search_run
socialpolicy_greatrecession           9
welfarestate_greatrecession           9
manual_greatrecession                 9
ti_welfarestate_abs_greatrecession    2
Name: count, dtype: int64

,title,abstract,eid,authors,journal,issue,volume,keywords,doctype,year,...,pageend,database,search_run,title_normalized,abs_normalized,is_globalsouth,title_abstract,keybert,yake,abs_summ_gpt-4.1-nano
91,Is the Welfare State resisting? Recent develop...,In this paper an attempt was made to analyze s...,WOS:000438917100004,"Kerstenetzky, CL; Guedes, GP",CIENCIA & SAUDE COLETIVA,7,23.0,Welfare State; Organisation for Economic Co-Op...,Article,2018,...,2106,wos,ti_welfarestate_abs_greatrecession,is the welfare state resisting? recent develop...,in this paper an attempt was made to analyze s...,False,is the welfare state resisting? recent develop...,"[('recession', 0.4087), ('2008', 0.2476), ('la...","[('welfare state resisting', 0.007429410766558...",The study analyzes welfare state evolution in ...
92,Welfare State and party political programmes i...,Since the start of the Great Recession in 2007...,WOS:000473527800003,"Ares, C; Losada, A",REVISTA DE ESTUDIOS POLITICOS,184,NaN,Population Ageing; Welfare State; Manifesto Co...,Article,2019,...,101,wos,ti_welfarestate_abs_greatrecession,welfare state and party political programmes i...,since the start of the great recession in 2007...,False,welfare state and party political programmes i...,"[('recession', 0.3248), ('2007', 0.2217), ('de...","[('Great Recession', 0.00402221119755729), ('s...",The study analyzes European political parties'...
132,Resisting austerity measures to social policie...,Since Margaret Thatcher reached power in the U...,2-s2.0-85076526946,"O'Campo, P.; Freiler, A.; Muntañer, C.; Gelorm...",Health Promotion International,6,34.0,Austerity; Employment policies; Fuel poverty; ...,Article,2019,...,1140,scopus,socialpolicy_greatrecession,resisting austerity measures to social policie...,since margaret thatcher reached power in the u...,False,resisting austerity measures to social policie...,"[('thatcher', 0.27), ('neoliberal', 0.2594), (...","[('Margaret Thatcher reached', 0.0009064427839...",The study examines resistance to austerity mea...
133,US Social Policy in the 21st Century: The Diff...,"In Western Europe, political commentators have...",2-s2.0-79959264975,"Daguerre, A.",Social Policy and Administration,4,45.0,American social policy; Economic insecurity; S...,Article,2011,...,407,scopus,socialpolicy_greatrecession,us social policy in the 21st century: the diff...,"in western europe, political commentators have...",False,us social policy in the 21st century: the diff...,"[('obama', 0.2952), ('recession', 0.2462), ('d...","[('President Barack Obama', 0.0009497605608292...",The article analyzes why President Obama's eff...
134,Familistic welfare capitalism in crisis: Socia...,Familistic welfare capitalism is a model of na...,2-s2.0-84890434049,"Papadopoulos, T.; Roumpakis, A.",Journal of International and Comparative Socia...,3,29.0,anti-social policy; familistic welfare capital...,Article,2013,...,224,scopus,socialpolicy_greatrecession,familistic welfare capitalism in crisis: socia...,familistic welfare capitalism is a model of na...,False,familistic welfare capitalism in crisis: socia...,"[('capitalism', 0.3345), ('greece', 0.2939), (...","[('Southern Europe', 0.0036614675598375503), (...",The study investigates familistic welfare capi...
242,European health inequality through the Great R...,This paper investigates the association betwee...,WOS:000431674900010,"van der Wel, KA; Saltkjel, T; Chen, WH; Dahl, ...",SOCIOLOGY OF HEALTH & ILLNESS,4.0,40.0,social determinants of health; social change; ...,Article,2018,...,768,wos,socialpolicy_greatrecession,european health inequality through the great r...,this paper investigates the association betwee...,False,european health inequality through the great r...,"[('recession', 0.3209), ('unemployment', 0.196...","[('great recession', 0.006846512348713536), ('...",The study examines how the Great Recession imp...
280,Weathering the Storm: Social Policy and the Gr...,This review discusses recent challenges to the...,WOS:000467878600006,"Maks-Solomon, C; Stoker, RP",POLICY STUDIES JOURNAL,NaN,47.0,social policy; welfare; Great Recession; unemp...,Article,2019,...,S137,wos,socialpolicy_greatrecession,weathering the storm: social policy and the gr...,this review discusses recent challenges to the...,False,weathering the storm: social policy and the gr...,"[('recession', 0.4373), ('storm', 0.3094), ('d...","[('great recession', 0.0022187612786954184), (...",This review examines how the Great Recession c...
331,Explaining Social Policy Preferences: Evidence...,"To what extent do personal circumstances, as c...",WOS:000315340600005,"Margalit, Y",AMERICAN POLITICAL SCIENCE REVIEW,1.0,107.0,NaN,Article,2013,...,103,wos,socialpolicy_greatrecession,explaining social policy preferences: evidence...,"to what extent do personal circumstances, as c...",False,explaining social policy preferences: evidence...,"[('recession', 0.3651), ('economic', 0.2044), ...","[(""drive voters' preferences"", 0.0175630570523...",This study uses a four-year panel of Americans...
332,Dynamic social security after the crisis: Towa...,The conservative bias in social attitudes to t...,2-s2.0-84919675811,"Diamond, P.; Lodge, G.",International Social Security Review,4-Mar,67.0,Denmark; Economic recession; European union; F...,Article,2014,...,59,scopus,welfarestate_greatrecession,dynamic social security after the crisis: towa...,the conservative bias in social attitudes to t...,False,dynamic social security after the crisis: towa...,"[('recession', 0.2438), ('conservative', 0.190...","[('welfare state', 0.022096912286268092), ('so...",The article analyzes public support for tradit...
333,"Great Recession, great regression? The welfare...",Has the welfare state undergone significant re...,2-s2.0-85099549502,"Kerstenetzky, C.; Pereira Guedes, G.",Cambridge Journal of Economics,1,45.0,Inequality; Poverty; Social expenditure; Taxat...,Article,2021,...,194,scopus,welfarestate_greatrecession,"great recession, great regression? the welfare...",has the welfare state undergone significant re...,False,"great recession, great regression? the welfare...","[('recession', 0.4067), ('2007', 0.241), ('cra...","[('great recession', 0.012777997435996388), ('...",The study analyzes OECD data from 2007-2013 to...
346,The great recession and welfare state reform: ...,"By 2010, when the Greek sovereign debt crisis ...",2-s2.0-84911990622,"van Kersbergen, K.; Vis, B.; Hemerijck, A.",Social Policy and Administration,7,48.0,Comparative analysis; Cost containment; Retren...,Article,2014,...,904,scopus,welfarestate_greatrecession,the great recession and welfare state reform: ...,"by 2010, when the greek sovereign debt crisis ...",False,the great recession and welfare state reform: ...,"[('recession', 0.2586), ('democracies', 0.1496...","[('welfare state reform', 0.017244644016146737...",The study examines welfare state reforms in fo...
347,Public opinion on policy and budgetary trade-o...,"In the wake of the ‘Great Recession’, welfare ...",2-s2.0-85016116747,"Busemeyer, M.R.; Garritzmann, J.L.",Journal of European Public Policy,6,24.0,Education policy; INVEDUC survey; policy trade...,Article,2017,...,889,scopus,welfarestate_greatrecession,public opinion on policy and budgetary trade-o...,"in the wake of the ‘great recession’, welfare ...",False,public opinion on policy and budgetary trade-o...,"[('recession', 0.2832), ('economy', 0.1814), (...","[('Great Recession’', 0.004064343235516733), (...",This study examines European public preference...
348,Political distrust amidst the Great Recession:...,The economic crisis that erupted in Europe in ...,2-s2.0-85020209721,"Haugsgjerd, A.",Comparative European Politics,4,16.0,economic crises; political trust; The Great Re...,Article,2018,...,648,scopus,welfarestate_greatrecession,political distrust amidst the great recession:...,the economic crisis that erupted in europe in ...,False,political distrust amidst the great recession:...,"[('recession', 0.3293), ('setbacks', 0.2476), ...","[('national political system', 0.0100282201491...",The study explores how the 2008 European econo...
350,Unemployment and political trust across 24 Wes...,Set against the backdrop of the Great Recessio...,2-s2.0-85105482413,"Giustozzi, C.; Gangl, M.",Acta Sociologica,3,64.0,cross-national comparison; Great Recession; Po...,Article,2021,...,273,scopus,welfarestate_greatrecession,unemployment and political trust across 24 wes...,set against the backdrop of the great recessio...,False,unemployment and political trust across 24 wes...,"[('recession', 0.2551), ('unemployment', 0.197...","[('European Social Survey', 0.0039391645079864...",The study examines how personal unemployment e...
351,Boosting work through welfare? Individual-leve...,Given the heterogeneity of European welfare st...,2-s2.0-85175170263,"Ronchi, S.",Socio-Economic Review,4,21.0,D690 (Welfare Economics: Other); employment; E...,Article,2023,...,2189,scopus,welfarestate_greatrecession,boosting work through welfare? individual-leve...,given the heterogeneity of european welfare st...,False,boosting work through welfare? individual-leve...,"[('economics', 0.3891), ('recession', 0.3675),...","[('european welfare states', 0.011400602205714...",This study investigates how social investment ...
377,Policy Continuity and Change in Greek Social P...,The extensive and radical reforms introduced i...,WOS:000371069100008,"Angelaki, M",SOCIAL POLICY & ADMINISTRATION,2.0,50.0,Pensions; Health care; Reform; Greece; Crisis;...,Article,2016,...,277,wos,socialpolicy_greatrecession,policy continuity and change in greek social p...,the extensive and radical reforms introduced i...,False,policy continuity and change in greek social p...,"[('transformative', 0.2718), ('reforms', 0.260...","[('greek social policy', 0.003971739234962576)...",The article examines Greece's post-crisis pens...
382,The welfare state and the great recession,NaN,2-s2.0-84865449163,"Andersen, T.M.",Intereconomics,4,47.0,NaN,NaN,2012,...,211,scopus,welfarestate_greatrecession,the welfare state and the great recession,NaN,False,the welfare state and the great recession,"[('recession', 0.8194), ('welfare', 0.325), ('...","[('great recession', 0.015380821171891606), ('...",NaN
383,A new era of European Integration? Governance ...,In this article we develop a typology of Europ...,WOS:000347435800002,"de la Porte, C; Heins, E",COMPARATIVE EUROPEAN POLITICS,1.0,13.0,European Integration; institutional change; go...,Article,2015,...,28,wos,socialpolicy_greatrecession,a new era of european integration? governance ...,in this article we develop a typology of europ...,False,a new era of european integration? governance ...,"[('integration', 0.3462), ('investments', 0.31...","[('European Monetary Union', 0.008139172179264...",The article develops a typology of EU integrat...
391,"Dualization, crisis and the welfare state",Labour market dualization (an increasing separ...,2-s2.0-84897061563,"Rueda, D.",Socio-Economic Review,2,12.0,Comparative politics; Crises; Labor markets; P...,Article,2014,...,407,scopus,welfarestate_greatrecession,"dualization, crisis and the welfare state",labour market dualization (an increasing separ...,False,"dualization, crisis and the welfare state Labo...","[('economics', 0.38), ('recession', 0.3548), (...","[('state Labour market', 0.002523948234050751)...",The article examines how labour market dualiza...
406,Back from the Cold? Progressive Politics and S...,This article examines the programmatic evoluti...,WOS:001161605900001,"Branco, R; Miro, J; Natili, M",POLITICS & SOCIETY,4.0,52.0,social democracy; post-austerity; social polic...,Article,2024,...,661,wos,socialpolicy_greatrecession,back from the cold? progressive politics and s...,this article examines the programmatic evoluti...,False,back from the cold? progressive politics and s...,"[('recession', 0.2993), ('democratic', 0.2425)...","[('social', 0.05690458799384441), ('Spain', 0....",The article analyzes the evolution of social d...
433,Accumulation or absorption? Changing dispariti...,Abstract This comparative study an...,8ES9M2K8,"Biegert, Thomas; Ebbinghaus, Bernhard",Socio-Economic Review,1.0,20.0,NaN,journalArticle,2022,...,168,manual,manual_greatrecession,accumulation or absorption? changing dispariti...,abstract this comparative study an...,NaN,NaN,NaN,NaN,The study examines how the Great Recession aff...
443,Black swans and elephants on the move: the imp...,This article addresses the question of how une...,FA45G7NU,"Castles, Francis G",Journal of European Social Policy,2.0,20.0,NaN,journalArticle,2010,...,101,manual,manual_greatrecession,black swans and elephants on the move: the imp...,this article addresses the question of how une...,NaN,NaN,NaN,NaN,The article examines how major emergencies inf...
444,Institutional Change after the Great Recession...,NaN,ME4RNHAN,"Cárdenas, Luis; Arribas, Javier",NaN,NaN,NaN,NaN,book,2021,...,NaN,manual,manual_greatrecession,institutional change after the great recession...,NaN,NaN,NaN,NaN,NaN,NaN
445,Challenges to European Welfare Systems,NaN,TLZQ8IHG,NaN,NaN,NaN,NaN,NaN,book,2016,...,NaN,manual,manual_greatrecession,challenges to european welfare systems,NaN,NaN,NaN,NaN,NaN,NaN
446,Changes in Income Distributions and the Role o...,"Abstract In this paper, we examine...",9VQ6ZAUK,"Bargain, Olivier; Callan, Tim; Doorley, Karina...",Fiscal Studies,4.0,38.0,NaN,journalArticle,2017,...,585,manual,manual_greatrecession,changes in income distributions and the role o...,"abstract in this paper, we examine...",NaN,NaN,NaN,NaN,The study analyzes how the 2008–13 economic cr...
447,The Politics of Fiscal Responses to the Crisis...,The national fiscal responses to the economic ...,Q72NY8BV,"Armingeon, Klaus",Governance,4.0,25.0,NaN,journalArticle,2012,...,565,manual,manual_greatrecession,the politics of fiscal responses to the crisis...,the national fiscal responses to the economic ...,NaN,NaN,NaN,NaN,The article analyzes how different national fi...
497,After '08: Social Policy and the Global Financ...,NaN,YFXDXV2V,"McBride, Stephen; Mahon, Rianne; Boychuk, Gera...",NaN,NaN,NaN,NaN,book,2015,...,NaN,manual,manual_greatrecession,after '08: social policy and the global financ...,NaN,NaN,NaN,NaN,NaN,NaN
498,The Times They Are Changing: Crisis and the We...,Some have argued that the concept of the moder...,8938YCZX,"Greve, Bent",NaN,NaN,NaN,NaN,book,2012,...,NaN,manual,manual_greatrecession,the times they are changing: crisis and the we...,some have argued that the concept of the moder...,NaN,NaN,NaN,NaN,The article examines whether the recent global...
499,The welfare state as crisis manager: explainin...,"""Written during an ongoing period of global ec...",FDQUAI4T,"Starke, Peter; Kaasch, Alexandra; Hooren, Fran...",NaN,NaN,NaN,NaN,book,2013,...,NaN,manual,manual_greatrecession,the welfare state as crisis manager: explainin...,"""written during an ongoing period of global ec...",NaN,NaN,NaN,NaN,The book analyzes social policy responses to i...

In [27]:
# display result
with pd.option_context('display.max_colwidth', None):
    display(greatrecession_df[['title', 'authors', 'year', 'abstract', 'abs_summ_gpt-4.1-nano']])

,title,authors,year,abstract,abs_summ_gpt-4.1-nano
91,Is the Welfare State resisting? Recent developments of the social state in OECD countries,"Kerstenetzky, CL; Guedes, GP",2018,"In this paper an attempt was made to analyze some of the main indicators of the evolution of the welfare state in OECD countries between 1980 and 2016. In particular, an assessment was made to evaluate if the so-called Great Recession starting in 2008 led to a contraction of the social state. The analysis focused on three dimensions: social expenditure, funding, and effectiveness. The conclusion drawn was that the twenty-first century has been a period of expansion, both in terms of social expenditure and the catch-up of the latecomers. In particular, all traditional areas of social policy have expanded in tandem with a slight increase in active social policies. The rise in social expenditure has been financed by increasing taxation not thoroughly alien to progressivity principles. Overall, it has been translated into an increased effort for redistribution. However, inequality and poverty are advancing at a higher rate.","The study analyzes welfare state evolution in OECD countries from 1980-2016, finding overall expansion in social expenditure and policy. Despite increased redistribution efforts financed by progressive taxes, inequality and poverty continue to rise, with the Great Recession not causing a contraction of the social state."
92,Welfare State and party political programmes in Spain: A comparative analysis of parties' social profiles,"Ares, C; Losada, A",2019,"Since the start of the Great Recession in 2007, increased concern has emerged about the amount of social expenditure devoted to the elderly in various European societies. In Spain, this debate has been linked to the irruption of two new political parties Podemos (We can) and Ciudadanos (Citizens). This paper presents a methodological proposal that aims to define, in comparative perspective, parties' social policy profiles. It is based on the annotated manifestos issued by the Manifesto Corpus (Merz et al., 2016) and on the Hirschman's conceptual model. The latter summarises critiques of the Welfare State (WS) in three arguments of perversity, futility, and jeopardy. Data from the Manifesto Project on the 94 general elections held in the EU-15 from 1993 onwards, and covered in the 2017b version of its main dataset (729 observations), are used. Parties' positions on the expansion of welfare spending and emphases on social cuts are examined, both at the meso-level of political parties and the macro-level of national Parliaments. In Spain, Podemos and Ciudadanos have not offered to expand social services for the young generations and, moreover, they have paid scarce attention to the elderly. Neither the Partido Popular (PP Popular Party), nor the Partido Socialista Obrero Espanol (PSOE, Socialist Party), have given greater priority to pensions in comparison to other welfare programmes, such as education or employment. Finally, since 1993, the PP Ciudadanos and Union Progreso y Democracia (UPyD, Union, Progress and Democracy) have been the only parties supportive of cuts to social spending, albeit infrequently. The PP has changed its reasons for proposing cuts to social spending over time. By 2016, these reasons were consistent with the idea of the perversity of the welfare state.","The study analyzes European political parties' social policy profiles from 1993-2016 using manifesto data, revealing that in Spain, parties like Podemos and Ciudadanos show limited support for social spending on the elderly, with mainstream parties like PP and PSOE also not prioritizing pensions and occasionally supporting social cuts aligned with critiques of the welfare state."
132,Resisting austerity measures to social policies: Multiple explanatory case studies,"O'Campo, P.; Freiler, A.; Muntañer, C.; Gelormino, E.; Huegaerts, K.; Puig-Barrachina, V.; Mitchell, C.",2019,"Since Margaret Thatcher reached power in the United Kingdom, European governments have increasingly turned to neoliberal forms of policy-making, focusing, especially after the 2008 Great Recession on 'austerity policies' rather than investing in social protection policies. We applied a multiple explanatory case studies methodology to examine how and why challenges and resistance to these austerity measures are successful or not in four settings for three different social policy issues: using a gender lens in state budgeting in Andalusia (Spain), maintaining unemployment benefits in Italy and cuts to fuel poverty reduction programs in Northern Ireland and England. In particular, we intended to learn about whether resistance strategies are shared across disparate cases or whether there are unique activities that lead to successful resistance to austerity policies. As our approach drew from realist philosophy of science, we started with initial theories concerning collective action, political ideology and political power of affected populations. Our findings suggest that there are similarities between the cases we studied despite differences in political and policy contexts. We found that joint action between advocacy groups was effective in resisting cuts to social spending. Evidence also indicates that the social construction of target populations is important in resisting changes to social programmes. This was observed in both England and Northern Ireland where pensioners held significant political clout. © 2018 The Author(s) 2018. Published by Oxford University Press. All rights reserved. For permissions, please email: journals.permissions@oup.com.","The study examines resistance to austerity measures in four settings across Spain, Italy, and the UK, finding that joint advocacy actions and the social framing of target populations, such as pensioners, are crucial for successful opposition despite varying political contexts."
133,US Social Policy in the 21st Century: The Difficulties of Comprehensive Social Reform,"Daguerre, A.",2011,"In Western Europe, political commentators have been surprised by the apparent inability of President Barack Obama to implement comprehensive social policy reform, with the exception of health care legislation. Hopes that President Obama could become a new Roosevelt have been disappointed, precisely at a time when the 'Great Recession' (2007-09) has laid bare the challenge of economic insecurity and poverty in contemporary America. Paradoxically, it is the Presidency's incapacity to address this challenge that partially explains the Democrats' crushing electoral defeat in the mid-term congressional elections in November 2010. This article explains this apparent political paradox in four stages. First, it defines the American social contract - the dream of social mobility through hard work. Second, it shows how this dream has been severely tested by the rise of economic insecurity since the late 1970s and finally the Great Recession. Third, it analyses the social policy responses to the recession, namely the American Recovery Act. To conclude, the comparative timidity of the Obama administration's response is explained by a series of circumstantial and institutional constraints that limit the capacity of the Presidency to implement comprehensive social reform. © 2011 Blackwell Publishing Ltd.","The article analyzes why President Obama's efforts at comprehensive social policy reforms in the US were limited, especially during the Great Recession, attributing this to institutional and circumstantial constraints that hindered the presidency's capacity for broad reform efforts."
134,Familistic welfare capitalism in crisis: Social reproduction and anti-social policy in Greece,"Papadopoulos, T.; Roumpakis, A.",2013,"Familistic welfare capitalism is a model of national political economy prevalent in many regions in the world (Southern Europe, Latin America, and Asia), where the family plays a double role as the key provider of welfare and a key agent in the model's socio-economic and political reproduction. The article offers a new approach to the study this model by adopting an expanded concept of social reproduction to capture its historical evolution, using Greece as a case study. Our empirical analysis of austerity measures on employment and pensions demonstrates, how, in the Greek case, a crisis of social reproduction of the traditional form of familistic welfare capitalism was already underway prior to the well-known sovereign-debt crisis. And further we show how the adoption of austerity measures and pro-market reforms is deepening this crisis by severely undermining the key pillars of familial welfare security while rapidly transforming the model into a political economy of generalised insecurity. © 2013 Taylor & Francis.","The study investigates familistic welfare capitalism in Greece, analyzing how austerity measures have deepened a pre-existing social reproduction crisis by undermining familial welfare pillars, thereby transforming the model into a system of broad insecurity."
242,European health inequality through the Great Recession': social policy matters,"van der Wel, KA; Saltkjel, T; Chen, WH; Dahl, E; Halvorsen, K",2018,"This paper investigates the association between the Great Recession and educational inequalities in self-rated general health in 25 European countries. We investigate four different indicators related to economic recession: GDP; unemployment; austerity and a crisis' indicator signifying severe simultaneous drops in GDP and welfare generosity. We also assess the extent to which health inequality changes can be attributed to changes in the economic conditions and social capital in the European populations. The paper uses data from the European Social Survey (2002-2014). The analyses include both cross-sectional and lagged associations using multilevel linear regression models with country fixed effects. This approach allows us to identify health inequality changes net of all time-invariant differences between countries. GDP drops and increasing unemployment were associated with decreasing health inequalities. Austerity, however, was related to increasing health inequalities, an association that grew stronger with time. The strongest increase in health inequality was found for the more robust crisis' indicator. Changes in trust, social relationships and in the experience of economic hardship of the populations accounted for much of the increase in health inequality. The paper concludes that social policy has an important role in the development of health inequalities, particularly during times of economic crisis.","The study examines how the Great Recession impacted health inequalities in 25 European countries, finding that austerity policies and social factors contributed to increased disparities in health, especially under severe economic downturns, while GDP drops and unemployment were linked to reduced inequalities."
280,Weathering the Storm: Social Policy and the Great Recession,"Maks-Solomon, C; Stoker, RP",2019,"This review discusses recent challenges to the welfare state arising from the Great Recession (GR). The GR was a significant event for social policy analysts, as it tested the responsiveness of welfare systems in the midst of a recent trend toward austerity politics in advanced economies. Social policy changes were part of the toolkit advanced democracies used to respond to the GR, and the welfare state mitigated the consequences of the GR. However, a stark limitation of the social safety net in the United States was the failure to assist immigrant households. The nexus of immigration and social policy is likely to be a significant controversy as we consider the meaning of social citizenship.","This review examines how the Great Recession challenged welfare states, highlighting the responsiveness and limitations of social safety nets, particularly noting the US's failure to aid immigrant households, raising ongoing debates about social citizenship and immigration."
331,Explaining Social Policy Preferences: Evidence from the Great Recession,"Margalit, Y",2013,"To what extent do personal circumstances, as compared to ideological dispositions, drive voters' preferences on welfare policy? Addressing this question is difficult because a person's ideological position can be an outcome of material interest rather than an independent source of preferences. The article deals with this empirical challenge using an original panel study carried out over four years, tracking the labor market experiences and the political attitudes of a national sample of Americans before and after the eruption of the financial crisis. The analysis shows that the personal experience of economic hardship, particularly the loss of a job, had a major effect on increasing support for welfare spending. This effect was appreciably larger among Republicans than among Democrats, a result that was not simply due to a ceiling effect. However the large attitudinal shift was short lived, dissipating as individuals' employment situations improved. The results indicate that the personal experience of an economic shock has a sizable, yet overall transient effect on voters' social policy preferences.","This study uses a four-year panel of Americans to assess how personal economic hardship influences welfare support, finding that job loss significantly increases support, especially among Republicans, but this effect diminishes as employment improves, highlighting the transient impact of economic shocks on social policy preferences."
332,Dynamic social security after the crisis: Towards a new welfare state?,"Diamond, P.; Lodge, G.",2014,"The conservative bias in social attitudes to the welfare state is manifested in entrenched support among the public for traditional welfare and social security benefits, chiefly higher pension payments and public expenditure on health care. This pattern has been reinforced by the 2008 financial crisis and the Great Recession as public support for social protection strategies geared towards ""new"" social risks - structural changes in labour markets, adverse demography, gender inequality, and family instability - has remained relatively weak. This pattern of resistance to change may hardly be surprising given that reforms are more often viewed by the public as a form of retrenchment with clear losers and few obvious beneficiaries. This underlines that political courage is rarely enough to achieve structural reforms of the welfare state. There will need to be clearly defined short-term and long-term objectives underpinned by a coherent rationale capable of persuading publics and citizens of the case for change if a more ""Dynamic"" system of social security is to be enacted in the industrialized countries over the next 20 years. © 2014 International Social Security Association.","The article analyzes public support for traditional versus reform-oriented welfare policies, highlighting strong resistance to change due to perceptions of reforms as retrenchment, and emphasizes the need for clear, persuasive objectives to implement a more dynamic social security system in industrialized countries over the next two decades."
333,"Great Recession, great regression? The welfare state in the twenty-first century","Kerstenetzky, C.; Pereira Guedes, G.",2021,"Has the welfare state undergone significant retrenchment in the aftermath of the 2007-08 crackdown? In the literature, two contrasting views can be found. Some commentators argue that expansions that would otherwise be observed during crises have been suffocated due to the imperative of austerity. Other more optimistic assessments see social investment policies as having been experimented with in various places, alongside widespread retrenchment. In this paper, using an Organisation for Economic Co-operation and Development (OECD) database for 35 countries, we check these assessments by examining aggregate figures, such as the evolution - over the 2007-13 period - of social spending and its composition, the participation of social spending in public expenditure, the tax burden and tax composition and welfare state effectiveness. We document expansion in the OECD area alongside stable performance. However, important challenges persist. © 2020 The Author(s) 2020.","The study analyzes OECD data from 2007-2013 to assess whether the welfare state experienced retrenchment post-2007-08 financial crisis, examining social spending, tax policies, and welfare effectiveness. Results indicate overall expansion and stable performance amidst ongoing challenges."
346,The great recession and welfare state reform: Is retrenchment really the only game left in town?,"van Kersbergen, K.; Vis, B.; Hemerijck, A.",2014,"By 2010, when the Greek sovereign debt crisis changed into an existential crisis of the euro, all developed democracies entered a phase in which they had to consolidate their budgets, typically implying a politics of austerity. The scholarly literature, as well as the popular press, suggests that - consequently - welfare retrenchment and cost containment became the only games left in town. In this article, we study the welfare state reform measures taken between 2010 and 2012 in four countries characteristic of mature welfare state regimes (liberal, UK; conservative, Germany; social democratic, Denmark; and hybrid, the Netherlands) to examine empirically whether austerity has indeed become the only item left on the policy menu. Our analysis reveals that retrenchment features prominently on the agenda everywhere, but nowhere by itself. While compensation for income loss is rare since 2010, this still happens. More unexpectedly, reforms in line with a social investment agenda (like expansion of child care or active labour market policies) are still being pursued in all our four cases. © 2014 John Wiley & Sons Ltd.","The study examines welfare state reforms in four mature democracies during 2010-2012, revealing that austerity measures are prominent but not exclusive, as social investment policies like childcare and active labor market programs continue to be pursued."
347,Public opinion on policy and budgetary trade-offs in European welfare states: evidence from a new comparative survey,"Busemeyer, M.R.; Garritzmann, J.L.",2017,"In the wake of the ‘Great Recession’, welfare states have entered a new phase of austerity. Simultaneously, new social risks and the rise of the knowledge economy fuel new demands on the welfare state. We analyse how demands for social investment policies–particularly education–come into conflict with budgetary concerns, using new survey data on individual-level preferences in eight European countries. Paying particular attention to fiscal and budgetary trade-offs, we find that social investments are generally very popular, but as soon as realistic budget constraints are added, public support drops considerably. The largest drop occurs when social investments would be financed with cutbacks in social transfers rather than higher taxes or higher public debt levels. Furthermore, when studying the determinants of preferences, we find that in the era of permanent austerity distributive conflicts within welfare states exhibit a different political dynamic than conflicts about the size of the welfare state. © 2017 Informa UK Limited, trading as Taylor & Francis Group.","This study examines European public preferences for social investment policies, particularly education, revealing broad support that diminishes significantly when budget constraints prioritize cutbacks over increased taxes or debt, highlighting distinct political dynamics of welfare state conflicts in austerity times."

In [45]:
# save greatrecession_df to 03_analysis

greatrecession_df.to_csv(output_path / f"{date.today()}_greatrecession_analysis.csv", index=False)
print(f"saved to {output_path / f'{date.today()}_greatrecession_analysis.csv'}")

saved to ..\03_analysis\2026-01-28_greatrecession_analysis.csv

## 3. explore covid entries

In [ ]:

# Filter for covid entries
searchruns_filter_covid = [
    "welfarestate_covid",
    "manual_covid",
    "socialpolicy_covid"
]

covid_df = df_enriched[df_enriched['search_run'].isin(searchruns_filter_covid)].copy()
print(f"covid related entries: {len(covid_df)}")
print(f"\nbreakdown by search run:")
print(covid_df['search_run'].value_counts())


with pd.option_context('display.max_colwidth', None, 'display.max_rows', None):
    display(covid_df[['authors', 'year', 'title', 'abstract', 'abs_summ_gpt-4.1-nano']])

covid related entries: 131

breakdown by search run:
search_run
socialpolicy_covid    82
welfarestate_covid    41
manual_covid           8
Name: count, dtype: int64

,authors,year,title,abstract,abs_summ_gpt-4.1-nano
1,"Ebbinghaus, B.; Lehner, L.; Naumann, E.",2022,Welfare state support during the COVID-19 pandemic: Change and continuity in public attitudes towards social policies in Germany,"Our analysis asks whether the pandemic situation affects welfare state support in Germany. The pandemic has increased the health and income risks calling for welfare state intervention. While increased needs, more deservingness, and higher state responsibility during such a crisis would suggest augmented support generally and among those at risk, this might be a short-term effect and cost considerations could reverse this trend. We study public attitudes towards four key social policy areas based on the German Internet Panel (GIP). We use three waves prior and further three waves since the pandemic had been declared in March 2020. The analysis shows both continuity in the popularity of social policies, in particular health and pensions, and some short-term increase in support for unemployment and family policies. The results after nearly 2 years suggest rather continuation with some thermostatic short-term boosts in support instead of any long-lasting change. © 2022 The Authors. European Policy Analysis published by Wiley Periodicals LLC on behalf of Policy Studies Organization.","The study examines German public support for social policies before and during the COVID-19 pandemic, finding mostly stable attitudes with temporary boosts in support for unemployment and family policies, and no long-term change in overall welfare support."
2,"Meagher, K.",2022,"Crisis Narratives and the African Paradox: African Informal Economies, COVID-19 and the Decolonization of Social Policy","This article challenges the role of COVID-19 crisis narratives in shaping social policy choices in Africa. The COVID-19 pandemic has focused attention on Africa's vast informal economies, both as a symbol of the continent's intense vulnerability to the ravages of the pandemic, and as a puzzle in the face of the uneven and limited effects of COVID-19 across the continent. Indeed, an examination of statistical and documentary evidence reveals an inverse relationship between COVID-19 fatalities and the size of African informal economies, and a perverse relationship between best-practice COVID social protection responses and levels of COVID-19 mortality. Scrutinizing the evidence behind African COVID-19 crisis narratives raises questions about the ability of donor-led digitized social protection paradigms to address social needs in highly informalized, low-resource environments. This article highlights the role of crisis narratives as an exercise of power geared to remastering, homogenizing and reimagining African informal economies in ways that facilitate particular types of development intervention, sidelining alternative, more socially grounded policy perspectives. Through a closer examination of historical and contemporary realities in Africa's vast and varied informal economies, the article highlights the need to decolonize social policy by privileging local needs and policy perspectives over global policy agendas in the interest of transformative rather than palliative policy responses. © 2022 The Authors. Development and Change published by John Wiley & Sons Ltd on behalf of International Institute of Social Studies.","The article critiques the framing of COVID-19 as a vulnerability in Africa's informal economies, revealing an inverse correlation between fatalities and informal economy size and questioning the efficacy of donor-led digital social protections. It advocates for decolonizing social policy by prioritizing local needs and perspectives over global narratives to foster transformative solutions."
3,"Nayyar, D.; Malhotra, R.",2023,Economic and Social Policies for Human Development,"Economic and social policies of governments could improve or worsen the wellbeing of people, so that their impact on human development could be positive or negative. This article discusses the role, as well as the scope, of public policies for human development in the contemporary developing and industrialised worlds, buffeted by frequent global and local economic crises, including a health pandemic of unprecedented proportions, where mainstream economic policies have often been detrimental, rather than conducive, to advancing human wellbeing. The paper revisits the human development framework and anchors it in an interpretation of the capability approach that helps in delineating economic and social policy pathways to desirable outcomes. It argues that this is essential for an effective operationalisation of the approach to human development. Building on that, it explores the nature of economic and social policies that might constitute an appropriate policy-mix for advancing human development. In doing so, it recognises that, while human development problems in poor and rich countries are similar, the choices, sequencing and prioritisation of policies will inevitably be determined by the country-context and government-objectives. Given the context, it suggests that the framework of SDGs at the national level could enable a focus on human development objectives in the policy design and strategic response of countries. © 2023 Human Development and Capability Association.","The article examines how government policies impact human development within the capability approach, emphasizing the need for context-specific policy mixes and SDG frameworks to effectively promote well-being amid economic crises and global challenges."
4,"Pavolini, E.; Fullin, G.; Scalise, G.",2023,Labour market dualization and social policy in pandemic times: an in-depth analysis of private consumption services in Europe,"Purpose: This article contributes to the debate on how social policies and labour market regulation have been used to limit the socio-economic consequences of the pandemic by focusing on one specific economic segment of European labour markets: private consumption services, such as trade, tourism, catering and other support services. Design/methodology/approach: The analysis combines mixed methods and a variety of sources. First, we built a set of indicators from the EU-LFS microdata for 2019 and the 2018 Eurostat “Structure of earnings survey” and performed a cluster analysis (k-means) on the dimensions and indicators considered. Second, we elaborated EU-LFS data covering 2019 and 2020 (by quarter) and OECD 2020 data, and finally we traced Covid-related policy reforms for the period March 2020–December 2021 and analysed documents and information collected in different policy repositories. Findings: The paper shows the relevance and characteristics of private consumption services in different countries, demonstrating that so-called labour market “outsiders” are highly represented in this sector and illustrates the policies adopted to respond to the pandemic in different European countries. The paper asks whether this emergency has been a window of opportunity to redefine regulation in this sector, making it more inclusive. It demonstrates, however, that the common approach in Europe has been dominated by temporary, short-term and one-off measures, which do not represent major changes to the social security schemes that were in place before the pandemic. Originality/value: This article builds on the literature on labour market dualization, but approaches the concept from a different perspective – one not centred on the nature of employment relations (stable/unstable) but on economic sectors/branches. This article does not, therefore, discuss in general terms what happened to labour market outsiders during the pandemic, but rather focus attention on a specific group of workers who are highly exposed to risks stemming from dualization: those employed in the private consumption services. The economic sector perspective is an integrative way of framing dualization which is still under-researched. © 2022, Emerald Publishing Limited.","The study analyzes the impact of social policies on private consumption services in Europe during the COVID-19 pandemic, highlighting the sector's high reliance on 'outsiders' and the predominantly short-term policy responses. It suggests that the pandemic did not lead to major reforms but instead reinforced existing sector-specific vulnerabilities."
5,"Chipenda, C.",2022,Comparative Perspectives on Zimbabwe and South Africa’s Social Policy Response to Covid-19,"Zimbabwe and South Africa have been burdened by the challenges of poverty and inequality, a consequence of their historical legacy and post-colonial developmental challenges. To counter these, the development and adoption of progressive social policies has been witnessed. In 2020, the social policy architecture of both countries was put to the test by the Covid-19 pandemic. What has been the social policy response to Covid-19 by the two countries and how effective has it been? This is the major question which this article addresses, utilising the transformative social policy framework as a conceptual and heuristic tool to undertake a comparative analysis of social policy responses to Covid-19. It shows that responses crystallised around cash transfers, food mitigation and health interventions. Although timely, these interventions proved inadequate in addressing the welfare needs of citizens. The article highlights the limitations of the current social policy paradigm in mitigating Covid-19-induced shocks and reducing vulnerability. © Koninklijke Brill NV, Leiden, 2022.","The article compares Zimbabwe's and South Africa's social policy responses to Covid-19 using a transformative framework, revealing that while responses focused on cash transfers, food aid, and health measures, they were ultimately insufficient to meet citizens' welfare needs and address vulnerability."
6,"Cook, S.; Ulriksen, M.S.",2021,"Social policy responses to COVID-19: New issues, old solutions?",NaN,NaN
7,NaN,2021,Global Social Policy Digest 21.3: Managing the fallout from COVID-19,NaN,NaN
8,"Christensen, T.",2021,The Social Policy Response to COVID-19 – The Failure to Help Vulnerable Children and Elderly People,"Norway’s handling of COVID-19 has been seen as a success. Vulnerable groups among young and elderly people, have however, not been part of this success. Their interests have been defocused in two ways. First, they have not been prioritized in the big picture, because the precautionary principle and health concerns, in particular the capacity questions, have dominated. Second, the more specific social policy measures have been indirect and not particular targeted vulnerable children, youths and old people, and had negative effects for them, such as social isolation and lack of daily support and services, resulting in increasing problems. © 2021, The Author(s).","The article examines Norway's largely successful COVID-19 response, noting that vulnerable groups like children, youth, and the elderly were overlooked and negatively impacted by broad policies focused on precaution and health, leading to social isolation and reduced support."
9,"Melugbo, D.; Amara Onwuka, I.",2020,"Demographic variations in public views of response to and management of the COVID-19 pandemic: Examining the perceived roles of public/social policies, government emergency powers and citizen participation","This study examined the demographic variations in public views of response to and management of the Covid-19 pandemic in Nigeria. Specifically, the study assessed the proportion of responses to items on social/public policies designed for the management of the pandemic, government emergency powers with regards to the Covid-19 pandemic and roles of citizens in tackling the challenges that come with the Covid-19 pandemic. A web-based survey design was employed to elicit data from 600 respondents. Findings showed that although many respondents supported the lockdowns of various states and a cessation of social and economic activity, they were not satisfied with the implementation of many of the social policies that the government had designed to respond to and manage the resulting challenges of Covid-19.As to the political response and management of the lockdowns and restrictions due to the Covid-19 pandemic, many people expressed the views that the government and law enforcement agents have abused their emergency powers. Many respondents understood what their roles were as responsible citizens in a time like this. Overall, findings accentuate the likely impact of such socio-demographic factors as gender, age, educational status and financial sufficiency in public views of response to and management of the Covid-19 pandemic in Nigeria. While this study reflects respondents’ assessment or rating of government efforts in addressing the challenges of the Covid-19 pandemic, it also provides a link between socioeconomic vulnerability of social groups and the perceived successes resulting from societal response to and management of the Covid-19 pandemic in Nigeria. © 2020, Goce Delchev University of Shtip. All rights reserved.","The study analyzes Nigerian public views on COVID-19 policies, highlighting mixed support for lockdowns but dissatisfaction with government implementation and concerns over abuse of emergency powers, influenced by socio-demographic factors like gender, age, education, and financial status."
10,"Sengupta, S.; Jha, M.K.",2020,"Social Policy, COVID-19 and Impoverished Migrants: Challenges and Prospects in Locked Down India","As countries shore up existing safeguards to address the social and economic impacts of the COVID-19 pandemic, India faces a humanitarian disaster of unprecedented proportions. Ninety per cent of the Indian workforce is employed in the unorganised sector; uncounted millions work in urban areas at great distances from rural homes. When the Government of India (GOI) announced the sudden ‘lockdown’ in March to contain the spread of the pandemic, migrant informal workers were mired in a survival crisis, through income loss, hunger, destitution and persecution from authorities policing containment and fearful communities maintaining ‘social distance’. In this context, the article analyses how poverty, informality and inequality are accentuated by the COVID-19 pandemic experiences of ‘locked down’ migrant workers. The article examines the nature and scope of existing social policy, designed under changing political regimes and a fluctuating economic climate, to protect this vulnerable group and mitigate dislocation, discrimination and destitution at this moment and in future. © 2020 SAGE Publications.","The article investigates how the COVID-19 lockdown exacerbated poverty, informality, and inequality among India's migrant informal workers, highlighting their survival crises including income loss and destitution, and examines existing social policies aimed at protecting this vulnerable group."
11,"Eichhorst, W.; Marx, P.; Rinne, U.",2020,Manoeuvring Through the Crisis: Labour Market and Social Policies During the COVID-19 Pandemic,"The unprecedented COVID-19 pandemic has a severe impact on societies, economies and labour markets. However, not all countries, socio-economic groups and sectors are equally affected. Part of this disparity can be related to the different role and extent of short-time work, which is now being used more widely than during the Great Recession. Furthermore, unemployment benefits have been made more generous in many countries. While it is still too early to assess the relative success of national strategies to cope with the pandemic and to revitalise the labour market as well as to evaluate the medium-term fiscal viability of different support measures, a few policy directions become apparent. These include the use of digital tools to increase resilience against economic shocks, the longer-term perspective of short-time workers in the current crisis, social protection for self-employed workers that is robust to economic crises and resilient models for school-to-work transitions of younger workers. © 2020, The Author(s).","The abstract explores the varied impacts of COVID-19 on labor markets and policy responses, emphasizing increased use of short-time work, more generous unemployment benefits, and strategies like digital tools and social protection to enhance resilience; however, the long-term effectiveness of these measures remains to be assessed."
12,NaN,2020,Global Social Policy Digest 20.3 and COVID-19: Global social or ‘corona’ policies and governance?,NaN,NaN
13,"Bowpitt, G.",2020,Choosing to be homeless? Persistent rough sleeping and the perverse incentives of social policy in England,"Purpose: With the temporary housing of rough sleepers in response to the Covid-19 emergency, some commentators have been tempted to believe that the rising population of rough sleepers in the UK has finally been reversed. This paper aims to examine the choices made by persistent rough sleepers and how far they are influenced by the perverse incentives of social policies, in order to challenge the view that they sleep rough out of choice. Design/methodology/approach: Evidence for this paper is derived from two teams of frontline service providers with routine familiarity with the rough sleeping population: a street outreach team and a team of support workers working with adults with multiple and complex needs. Primary data from focus groups were combined with the secondary analysis of both numerical and narrative accounts routinely recorded by both teams. Findings: The exercise of agency by persistent rough sleepers is constrained by a mixed baggage of complex needs, past negative risk assessments, limited resources and regulatory deterrents to generate choices to reject help that appear irrational. These need to be understood if recent policy initiatives to end rough sleeping are to be effective. Originality/value: The paper draws on the experience and comprehensive records of practitioners with intimate knowledge of the rough sleeping population. It extends narrative accounts of causes by focusing on key choices to show how the perverse incentives of policy combine with personal factors to incline rough sleeping to persist. © 2020, Emerald Publishing Limited.","The study examines how social policies and personal factors influence the choices of persistent rough sleepers in the UK, revealing that complex needs, negative risk assessments, and regulatory deterrents limit their help-seeking, challenging the view that they sleep rough by choice."

In [28]:
# save greatrecession_df to 03_analysis

covid_df.to_csv(output_path / f"{date.today()}_covid_analysis.csv", index=False)
print(f"saved to {output_path / f'{date.today()}_covid_analysis.csv'}")

saved to ..\03_analysis\2026-01-29_covid_analysis.csv

## 4. explore 'crisis and welfare state' literature

In [34]:

# Filter for 'crisis and welfare state' entries
searchruns_filter_crisis = [
    "welfarestate_crisis",
    "socialpolicy_crisis",
    "distributionalimpact_crisis"
]

crisisws_df = df_enriched[df_enriched['search_run'].isin(searchruns_filter_crisis)].copy()
print(f"crisis and welfare state related entries: {len(crisisws_df)}")
print(f"\nbreakdown by search run:")
print(crisisws_df['search_run'].value_counts())


with pd.option_context('display.max_colwidth', None, 'display.max_rows', None):
    display(crisisws_df[['authors', 'year', 'title', 'abstract', 'abs_summ_gpt-4.1-nano']])

crisis and welfare state related entries: 139

breakdown by search run:
search_run
welfarestate_crisis            72
socialpolicy_crisis            62
distributionalimpact_crisis     5
Name: count, dtype: int64

,authors,year,title,abstract,abs_summ_gpt-4.1-nano
26,"Berten, J.; Grabo, K.; Kaasch, A.; Martens, K.; Meier, S.; Moore, M.; Panaro, A.V.",2025,"Global social policy ideas in the COVID-19 crisis: Ideational change and continuity in the ILO, the OECD, the WHO, and the World Bank","Global crises constitute challenges for social policy. While social policy is predominantly a national concern, international organisations (IOs) contribute frames of reference for state decisions. In this article, we explore whether the COVID-19 pandemic led to changes in IOs' social policy ideas and recommendations in health care, labour market, and social protection policies due to how IOs perceived the crisis' specific nature, severity, and global scope. We focus on four IOs regarded as key actors in global social policy, namely the ILO, OECD, WHO, and the World Bank. Theoretically, we employ a framework of ideational policy change combining different levels (recommendations - including parameters and instruments - and paradigmatic ideas) with different types of change (layering, conversion, dismantlement, and displacement). We find that IOs have not fundamentally reimagined their pre-pandemic stances during the pandemic. The IOs' perceptions of the crisis do not undermine IOs' ideas and recommendations but highlight their appropriateness. © 2025 The Author(s).","The article examines whether the COVID-19 pandemic led to significant changes in international organizations' social policy recommendations in health, labor, and social protection, focusing on ILO, OECD, WHO, and the World Bank. Findings indicate that these organizations largely maintained their pre-pandemic ideas and advice, seeing their recommendations as appropriate despite the crisis."
27,"Wentzlof, C.A.; Boman Iv, J.H.; Pryor, C.; Hemez, P.",2021,"“Kicking the Can down the Street”: Social Policy, Intimate Partner Violence, and Homicide during the Opioid Crisis","Background: Research has established a strong, positive correlation between homicides and substance use and also between homicides and intimate partner violence (IPV). Additionally, there is a well-known, robust, positive relationship between substance use and IPV. Focusing on the opioid crisis and using county-level panel data, this study investigates the possibility that opioid pill prescription trends, IPV, and homicide are intertwined in a complex, interdependent relationship. Objectives: With an eye toward integrated social policy, this study explores the relationships among and between opioid pill distribution patterns, IPV arrests, and homicide arrests within the United States between 2006 and 2012. Methods: Using county-level panel data from several established federal datasets, a series of longitudinal mixed-effects models regress homicide arrests onto the number of pills within each county, IPV arrests, and other relevant controls. Results: While IPV shares a strong, positive main effect relationship with homicide arrests, opioid pill volume is not significantly related to homicides. However, opioid pill volume within a county significantly attenuates the relationship between IPV and homicide, indicating that pills, IPV, and homicides share a complex, interwoven relationship. Conclusion: While the non-significant main effect of opioid pills suggests that opioids are not consequential for homicide, the highly significant interaction between pills and IPV indicates the opposite. Acknowledging the interwoven link between opioids, IPV, and homicide may be of importance when attempting to develop individual programs aimed at addressing these social problems. Well intentioned, unidimensional policies aimed at reducing opioids or IPV may be unknowingly impacting other social problems. © 2021 Taylor & Francis Group, LLC.","This study analyzes county-level data from 2006-2012 to explore the intertwined relationships among opioid pill distribution, intimate partner violence (IPV), and homicides in the US. Results show IPV's strong positive association with homicides and that opioid volume significantly moderates the IPV-homicide link, highlighting a complex interplay that has implications for integrated social policies."
28,"Dhakal, S.P.; Burgess, J.",2021,Decent work for sustainable development in post-crisis Nepal: Social policy challenges and a way forward,"Although the Decent Work agenda has received significant attention in the context of sustainable development, the formulation and implementation of appropriate social policies in developing countries remain an underexplored subject. This article responds to this gap and traces country-specific Decent Work related policies and programs in Nepal—which is recovering from two major crises: a decade-long armed conflict that ended in 2006 as well as the 2015 earthquake. Drawing on Critical Policy Analysis framework, this article examines how key tenets of the International Labour Organisation's Decent Work platform, namely creation and provision of employment, social protection, social dialogue and rights at work have manifested in Nepal. The findings indicate that while attempts have been made to embrace the Decent Work agenda into social policies and programs, structural instability of political processes means that there is a lack of strategic directions to address a capacity deficit specific to the informal sector and outbound labour migrants. The article makes broader analytical contributions towards evaluating the implementation of social policies driven by the global priority in the context of developing nations with weak governance settings. In countries like Nepal, where the majority of workers are located within the informal sector and as such the administrative reach and effectiveness of Decent Work related social policies designed for the formal sector are limited. © 2020 John Wiley & Sons Ltd","The article analyzes Nepal's adherence to the International Labour Organisation's Decent Work agenda amidst post-conflict and earthquake recovery, highlighting attempts and challenges in implementing social policies for employment, social protection, and rights amid political instability and a dominant informal sector."
29,"Vetterlein, A.",2015,Paradigm maintenance: The IMF and social policies after the financial crisis,NaN,NaN
30,"Hall, A.",2015,More of the same: The World Bank’s social policy response to global economic crisis,NaN,NaN
31,"Hermann, C.",2015,Crisis and social policy in Europe,NaN,NaN
32,"Gautam, R.S.",2015,Banking crises and social policy: the case of Latin America and the Caribbean,"This paper examines the social policy consequences of systemic banking crises or financial crises in 13 Latin American and Caribbean countries between 1990 and 2010. It takes a rationalist approach to political economy to analyse the effect of these crises on aggregate social policy spending and on four distinct social welfare policy programmes – education, health, housing, and social security – benefits of which vary across social groups. The results indicate that banking crises have a statistically strong negative effect on aggregate social expenditure, but the impact is not uniform across the four programmes. While social security spending increases during the course of crises, health and education expenditures decrease in the same period. The results reinforce the view that distributional conflicts overshadow governments’ response and the burden of crises is unevenly shared in a heterogeneous society. These findings are robust to alternative specifications. © 2015 Taylor & Francis.","The study analyzes 13 Latin American and Caribbean countries from 1990 to 2010, finding that systemic banking crises reduce overall social spending, especially on health and education, while social security spending increases, highlighting uneven distributional impacts and political conflicts in crisis responses."
33,"Min, S.",2016,The Chinese orientation of social policies of new socialized old-age insurance system in rural areas in the post financial crisis era,"As one of the important social policies, the new socialized old-age insurance system in rural areas has played a vital role in the construction of Chinese social security system in the post financial crisis era. Manifesting national responsibilities, it has embodied the core concept of social policies, and had a great significance for boosting domestic demand. Therefore, this thesis, on the basis of this new system, can continually perfect Chinese pension security system and promote the sustainable development of the social security course. © 2016, Canadian Center of Science and Education. All rights reserved.","The study examines China's rural old-age insurance system, emphasizing its role in social security and domestic demand; it aims to improve and sustain China's pension security framework for social policy development."
34,"Deusdad, B.A.; Comas-d'Argemir, D.; Dziegielewski, S.F.",2016,Restructuring Long-Term Care in Spain: The Impact of The Economic Crisis on Social Policies and Social Work Practice,"ABSTRACT: Care needs of the aging population are increasing in Southern European countries. The purpose of this article is to explore the implications of meeting these needs while taking into account the recent economic crisis, which has deeply affected countries such as Spain. This study is part of a European project (ISCH COST Action IS1102) and is based mainly on qualitative information that focuses on in-depth interviews with social service workers (n = 19) who provide the service and program recipients or their caregivers (n = 14). In addition, two discussion groups were conducted with professionals (n = 9) and program volunteers (n = 5), as well as a workshop/discussion group (n = 28) with politicians, service providers, and participants. Six thematic premises were identified with differing views being highlighted relevant to the participants' roles in the program. Future research should explore social service strategies to deal with the increase in care needs as well as community-based responses. © 2016 Taylor & Francis Group, LLC.","This study examines the care needs of the aging population in Spain amid the economic crisis through qualitative interviews with social workers, recipients, caregivers, professionals, volunteers, and policymakers, identifying six thematic premises and emphasizing the need for future community-based social service strategies."
35,"Parisi, M.L.",2017,"Labor market rigidity, social policies and the labor share: Empirical evidence before and after the big crisis","This paper provides evidence of the impact of three important and general policies shaping the degree of labor market rigidity on the labor share: welfare expenditures, government expenditures on active labor market programs, and passive labor market measures. It analyses the impact of regulation, such as the intensity of employment protection, and evaluates whether trade unions and minimum wage institutions play a role in the relationship between all measures and the labor share. The labor income share has experienced a declining trend since the mid-1970s in most advanced economies, and the existing literature found little if no correlation of this decline to general labor market characteristics. However, the present paper finds that some institutions are correlated to the downward trend, depending on the welfare system adopted, and that welfare and employment protection counteract the decline. Moreover, many countries saw an upsurge in their labor share after the burst of the financial crisis. Evidence of whether the effect of the policies weakened or reinforced the labor share after 2007 is reported. © 2017 Elsevier B.V.","This study examines how three policies—welfare, active and passive labor market measures—and regulations like employment protection influence the declining labor share since the 1970s, finding that welfare and employment protections can mitigate the decline and that the labor share increased post-2007 crisis, with effects varying by country."
37,"Steinebach, Y.; Knill, C.",2017,Social Policy in Hard Times: Crisis-Coping Strategies in Europe from 1976 to 2013,"Scholarly contributions linking welfare state and crisis management literature still lack a consistent conceptualization of the central matter of interest. To remedy this shortcoming, this article provides a classification of four potential crisis-coping strategies and analyzes the policy outputs of 11 European countries from 1976 to 2013 on the basis of an innovative dataset. The analysis shows that strong deviations from the status quo ante are the rule rather than the exception in times of economic hardship. Furthermore, it reveals a clear shift from the crisis-coping strategy of “Social Protectionism” over “Muddling Through” and “Welfare State Restructuring” to “Austerity” over time. © 2017 Taylor & Francis Group, LLC.","This study classifies four crisis-coping strategies and analyzes the policy responses of 11 European countries from 1976 to 2013, revealing frequent deviations from the status quo during economic crises and a temporal shift towards austerity measures over alternative strategies."
38,"Steinebach, Y.; Knill, C.",2018,Social policies during economic crises: an analysis of cross-national variation in coping strategies from 1980 to 2013,"This paper provides a comprehensive analysis of the relationship between economic crises and social policy change for 13 European countries. Based on the degree of policy expansion and dismantling, we identify three potential crisis-coping strategies, namely ‘Muddling Through’, ‘Social Protectionism’ and ‘Austerity’. By means of multinomial logistic regression analysis, we test the effect of various factors on governments’ choice of crisis-coping strategies for 45 economic crises between 1980 and 2013. Our analysis reveals that Austerity becomes a more likely scenario in crisis times. Moreover, we demonstrate that governments in consensual systems do not deviate from their true policy preferences when facing economic hardship. In majoritarian systems, by contrast, this pattern is strikingly reversed. Here, left-wing governments resort to Austerity, while right-wing parties opt for Social Protectionism. This indicates that both blame avoidance and the capabilities to mediate unpopular reform decisions can convert political parties from ‘Saul to Paul’ and vice versa. © 2017, © 2017 Informa UK Limited, trading as Taylor & Francis Group.","This study analyzes how 13 European countries' social policies respond to 45 economic crises (1980-2013), finding that austerity policies become more common during crises, with governmental responses influenced by political system type and ideology, where consensual systems maintain policy preferences, and majoritarian systems see left-wing governments adopt austerity while right-wing governments engage in social protection."
39,"Lammers, I.; Van Gerven-Haanpää, M.M.-L.; Treib, O.",2018,Efficiency or compensation? The global economic crisis and the development of the European Union’s social policy,"How has the global social policy agenda evolved since the global economic crisis? To shed light on this question, this article looks at the discourses in European Union (EU) social policy. It draws on two rival theoretical approaches from the literature on globalisation and the welfare state, the efficiency and compensation hypotheses, and links these approaches to two fundamental rationales underlying the discourse in EU social policy. Based on an analysis of key documents from two Open Methods of Coordination (OMCs), the article shows that the logic underlying the efficiency hypothesis can be extended to discourses in EU social policy. While policy debates in one OMC remained largely unchanged, the discourse significantly shifted towards the economic rationale during and after the crisis in the other OMC. This suggests that the crisis at least partly strengthened the view that social policy should be geared towards economic efficiency, growth, and the creation of jobs. © The Author(s) 2018.","The article examines EU social policy discourses post-global economic crisis, contrasting the efficiency and compensation hypotheses, and finds that in one policy area, discourse shifted towards economic efficiency and growth, indicating the crisis reinforced views linking social policy to economic objectives."
40,"Kourachanis, N.; Lalioti, V.; Venieris, D.",2019,Social policies and solidarity during the Greek Crisis,"This article provides a succinct overview of the phenomenon of solidarization in crisis-ridden Greece. Brief accounts of the pre- and post-crisis situation in four core social policy areas (health, employment, housing, education) are combined with the presentation of four illustrative case studies, one for each of the aforementioned areas. Drawing on a broad range of primary and secondary data, including 20 in-depth interviews with key stakeholders and end-users of the actions examined, we argue that while the crisis provoked a further “residualization” of the institutionalized solidarity system, it also triggered the development of new solidarity ventures, both by state and non-state actors, often even including partnerships between them. These ventures reflect the building of a bridge between institutionalized and informal solidarity in Greece and the shift towards a new type of mixed, although fragmented, mode of solidarity. © 2018 John Wiley & Sons Ltd","The article examines solidarization in Greece during its crisis, analyzing pre- and post-crisis social policies across health, employment, housing, and education through case studies and interviews. It finds that while institutional solidarity declined, new solidarity initiatives emerged, forming a mixed and fragmented system involving both state and non-state actors."

In [37]:
#this section divides the dataframe crisisws_dw into literature that mention covid or financial crisis or neither or both in their title

# Define search patterns for title_normalized (already lowercase)
covid_terms = [
    "covid", "covid-19", "coronavirus", "sars-cov2", 
    "global pandemic", "corona", "pandemic"
]

financial_crisis_terms = [
    "great recession", "subprime mortgage crisis", "subprime crisis",
    "sovereign debt crisis", "housing bubble", "financial crisis"
]

# Create regex patterns
covid_pattern = "|".join(covid_terms)
financial_crisis_pattern = "|".join(financial_crisis_terms)

# Create boolean masks
has_covid = crisisws_df['title_normalized'].str.contains(covid_pattern, na=False, regex=True)
has_financial_crisis = crisisws_df['title_normalized'].str.contains(financial_crisis_pattern, na=False, regex=True)

# Handle special case: "wall street crash" AND "2008"
has_wall_street_2008 = (
    crisisws_df['title_normalized'].str.contains("wall street crash", na=False) & 
    crisisws_df['title_normalized'].str.contains("2008", na=False)
)
has_financial_crisis = has_financial_crisis | has_wall_street_2008

# Create three dataframes
subs_crisis_covid_df = crisisws_df[has_covid & ~has_financial_crisis].copy()
subs_crisis_greatrec_df = crisisws_df[has_financial_crisis & ~has_covid].copy()
subs_crisis_both_df = crisisws_df[has_covid & has_financial_crisis].copy()
subs_crisis_neither_df = crisisws_df[~has_covid & ~has_financial_crisis].copy()

# Print summary
print(f"COVID-related titles: {len(subs_crisis_covid_df)}")
print(f"Financial crisis titles: {len(subs_crisis_greatrec_df)}")
print(f"Both crises mentioned: {len(subs_crisis_both_df)}")
print(f"Neither crisis: {len(subs_crisis_neither_df)}")
print(f"Total: {len(subs_crisis_covid_df) + len(subs_crisis_greatrec_df) + len(subs_crisis_both_df) + len(subs_crisis_neither_df)}")

COVID-related titles: 9
Financial crisis titles: 13
Both crises mentioned: 1
Neither crisis: 116
Total: 139

In [39]:
with pd.option_context('display.max_colwidth', None, 'display.max_rows', None):
    display(subs_crisis_greatrec_df[['authors', 'year', 'title', 'abstract', 'abs_summ_gpt-4.1-nano']])

,authors,year,title,abstract,abs_summ_gpt-4.1-nano
29,"Vetterlein, A.",2015,Paradigm maintenance: The IMF and social policies after the financial crisis,NaN,NaN
33,"Min, S.",2016,The Chinese orientation of social policies of new socialized old-age insurance system in rural areas in the post financial crisis era,"As one of the important social policies, the new socialized old-age insurance system in rural areas has played a vital role in the construction of Chinese social security system in the post financial crisis era. Manifesting national responsibilities, it has embodied the core concept of social policies, and had a great significance for boosting domestic demand. Therefore, this thesis, on the basis of this new system, can continually perfect Chinese pension security system and promote the sustainable development of the social security course. © 2016, Canadian Center of Science and Education. All rights reserved.","The study examines China's rural old-age insurance system, emphasizing its role in social security and domestic demand; it aims to improve and sustain China's pension security framework for social policy development."
54,"Saxonberg, S; Sirovátka, T",2014,From a Garbage Can to a Compost Model of Decision-Making? Social Policy Reform and the Czech Government's Reaction to the International Financial Crisis,"This article argues that the financial crisis did not have a strong impact on Czech social policy. In contrast to the garbage-can model, in which policymakers wait for a 'window of opportunity' to implement radical reforms, the Czech centre-right parties instead used the crisis as a means of continuing their market-liberal reforms that they had initiated before the crisis had even begun. Since they had extremely little public support for their reforms, they tried to bring about gradual change. Thus, instead of pulling radical reforms out of the garbage-can, Czech right-wing politicians have tended to take out smaller biodegradable goods that can decay and compost into fertile ground in order to sow the seeds of gradual change.","The article finds that the Czech social policy was minimally affected by the financial crisis, as right-wing parties utilized the crisis to further pre-existing market-liberal reforms through gradual, manageable changes rather than radical revolutions, despite limited public support."
129,"Ulriksen, M.S.",2011,Social policy development and global financial crisis in the open economies of Botswana and Mauritius,"The manner in which open economies in a globalized world shape social policy development is highly disputed, as is the impact of the current financial crisis on social policy. One argument is that globalization and economic austerity force social policy dismantling. Alternatively, it is proposed that open economies - facing greater volatility, especially during crisis - push for greater social protection. Using the examples of Botswana and Mauritius, two open middle-income countries, this article suggests that, in fact, both arguments may be correct. The impact of globalization and economic crisis depends on the character of the welfare system already in place and the organized interests underpinning it. In Botswana a main social policy thrust is to increase efficiency in spending, whereas issues of job security and compensation are more prevalent in Mauritius. The findings imply that divergence across welfare systems persists and that, even in crisis, countries often use tried social policy solutions. © The Author(s) 2011.","The article examines how globalization and economic crises influence social policy in Botswana and Mauritius, revealing that effects depend on existing welfare systems, with Botswana focusing on efficiency and Mauritius on job security; both countries tend to rely on familiar social policies despite economic challenges."
177,"Schwartz, H.",2012,"Housing, the welfare state, and the global financial crisis: What is the connection?","Analyses of the global financial crisis that assign causality to the erosion of parts of the welfare state that protected individuals miss the importance of macro level regulation that protected firms and the financial system from itself. Post-Depression macro level regulation of finance prevented the emergence of mismatched maturities where deposits lacked state guarantees, and thus prevented runs on banks or near-banks. A balance sheet approach shows that macro regulation linked long duration liabilities in housing finance (mortgages) to long duration assets (pensions). Deregulation permitted the reemergence of mismatched maturities, providing both a necessary and sufficient condition for the current financial crisis. © 2012 SAGE Publications.","The article emphasizes that macro-level financial regulation, by linking long-term liabilities and assets, prevented financial crises, but deregulation reintroduced maturity mismatches, which were crucial in causing the recent financial crisis."
336,"Reeskens, T.; van Oorschot, W.",2014,European feelings of deprivation amidst the financial crisis: Effects of welfare state effort and informal social relations,"As European governments have embraced the credo of austerity, the perennial discussion whether welfare states erode the quality of social networks has taken on a more prominent position on political and social science research agendas. While non-believers of this so-called 'crowding out' thesis argue that social networks flourish well in welfare states, believers argue that welfare provisions render social networks irrelevant in mobilizing resources. Using the 2010 wave of the European Social Survey, we analyse the extent to which both the welfare state and social networks have prevented deprivation, as well as the extent to which the functional quality of social networks in inhibiting impoverishment differs as a function of welfare state generosity. Both the 'crowding out' and the 'crowding in' theses are supported: resources are less mobilized through networks in more generous welfare states precisely because encompassing welfare provisions reduce deprivation significantly, lowering the functional quality of social networks. © The Author(s) 2013.","The study investigates whether welfare states crowd out or promote social networks in preventing deprivation, using 2010 European Social Survey data; findings support both theses—more generous welfare states reduce deprivation, thus diminishing the role and functional quality of social networks in mobilizing resources."
339,"Lynch, J.",2014,The Italian welfare state after the financial crisis,"The essential characteristics of the Italian welfare state as it developed after the Second WorldWar generated social cleavages and inequities that affected the Italian economy and provided grist for future reforms. At the same time, the welfare state provided political actors with incentives and resources that constrained attempts at reform. With the financial crisis beginning in 2008, serious reform was no longer optional. But austerity politics have generated pressures for changes to the welfare state which are unlikely to moderate most of the underlying inequities generated by the post-war system. Going forward, Italian policymakers must chart a path that is informed by efforts to overcome the pathologies of the past without further undermining the social and economic health of the country. © 2014 Taylor and Francis.","The article examines Italy's post-WWII welfare state, highlighting how it created social inequalities that constrained reforms, and discusses the challenges of implementing austerity-driven changes without exacerbating existing inequities amid ongoing economic crises."
345,"Vis, B.; van Kersbergen, K.; Hylands, T.",2011,To what extent did the financial crisis intensify the pressure to reform the welfare state?,"If ever there was momentum to roll back the welfare state, it is the (aftermath) of the financial crisis of 2008-09. All theoretical perspectives within comparative welfare state research predict radical reform in this circumstance, but does it also happen? Our data indicate that - at least so far - it does not. Focusing on a selection of advanced welfare states (the UK, the USA, Germany, the Netherlands, Denmark and Sweden), we find that these countries face similar problems and that their initial response to these problems is also similar. The latter is surprising because, theoretically, we would expect varying responses across welfare state regime types. Rather than retrenchment, we observe a first phase of emergency capital injections in the banking sector and a second of Keynesian demand management and labour market protection, including the (temporary) expansion of social programmes. Continuing public support for the welfare state was a main precondition for this lack of immediate radical retrenchment. However, the contours of a third phase have become apparent now that budgetary constraints are forcing political actors to make tough choices and introduce austerity policies. As a result, the question of who pays what, when, and how will likely give rise to increasingly sharp distributional conflicts. © 2011 Blackwell Publishing Ltd.","The article examines the response of advanced welfare states to the 2008-09 financial crisis, finding that despite expectations of radical reform, these countries initially engaged in emergency financial measures and social program expansions rather than retrenchment, with potential austerity policies raising future distributional conflicts."
367,"Holliday, I",2005,East Asian social policy in the wake of the financial crisis: farewell to productivism?,"For some years, a productivist strand characterised debates about a possible East Asian welfare model. However, recent policy initiatives, prompted partly by the Asian financial crisis and partly by far wider economic, social and political changes, cast doubt on the continuing validity of the productivist thesis in an East Asian context. This article reviews the evidence, and argues that while social policy has some nonproductivist tendencies in South Korea and Taiwan in particular, they are not as substantial and significant as is sometimes held. It concludes that it is not yet time to discard productivism, which remains plausible and useful in analysing social policy systems in the region.","The article reviews evidence on East Asian social policy, arguing that although some nonproductivist tendencies exist in South Korea and Taiwan, the productivist model remains a valid and useful framework amid recent socio-economic changes."
393,"De Haan, A",2010,A DEFINING MOMENT? CHINA'S SOCIAL POLICY RESPONSE TO THE FINANCIAL CRISIS,"This paper discusses whether China's response to the 2008-2009 financial crisis is a 'defining moment', whether it is leading to a departure of China's export-driven development model and whether the large stimulus package is strengthening its social policies and leading towards a more egalitarian structure. Two years after the crisis, it seems China has been very successful in managing the crisis, reaffirming political legitimacy, monitoring potential social unrest and introducing a wide range of promotive measures, even though this did not imply the sudden shift to promotion of household consumption some observers were arguing for. Copyright (C) 2010 John Wiley & Sons, Ltd.","The article evaluates China's 2008-2009 crisis response, highlighting its successful management and political legitimacy reinforcement, without a notable shift towards consumer-led growth or significant social policy changes."
478,"Hallerberg, M.",2013,Challenges for the German welfare state before and after the global financial crisis,NaN,NaN
480,"Parkinson, P.",2011,Another inconvenient truth: Fragile families and the looming financial crisis for the welfare state,NaN,NaN
481,"Drahokoupil, J.; Myant, M.",2010,"Varieties of capitalism, varieties of vulnerabilities: Financial crisis and its impact on welfare states in Eastern Europe and the commonwealth of independent states","This paper investigates the implications of the 2008 financial crisis on welfare states and the capitalist diversity in the post-communist world, including Eastern Europe and the Commonwealth of Independent States. It analyzes three political-economic varieties in the region: those of capitalism, welfare, and vulnerabilities to the crisis. The three varieties are linked, but there is also a considerable variation given the importance of political and policy factors. Economic growth models created different political and economic constraints on policies of adjustment to the crisis. In particular, currency substitution was associated with strong political preferences for defending exchange rates, with adjustment through reductions in public spending and wages. A variety of welfare models was associated with different political constituencies for welfare provision. The interplay of these constraints and political factors together with intervention of international institutions shapes the nature of welfare state adjustments. Early developments also indicate some unexpected outcomes. financial crisis, welfare state, varieties of capitalism, Eastern Europe, Russia, Commonwealth of Independent States.","This study examines how the 2008 financial crisis affected welfare states and capitalist diversity in Eastern Europe and CIS countries, highlighting the role of political and policy factors, economic models, and international interventions in shaping varied welfare adjustments and outcomes."

## 5. explore global south entries

In [5]:
# Filter for Global South entries
searchruns_filter_globalsouth = [
    "globalsouth_countrylist_inequality_poverty_covid_greatrecession",
    "globalsouth_synon_socialpolicy_inequality_welfarestate_covid_greatrecession_csv",
    "globalsouth_countrylist_socialpolicy_covid_greatrecession",
    "manual_globalsouth"
]

globalsouth_df = df_enriched[df_enriched['search_run'].isin(searchruns_filter_globalsouth)].copy()
print(f"Global South related entries: {len(globalsouth_df)}")
print(f"\nbreakdown by search run:")
print(globalsouth_df['search_run'].value_counts())



with pd.option_context('display.max_colwidth', None, 'display.max_rows', None):
    display(globalsouth_df[['authors', 'year', 'title', 'abstract', 'abs_summ_gpt-4.1-nano']])

Global South related entries: 95

breakdown by search run:
search_run
globalsouth_countrylist_inequality_poverty_covid_greatrecession                    75
globalsouth_synon_socialpolicy_inequality_welfarestate_covid_greatrecession_csv    13
globalsouth_countrylist_socialpolicy_covid_greatrecession                           5
manual_globalsouth                                                                  2
Name: count, dtype: int64

,authors,year,title,abstract,abs_summ_gpt-4.1-nano
0,"Faria, L; Alvarez, REC; Santos, LAD",2023,Socioeconomic inequality in Latin America and the Caribbean: the post-pandemic future for the training of health professionals,"Inequality is a global, structural problem that is particularly marked in the world's poorest countries. The covid-19 pandemic exacerbated this historic problem in Latin America and the Caribbean and deepened uncertainties in relation to basic human needs. This study presents an overview of the subject on the basis of official reports from international agencies (PAHO, WHO, ECLAC) between 2019 and 2022 and discusses some paths for the training of health professionals in Brazil. It also investigates how health practices could be changed to ensure greater social protection for vulnerable populations, based on the proposals of Paulo Freire and Edgar Morin, which highlight current social and health problems.","The study reviews official reports from 2019-2022 on inequality and health in Latin America, focusing on the COVID-19 pandemic's impact and exploring ways to enhance social protection through educational and ethical practices inspired by Freire and Morin to address vulnerabilities."
206,"Dantas, MNP; Silva, MDD; Barbosa, IR",2022,Reflections on the COVID-19 mortality among the Black population and racial inequality in Brazil,"This literature critical analysis reflects on the social, political, and historical background responsible for racial discrepancies in hospital mortality by COVID-19 among the Brazilian population. During the pandemic, the COVID-19 mortality among the Black population gained notoriety. Rather than an isolated fact, this finding has historical roots dating back to Brazil???s foundation and draws on structural racism, which reveals degrading living and health conditions experienced by the Black population before the pandemic. This situation of vulnerability affecting the Black population is a recurring scenario that is treated with the neglect inherent to structural racism. COVID-19 mortality portrays one way in which racism impacts and reproduces itself in the life and death of Black people.","This analysis examines how structural racism contributes to racial disparities in COVID-19 hospital mortality among Brazilians, highlighting historical and social factors leading to higher mortality rates among Black populations. It underscores that COVID-19 mortality is a manifestation of ongoing racial inequality rooted in Brazil's history of systemic racism."
207,"Wu, XF; Sun, ZW; Cheng, JL",2022,Who suffers from COVID-19 shock? Labour market risk and wage inequality in China,"Through an online survey from 2020, this study aims to investigate how labour market status and occupational factors shape the risk of wage drops resultant of the COVID-19 outbreak. Quantitative evidence shows the risk is amplified for lower-educated labourers working in administrative positions, and affiliated to the traditional service sector and foreign invested enterprises (FIE) and they are more likely to experience earning reduction. COVID-19 in China witnesses a significantly downward trend of labours` wage and general wage inequality has slightly eased. This study calls for policy shift in direct financial subsidies to workers to mitigate labours' risk.","This study investigates how labour market status and occupational factors affected wage drops due to COVID-19, with findings indicating higher risk for lower-educated workers in administrative, service, and foreign-invested sectors. Results show a general decline in wages with slight easing of wage inequality, suggesting policy needs for targeted financial support to workers."
208,"Ma, GM; Zhang, JY; Hong, L",2023,Learning From Home: Widening Rural-Urban Educational Inequality and High School Students' Self-Control in China During the COVID-19 Pandemic and School Closure,"Worldwide school closures and remote learning have been implemented during the COVID-19 pandemic. These measures' impact on young populations' academic achievements is unclear. This study ( N = 1,736, ages 14-20 years, 53% female, and Chinese) analyzed academic examination scores for students at a high school in Eastern China between January and July 2020. Results showed that overall, students' academic achievements appeared to be negatively affected amid a school closure. More importantly, students' self-control was introduced as a moderating factor that partially accounted for this difference in the context of remote learning at home. These findings extended our understanding of school closures' unequal impact on young populations. Education and social policies should respond to these challenges during times of crisis.","This study analyzed academic scores of 1,736 Chinese high school students during COVID-19 school closures, finding a general decline in achievement with self-control mitigating this effect. Results highlight the need for policies addressing the unequal impact of remote learning during crises."
209,"You, JL; Zhang, JH; Li, Z",2022,Consumption-Related Health Education Inequality in COVID-19: A Cross-Sectional Study in China,"BackgroundThe COVID-19 pandemic influences various aspects of society, especially for people with low socioeconomic status. Health education has been proven to be a critical strategy in preventing a pandemic. However, socioeconomic characteristics may limit health education among low socioeconomic status groups. This study explores consumption-related health education inequality and the factors that contribute to this, which are variable across China during COVID-19. MethodsThe 2020 China COVID-19 Survey is a cross-sectional study in China, based on an anonymous online survey from 7,715 samples in 85 cities. It employed machine-learning methods to assess household consumption and other contributing variates associated with health education during the pandemic. Concentration Index (CI) and Horizontal Index (HI) were used to measure consumption-related inequalities in health education, respectively. Moreover, Wagstaff decomposition analysis was employed to identify other contributing variables to health education inequality. ResultsThe result indicates that participants with more education, better income, and positive consumption preferences undertake higher health education during COVID-19. The CI and HI of consumption-health education inequality are 0.0321 (P < 0.001) and 0.0416 (p < 0.001), respectively, which indicates that health education is concentrated in wealthy groups. We adapted Lasso regression to solve issues and omit variables. In terms of other socioeconomic characteristics, Annual Income was also a major contributor to health education inequalities, accounting for 27.1% (P < 0.001). The empirical results also suggests that education, health status, identification residence, and medical health insurance contribute to health education inequality. ConclusionsThe difference in Household consumption, annual income, rural and urban disparity, and private healthcare insurance are critical drivers of health education inequality. The government should pay more attention to promoting health education, and healthcare subside policy among vulnerable people. Significantly to improve awareness of undertaking health education with lower education, rural residential, to enhance confidence in economic recovery and life after COVID-19.","This study analyzes consumption-related health education inequality during COVID-19 in China, revealing that higher education, income, and urban residence are associated with greater health education access, which is concentrated among wealthier groups. It highlights that socioeconomic factors like income, education, and healthcare insurance significantly contribute to this inequality, suggesting policy focus on vulnerable populations to improve health education equity."
210,"Cheong, TS; Wu, YR; Wojewodzki, M; Ma, N",2021,The Impacts of Globalization on Inequality in the Post-COVID-19 World: Evidence From China,"Empirical studies suggest that globalization (FDI and international trade) has been greatly affected by the COVID-19 and related anti-pandemic measures imposed by governments worldwide. This paper investigates the impact of globalization on intra-provincial income inequality in China and the data is based on the county level. The findings reveal that FDI is negatively associated with intra-provincial inequality, intra-provincial inequality increases as the primary industry sector (agriculture) declines. The result also finds that the increase in inequality stems not from the development in the tertiary or secondary industry sectors per se, but the unevenness in the distribution of these sectors.","The study examines how globalization influences intra-provincial income inequality in China, finding that FDI reduces inequality while sectoral unevenness—especially the decline of agriculture—drives inequality increases, independent of sector development levels."
211,"Ferris, R; Clarke, M; Raftery, D; Liddy, M; Sloan, S",2022,Digital poverty in a country that is digitally powerful: some insights into leadership of girls' schooling in India under Covid-19 restrictions,"This paper examines leadership challenges in managing digital power and digital poverty, in the delivery of schooling during the Covid-19 emergency lockdown in India. The article suggests that although India is considered a global leader in digital technology, its primary and secondary school system suffers from digital poverty with associated tensions for school leadership. The paper explores the nature of teaching and learning in a selection of girls' schools in India during Covid-19. In the context of the pandemic, school leaders have had to respond quickly to remote learning, supporting teachers to facilitate the use of educational technology. Our research examined the experience of leadership in a cross section of schools from different geographical and socio-economic backgrounds. The respondents reflected on their engagement with digital literacy and remote teaching methodologies, and how the pandemic changed the classroom experience with little or no lead in time to adapt. The article examines how Indian women in positions of educational leadership perceive digital power or poverty and how it affects change and challenge in their leadership responsibility. Conclusions are drawn regarding educational practices operational at present and anticipate considerations which must be acknowledged to support virtual learning into the future.","The article investigates leadership challenges in managing digital power and poverty in Indian schools during Covid-19, analyzing responses from female leaders across diverse schools and highlighting how the pandemic shifted remote teaching and digital literacy efforts, with implications for future virtual learning."
212,"Doruk, ÖT",2025,COVID-19 and youth unemployment in MENA countries: a matching approach,"The present study uses a rich dataset containing more than 1900 individuals from three important MENA countries: Egypt, Morocco, and Tunisia. The dataset is based on the Economic Research Forum (ERF) COVID-19 MENA Monitor, which consists of household and individual-level surveys during the COVID-19 period for these three MENA countries. The present study examines the effect of COVID-19 on youth unemployment in MENA countries in the post-COVID-19 period. Using a rich individual-level dataset, propensity score matching analysis is utilized. The propensity score matching analysis effectively controls unobservable differences across individuals during the pandemic. The propensity score matching analyses show that young employes were more likely to become unemployed than their older counterparts during the pandemic period. Furthermore, the results also show that young workers with formal contracts have a higher probability of becoming unemployed than their male and older counterparts with formal and informal contracts. The policymakers can design a policy framework to minimize this problem during external shocks.","The study uses data from Egypt, Morocco, and Tunisia to analyze COVID-19's impact on youth unemployment, finding that young workers, especially those with formal contracts, faced higher unemployment risks during the pandemic through propensity score matching analysis. Results suggest policy measures are needed to mitigate these risks during external shocks."
213,"Lamontagne, E; Nyako, HY; Enemo, A; Sunday, A; Muhammad, A; Abdullah, RM; Okiwu, H; Undelikwo, V; Ogbozor, P; Amusan, O; Alaba, O; Undelikwo, G; Takpa, K; Ashefor, G; Kavanagh, M; Foláyan, MO",2023,"The health inequity and socioeconomic inequality faced by adolescent girls and women on the move living with or at high risk of HIV infection, during the COVID-19 pandemic in Nigeria","BackgroundWe assessed if women and girls on the move living with or at high risk of HIV faced increased health inequity and socioeconomic inequalities during the COVID-19 pandemic compared with other vulnerable women and girls.MethodsWe used data collected through a survey conducted in Nigeria between June and October 2021. Women and girls living with or at risk of HIV were recruited voluntarily, using a combination of venue-based and snowball sampling. We performed multivariable logistic regression models per mobility and HIV status to determine associations between health inequity, socioeconomic inequalities and macrosocial characteristics.FindingsThere were 3442 participants, of which 700 were on the move. We found no statistical difference between HIV-negative women and girls on the move and those not on the move. On the opposite, we found substantial differences in health inequity and socioeconomic inequalities between women and girls on the move living with HIV and those not on the move living with HIV. There are very strong associations between being a woman or girl on the move living with HIV and facing economic precarity (aOR 6.08, 95% CI 1.94 to 19.03), food insecurity (aOR 5.96, 95% CI 2.16 to 16.50) and experiencing more gender-based violence since COVID-19 started (aOR 5.61, 95% CI 3.01 to 10.47).InterpretationBeing a woman or girl on the move and living with HIV compound increased health and socioeconomic vulnerabilities. The COVID-19 crisis seems to have exacerbated inequalities and gender-based violence. These findings call for more feminist interventions to protect women on the move living with HIV during health crises.","The study found that women and girls on the move living with HIV in Nigeria faced significantly increased health and socioeconomic inequalities, including economic precarity, food insecurity, and gender-based violence, especially during the COVID-19 pandemic, highlighting the need for targeted feminist interventions."
214,"Li, X; Li, YD; Li, YK; Lopez, R",2025,"The Effect of COVID-19 on Poverty-Alleviated Households: Evidence from J City, China","This paper estimates the causal effect of the COVID-19 pandemic on the per capita income of poverty-alleviated households (PAHs). Using administrative tracking panel data from a Chinese city, we leverage quasi-experimental variation in county-level pandemic deaths and policies. We find that the COVID-19 pandemic reduced the income of PAHs by nearly 14.78%. Additionally, each confirmed COVID-19 case was associated with a 2.02% reduction in income. Moreover, heterogeneity analysis reveals that the negative effect is more pronounced among households with less education and those that had recently overcome poverty. Finally, our findings highlight the effectiveness of China's industrial-assistance policies, which have significantly mitigated the negative effect of the COVID-19 pandemic on the income of PAHs.","The study finds that COVID-19 caused a nearly 15% reduction in income among poverty-alleviated households in a Chinese city, with effects more severe for less-educated and recently impoverished households, but China's industrial-assistance policies helped mitigate these impacts."
215,"Brzezinski, M",2018,Income inequality and the Great Recession in Central and Eastern Europe,"This paper uses data from the European Union Statistics on Income and Living Conditions (EU-SILC) to study changes in income inequality in Central and Eastern Europe during the Great Recession (2008-2012) and its determinants. Changes in inequality are decomposed using an Oaxaca-Blinder-like decomposition analysis based on the Recentered Influence Function (RIF) methodology, which allows splitting the overall change in inequality into endowment effects associated with changes in the distribution of inequality covariates and coefficient effects, which are related to changing returns to these covariates. Our results show that the Gini for disposable incomes has increased in a statistically significant way over 2008-2012 for Bulgaria, Estonia, Hungary and Slovenia. For most of the countries with significant increases in inequality, a falling full-time employment rate played the biggest role in explaining changes in inequality, accounting for about 50-60% of the Gini change for disposable incomes and about 60-80% of the Gini change for market incomes. The fall in the full-time employment rate had a smaller inequality-increasing effect for disposable incomes in Hungary (about 15% of the Gini increase). Increased part-time employment during the recession had either no impact on inequality or was rather inequality-decreasing. We did not find evidence that changes in the incidence of temporary jobs had any impact on income inequality.","The study examines income inequality changes in Central and Eastern Europe during the 2008-2012 Great Recession using EU-SILC data, finding significant increases in the Gini coefficient in several countries primarily driven by declines in full-time employment, while part-time and temporary jobs had minimal or counteracting effects."
216,"Valensisi, G",2020,COVID-19 and Global Poverty: Are LDCs Being Left Behind?,"The paper provides a preliminary assessment of COVID-19's impact on global poverty in the light of IMF's growth forecasts. It shows that the pandemic will erode many of the gains recorded over the last decade in terms of poverty reduction. Our baseline case suggests that globally the number of people living below US$1.90 per day will increase by 68 million in 2020 alone; this rise could however approach 100 million, should the recession turn out to be more severe than initially expected, as many practitioners fear. Without effective international support, this setback will pose a critical threat to the achievement of the United Nations 2030 Agenda for Sustainable Development. The fallout from the pandemic will also exacerbate the geographic concentration of poverty, to the extent that the Least Developed Countries, with only 14% of the global population, are set to represent the main locus of extreme poverty worldwide.","The article assesses COVID-19's impact on global poverty, estimating an increase of 68 million people below US$1.90/day in 2020, potentially rising to 100 million in a severe recession, predominantly affecting Least Developed Countries and threatening progress towards sustainable development goals."