# step 3 — pooled union: compilation & inspection

Compiles the union of System 1 (cosine similarity) and System 2 (BERTopic) candidates,
saves `_pooled_union.json`, and provides cells for reviewing the candidate set.

**Union rationale:** the union (not intersection) maximises recall — both systems have
independent failure modes, and any document missed by one may be caught by the other.

| section | what it shows |
|---|---|
| §3 | summary counts by source system + year distribution |
| §4 | high-confidence docs found by both systems |
| §5 | docs found only by cosine similarity |
| §5a | **decision:** which System-1-only policies to include (index list) |
| §6 | docs found only by BERTopic — inspect topic by topic |
| §6a | **decision:** which BERTopic topics to keep |
| §7 | noise pool spot-check (topic -1) |
| §8 | compile final policy set & save |
| §9 | export evaluation log (Markdown) |

In [9]:
import gzip
import json
import random
import pandas as pd
from pathlib import Path
from IPython.display import display

pd.set_option('display.max_colwidth', 120)
pd.set_option('display.max_rows', None)

# ── CONFIGURATION ─────────────────────────────────────────────────────────────

def _find_root(marker='CLAUDE.md'):
    for p in [Path.cwd(), *Path.cwd().parents]:
        if (p / marker).exists():
            return p
    raise FileNotFoundError('project root not found — run from within the project directory')

PROJECT_ROOT      = _find_root()
OUTPUT_PREFIX     = 'germany_2008-2015_2019-2022'
BASE              = PROJECT_ROOT / 'data' / 'processed' / 'germany'

S1_FILE           = BASE / f'{OUTPUT_PREFIX}_cosinesim_final.json' #selection from system 1, cosine similarity
S2_FILE           = BASE / f'{OUTPUT_PREFIX}_berttopic_candidates.json' #policies that are in social policy relevant topics (from triage)
NOISE_FILE        = BASE / f'{OUTPUT_PREFIX}_berttopic_noise_pool.json' #policies that could not be matched to any topic  at all
TOPIC_ASSIGN_FILE = BASE / f'{OUTPUT_PREFIX}_berttopic_topic_assignments.json.gz' #all policies with their assigned topics
TOPIC_INFO_FILE   = BASE / f'{OUTPUT_PREFIX}_berttopic_topic_info.json'
OUT_FILE          = BASE / f'{OUTPUT_PREFIX}_pooled_union.json'

## §1. Load data

In [10]:
s1_docs    = json.loads(S1_FILE.read_text(encoding='utf-8'))
s2_docs    = json.loads(S2_FILE.read_text(encoding='utf-8'))
noise_docs = json.loads(NOISE_FILE.read_text(encoding='utf-8')) if NOISE_FILE.exists() else []
topic_info = json.loads(TOPIC_INFO_FILE.read_text(encoding='utf-8')) if TOPIC_INFO_FILE.exists() else []

if TOPIC_ASSIGN_FILE.exists():
    with gzip.open(TOPIC_ASSIGN_FILE, 'rt', encoding='utf-8') as _fh:
        topic_assign = json.load(_fh)
else:
    topic_assign = []

print(f'System 1 (cosine similarity):   {len(s1_docs):>4} candidates')
print(f'System 2 (BERTopic):            {len(s2_docs):>4} candidates')
print(f'System 2 Noise pool (topic -1): {len(noise_docs):>4} docs')

System 1 (cosine similarity):    593 candidates
System 2 (BERTopic):             892 candidates
System 2 Noise pool (topic -1):  791 docs

## §2. Compile union & save

In [4]:
s1_by_title = {d['title'].strip(): d for d in s1_docs}
s2_by_title = {d['title'].strip(): d for d in s2_docs}
all_titles  = sorted(set(s1_by_title) | set(s2_by_title))

union  = []
counts = {'both': 0, 's1_only': 0, 's2_only': 0}

for title in all_titles:
    in_s1  = title in s1_by_title
    in_s2  = title in s2_by_title
    base   = s1_by_title[title] if in_s1 else s2_by_title[title]
    source = 'both' if (in_s1 and in_s2) else ('s1_only' if in_s1 else 's2_only')
    union.append({**base, 'system_sources': source})
    counts[source] += 1

union.sort(key=lambda x: x.get('date_published', ''))
OUT_FILE.write_text(json.dumps(union, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'Saved {len(union)} candidates to {OUT_FILE.name}')

df_union = pd.DataFrame(union)
df_union['year'] = pd.to_datetime(df_union['date_published'], errors='coerce').dt.year

Saved 1059 candidates to germany_2008-2015_2019-2022_pooled_union.json

## §3. Overview

In [19]:
n_both  = counts['both']
n_s1    = counts['s1_only']
n_s2    = counts['s2_only']
n_total = len(union)

pd.DataFrame({
    'n': [n_both, n_s1, n_s2, n_total],
    'share': [f'{n_both/n_total:.0%}', f'{n_s1/n_total:.0%}', f'{n_s2/n_total:.0%}', '100%'],
}, index=['both systems (high confidence)', 'System 1 only (cosine sim)', 'System 2 only (BERTopic)', 'total'])

                                   n share
both systems (high confidence)   345   33%
System 1 only (cosine sim)       212   20%
System 2 only (BERTopic)         502   47%
total                           1059  100%

In [ ]:
pd.crosstab(df_union['year'], df_union['system_sources'], margins=True)

## §4. High-confidence candidates (both systems)

Found by both cosine similarity and BERTopic — the strongest candidates.

In [ ]:
df_both = df_union[df_union['system_sources'] == 'both'][['title', 'date_published', 'year']].reset_index(drop=True)
print(f'{len(df_both)} docs found by both systems')
df_both

## §5. System 1 only (cosine similarity)

Found by cosine similarity but not by BERTopic — vocabulary close to seed descriptions
but did not cluster with other welfare-policy laws.

In [5]:
df_s1 = df_union[df_union['system_sources'] == 's1_only'][['title', 'date_published', 'year']].reset_index(drop=True)
print(f'{len(df_s1)} docs found only by cosine similarity')
df_s1

212 docs found only by cosine similarity

,title,date_published,year
0,Verordnung zur Übertragung der Befugnis zum Erlass von Rechtsverordnungen nach dem Dritten Buch Sozialgesetzbuch auf...,2008-01-25T00:00:00Z,2008
1,Verordnung über die Berufsausbildung zum Personaldienstleistungskaufmann/zur Personaldienstleistungskauffrau,2008-02-29T00:00:00Z,2008
2,Bekanntmachung nach § 141 Abs. 11 Satz 2 des Arzneimittelgesetzes,2008-03-31T00:00:00Z,2008
3,Verordnung zur Änderung der Arzneimittel- und Wirkstoffherstellungsverordnung,2008-04-04T00:00:00Z,2008
4,Verordnung über die Mindestbeitragsrückerstattung in der Lebensversicherung (Mindestzuführungsverordnung),2008-04-11T00:00:00Z,2008
5,Verordnung zur Vermeidung unbilliger Härten durch Inanspruchnahme einer vorgezogenen Altersrente (Unbilligkeitsveror...,2008-04-17T00:00:00Z,2008
6,Hinweis:Bundesgesetzblatt Teil II Nr. 10,2008-05-26T00:00:00Z,2008
7,"Verordnung über die Zuweisungen an das Sondervermögen ""Versorgungsfonds der Bundesagentur für Arbeit"" ( VFBAZV)",2008-06-16T00:00:00Z,2008
8,Fünfte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2008-06-25T00:00:00Z,2008
9,Erstes Gesetz zur Änderung des Jugendschutzgesetzes,2008-06-30T00:00:00Z,2008
10,Gesetz zur Erleichterung familiengerichtlicher Maßnahmen bei Gefährdung des Kindeswohls,2008-07-11T00:00:00Z,2008
11,Fünfzehnte Verordnung zur Anpassung des Bemessungsbetrages und von Geldleistungen nach dem Bundesversorgungsgesetz (...,2008-07-25T00:00:00Z,2008
12,Hinweis:Bundesgesetzblatt Teil II Nr. 18,2008-07-25T00:00:00Z,2008
13,Dreizehnte Verordnung zur Neufestsetzung der Beträge nach § 7 Abs. 1 des Gesetzes zur Hilfe für Frauen bei Schwanger...,2008-08-01T00:00:00Z,2008
14,Gesetz über die Anpassung von Dienst- und Versorgungsbezügen im Bund 2008/2009 (Bundesbesoldungs- und -versorgungsan...,2008-08-01T00:00:00Z,2008
15,Neufassung des Unterhaltssicherungsgesetzes,2008-09-05T00:00:00Z,2008
16,Gesetz zur Modernisierung des GmbH-Rechts und zur Bekämpfung von Missbräuchen (MoMiG),2008-10-28T00:00:00Z,2008
17,"Verordnung zur Durchführung des § 1 Abs. 1 und 3, des § 30 Abs. 1 und des § 35 Abs. 1 des Bundesversorgungsgesetzes ...",2008-12-15T00:00:00Z,2008
18,Anordnung über die Ausübung der Disziplinarbefugnisse bei Ruhestandsbeamtinnen und Ruhestandsbeamten im Deutschen Pa...,2009-01-15T00:00:00Z,2009
19,Verordnung zur Aussetzung und Ergänzung von Merkmalen nach dem Verdienststatistikgesetz (Verdienststatistikverordnun...,2009-01-15T00:00:00Z,2009
20,"Erste Verordnung zur Änderung der Verordnung über die Zuweisungen an das Sondervermögen ""Versorgungsfonds der Bundes...",2009-01-21T00:00:00Z,2009
21,Dritte Verordnung über die Aufhebung der Anerkennung von Ausbildungsberufen,2009-01-30T00:00:00Z,2009
22,Gesetz zur Neuordnung und Modernisierung des Bundesdienstrechts (Dienstrechtsneuordnungsgesetz  DNeuG),2009-02-11T00:00:00Z,2009
23,Verordnung zur Neuregelung mutterschutz- und elternzeitrechtlicher Vorschriften,2009-02-13T00:00:00Z,2009
24,Gesetz zur Sicherung von Beschäftigung und Stabilität in Deutschland,2009-03-05T00:00:00Z,2009
25,Gesetz zur steuerlichen Förderung der Mitarbeiterkapitalbeteiligung (Mitarbeiterkapitalbeteiligungsgesetz),2009-03-11T00:00:00Z,2009
26,Verordnung zur Bestimmung der zuständigen Behörde nach § 3 Absatz 5 des Arbeitnehmer-Entsendegesetzes (AEntGMeldstellV),2009-03-17T00:00:00Z,2009
27,Bundesgesetzblatt Teil II Nr. 10,2009-04-15T00:00:00Z,2009
28,Gesetz zur Änderung des Einlagensicherungs- und Anlegerentschädigungsgesetzes und anderer Gesetze,2009-06-29T00:00:00Z,2009
29,Vierte Verordnung zur Änderung der Kostenverordnung für Amtshandlungen des Paul-Ehrlich-Instituts nach dem Arzneimit...,2009-07-03T00:00:00Z,2009
30,Gesetz zur Reform des Kontopfändungsschutzes,2009-07-10T00:00:00Z,2009
31,Gesetz zur Änderung des Zugewinnausgleichs- und Vormundschaftsrechts,2009-07-10T00:00:00Z,2009
32,Gesetz zur Änderung arzneimittelrechtlicher und anderer Vorschriften,2009-07-22T00:00:00Z,2009
33,Sechzehnte Verordnung zur Anpassung des Bemessungsbetrages und von Geldleistungen nach dem Bundesversorgungsgesetz (...,2009-07-22T00:00:00Z,2009
34,Siebte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2009-07-24T00:00:00Z,2009
35,Verordnung des Bundes über leistungsbezogene Besoldungsinstrumente (Bundesleistungsbesoldungsverordnung  BLBV),2009-07-27T00:00:00Z,2009
36,Gesetz zur Änderung medizinprodukterechtlicher Vorschriften,2009-07-31T00:00:00Z,2009
37,Erstes Gesetz zur Änderung des Gesetzes zur Regelung der Rechtsverhältnisse der Helfer der Bundesanstalt Technisches...,2009-08-03T00:00:00Z,2009
38,Vierzehnte Verordnung zur Neufestsetzung der Beträge nach § 7 Absatz 1 des Gesetzes zur Hilfe für Frauen bei Schwang...,2009-08-28T00:00:00Z,2009
39,Gesetz zur Änderung des Schwangerschaftskonfliktgesetzes,2009-09-14T00:00:00Z,2009
40,Verordnung zur Bestimmung der zuständigen Behörde nach § 18 Absatz 6 des Arbeitnehmer-Entsendegesetzes (AEntGMeldste...,2009-09-16T00:00:00Z,2009
41,Anlageband:Anlage zur Verordnung über die Raumordnung in der deutschen ausschließlichen Wirtschaftszone in der Nords...,2009-09-25T00:00:00Z,2009
42,Karte zum Anlageband:Anlage zur Verordnung über die Raumordnung in der deutschen ausschließlichen Wirtschaftszone in...,2009-09-25T00:00:00Z,2009
43,Gesetz zur Durchführung gemeinschaftsrechtlicher Vorschriften über das Schulobstprogramm (Schulobstgesetz  SchulObG),2009-09-29T00:00:00Z,2009
44,Verordnung über die Ausbildung und Prüfung für den gehobenen technischen Dienst in der Bundeswehrverwaltung  Fachri...,2009-10-08T00:00:00Z,2009
45,Berichtigung des Gesetzes zur Änderung arzneimittelrechtlicher und anderer Vorschriften,2009-10-14T00:00:00Z,2009
46,Neufassung der Bundesmehrarbeitsvergütungsverordnung,2009-11-11T00:00:00Z,2009
47,Achte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2009-12-23T00:00:00Z,2009
48,Vierundzwanzigste Verordnung zur Änderung betäubungsmittelrechtlicher Vorschriften Vierundzwanzigste Betäubungsmitte...,2009-12-23T00:00:00Z,2009
49,Verordnung zur Übertragung der Befugnis zum Erlass von Rechtsverordnungen nach dem Fünften Buch Sozialgesetzbuch auf...,2010-02-22T00:00:00Z,2010
50,Verordnung zur Ausführung der Verordnung zur Weiterentwicklung des bundesweiten Ausgleichsmechanismus (Ausgleichsmec...,2010-02-26T00:00:00Z,2010
51,Neufassung des Beamtenversorgungsgesetzes,2010-03-03T00:00:00Z,2010
52,Erste Verordnung zur Änderung der Versorgungsmedizin-Verordnung,2010-03-09T00:00:00Z,2010
53,Bekanntmachung nach § 3 Absatz 1 Satz 2 des Gesetzes über die Versorgungsausgleichskasse,2010-04-01T00:00:00Z,2010
54,Neufassung der Kostenverordnung für Amtshandlungen des Paul-Ehrlich-Instituts nach dem Arzneimittelgesetz,2010-04-01T00:00:00Z,2010
55,Verordnung über die Ausbildung und Prüfung für den höheren technischen Dienst in der Bundeswehrverwaltung - Fachrich...,2010-04-09T00:00:00Z,2010
56,Verordnung zur Einrichtung einer Bundesfamilienkasse beim Bundesverwaltungsamt (BVA-Bundesfamilienkassenverordnung ...,2010-06-02T00:00:00Z,2010
57,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Industriefachwirt und Geprüfte Industrie...,2010-06-30T00:00:00Z,2010
58,Zweite Verordnung zur Änderung der Versorgungsmedizin-Verordnung,2010-07-21T00:00:00Z,2010
59,Neunte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2010-07-29T00:00:00Z,2010
60,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Personaldienstleistungsfachwirt und Gepr...,2010-07-29T00:00:00Z,2010
61,Fünfzehnte Verordnung zur Neufestsetzung der Beträge nach § 7 Absatz 1 des Gesetzes zur Hilfe für Frauen bei Schwang...,2010-08-05T00:00:00Z,2010
62,Verordnung zur Erhebung der Daten nach § 51b des Zweiten Buches Sozialgesetzbuch,2010-08-13T00:00:00Z,2010
63,Bundesbesoldungs- und versorgungsanpassungsgesetz 2010/2011 (BBVAnpG 2010/2011),2010-11-24T00:00:00Z,2010
64,Neufassung des Betriebsprämiendurchführungsgesetzes,2010-12-03T00:00:00Z,2010
65,Dritte Verordnung zur Änderung der Versorgungsmedizin-Verordnung,2010-12-22T00:00:00Z,2010
66,Verordnung zur Umsetzung von Konsultationsvereinbarungen zwischen der Bundesrepublik Deutschland und dem Königreich ...,2010-12-22T00:00:00Z,2010
67,Gesetz zur Neuordnung des Arzneimittelmarktes in der gesetzlichen Krankenversicherung (Arzneimittelmarktneuordnungsg...,2010-12-27T00:00:00Z,2010
68,Abschlusshinweis für Bundesgesetzblatt Teil I und Teil II,2010-12-31T00:00:00Z,2010
69,Verordnung über die Nutzenbewertung von Arzneimitteln nach § 35a Absatz 1 SGB V für Erstattungsvereinbarungen nach §...,2010-12-31T00:00:00Z,2010
70,Berichtigung des Bundesbesoldungs- und -versorgungsanpassungsgesetzes 2010/2011,2011-02-10T00:00:00Z,2011
71,Fünfte Verordnung über die Aufhebung der Anerkennung von Ausbildungsberufen,2011-02-25T00:00:00Z,2011
72,Zehnte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2011-02-25T00:00:00Z,2011
73,Fünfte Verordnung zur Änderung der Kostenverordnung für Amtshandlungen des Paul-Ehrlich-Instituts nach dem Arzneimit...,2011-04-11T00:00:00Z,2011
74,Verordnung zur Fortführung der leistungsorientierten Entgeltregelungen für die Beamtinnen und Beamten der Deutschen ...,2011-05-17T00:00:00Z,2011
75,Siebzehnte Verordnung zur Anpassung des Bemessungsbetrages und von Geldleistungen nach dem Bundesversorgungsgesetz (...,2011-06-30T00:00:00Z,2011
76,Gesetz zur Änderung des Vormundschafts- und Betreuungsrechts,2011-07-05T00:00:00Z,2011
77,Elfte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2011-07-25T00:00:00Z,2011
78,Erste Verordnung zur Änderung EU-rechtlicher Verweisungen im Arzneimittelgesetz,2011-07-25T00:00:00Z,2011
79,Vierte Verordnung zur Änderung der Versorgungsmedizin-Verordnung .,2011-11-04T00:00:00Z,2011
80,Gesetz zur Verbesserung der Feststellung und Anerkennung im Ausland erworbener Berufsqualifikationen,2011-12-12T00:00:00Z,2011
81,Neufassung des Europäische Betriebsräte-Gesetzes,2011-12-15T00:00:00Z,2011
82,Gesetz zur Wiedergewährung der Sonderzahlung,2011-12-27T00:00:00Z,2011
83,Gesetz zur Stärkung eines aktiven Schutzes von Kindern und Jugendlichen (Bundeskinderschutzgesetz  BKiSchG),2011-12-28T00:00:00Z,2011
84,Zweite Verordnung zur Änderung der Integrationskursverordnung,2012-02-29T00:00:00Z,2012
85,Hinweis:Bundesgesetzblatt Teil II Nr. 5,2012-03-06T00:00:00Z,2012
86,Verordnung über die Berufsausbildung zum Fachangestellten für Arbeitsmarktdienstleistungen und zur Fachangestellten ...,2012-05-31T00:00:00Z,2012
87,Zwölfte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2012-05-31T00:00:00Z,2012
88,Vierte Verordnung zur Änderung der Apothekenbetriebsordnung,2012-06-11T00:00:00Z,2012
89,Achtzehnte Verordnung zur Anpassung des Bemessungsbetrages und von Geldleistungen nach dem Bundesversorgungsgesetz (...,2012-06-29T00:00:00Z,2012
90,Zweite Verordnung zur Änderung EU-rechtlicher Verweisungen im Arzneimittelgesetz,2012-07-23T00:00:00Z,2012
91,Gesetz zur Begleitung der Reform der Bundeswehr (Bundeswehrreform-Begleitgesetz  BwRefBeglG),2012-07-25T00:00:00Z,2012
92,Bundesbesoldungs- und -versorgungsanpassungsgesetz 2012/2013 (BBVAnpG 2012/2013),2012-08-20T00:00:00Z,2012
93,Fünfte Verordnung zur Änderung der Versorgungsmedizin-Verordnung,2012-10-16T00:00:00Z,2012
94,Verordnung über die Meisterprüfung in den Teilen I und II im Müller-Handwerk (Müllermeisterverordnung  MüMstrV),2012-10-18T00:00:00Z,2012
95,Zweites Gesetz zur Änderung arzneimittelrechtlicher und anderer Vorschriften,2012-10-25T00:00:00Z,2012
96,Verordnung über statistische Erhebungen zu Arbeitsunfällen und arbeitsbedingten Gesundheitsproblemen im Rahmen der A...,2012-10-29T00:00:00Z,2012
97,Verordnung zur Aussetzung und Ergänzung von Merkmalen nach dem Verdienststatistikgesetz (Verdienststatistikverordnun...,2012-11-07T00:00:00Z,2012
98,Gesetz zur Neuordnung der Altersversorgung der Bezirksschornsteinfegermeister und zur Änderung anderer Gesetze,2012-12-13T00:00:00Z,2012
99,Verordnung zur Änderung von Vorschriften über die ärztliche Approbation,2013-01-14T00:00:00Z,2013
100,Gesetz zur Einführung eines Betreuungsgeldes (Betreuungsgeldgesetz),2013-02-20T00:00:00Z,2013
101,Dreizehnte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2013-02-25T00:00:00Z,2013
102,Gesetz zur Stärkung der beruflichen Aus- und Weiterbildung in der Altenpflege,2013-03-18T00:00:00Z,2013
103,Dritte Verordnung zur Änderung EU-rechtlicher Verweisungen im Arzneimittelgesetz,2013-04-08T00:00:00Z,2013
104,Gesetz zur Reform der elterlichen Sorge nicht miteinander verheirateter Eltern,2013-04-19T00:00:00Z,2013
105,Verordnung zur Fortführung der Sonderzahlung für die Beamtinnen und Beamten der Deutschen Post AG,2013-04-19T00:00:00Z,2013
106,Vierte Verordnung zur Änderung der Verordnung zur Errichtung von Sachverständigen-Ausschüssen für Standardzulassunge...,2013-04-19T00:00:00Z,2013
107,Gesetz zur Änderung des Unterhaltsvorschussgesetzes und anderer Gesetze (Unterhaltsvorschussentbürokratisierungsgesetz),2013-05-08T00:00:00Z,2013
108,Gesetz zur Stärkung der Innenentwicklung in den Städten und Gemeinden und weiteren Fortentwicklung des Städtebaurechts,2013-06-20T00:00:00Z,2013
109,Gesetz zur Förderung der Sicherstellung des Notdienstes von Apotheken (Apothekennotdienstsicherstellungsgesetz  ANSG),2013-07-18T00:00:00Z,2013
110,Gesetz zur Änderung des Finanzausgleichsgesetzes und der Bundeshaushaltsordnung,2013-07-18T00:00:00Z,2013
111,Vierte Verordnung zur Änderung EU-rechtlicher Verweisungen im Arzneimittelgesetz,2013-07-18T00:00:00Z,2013
112,Drittes Gesetz zur Änderung arzneimittelrechtlicher und anderer Vorschriften,2013-08-12T00:00:00Z,2013
113,Gesetz zur Strukturreform des Gebührenrechts des Bundes,2013-08-14T00:00:00Z,2013
114,Verordnung zur Festsetzung der der Revision unterliegenden Bundesbeteiligung an den Kosten der Unterkunft und Heizun...,2013-08-21T00:00:00Z,2013
115,Gesetz zum Ausbau der Hilfen für Schwangere und zur Regelung der vertraulichen Geburt,2013-09-03T00:00:00Z,2013
116,Gesetz zur Verwaltungsvereinfachung in der Kinder- und Jugendhilfe (Kinder- und Jugendhilfeverwaltungsvereinfachungs...,2013-09-03T00:00:00Z,2013
117,Zweite Verordnung zur Fortführung der Sonderzahlung für die Beamtinnen und Beamten bei der Deutschen Post AG,2013-09-24T00:00:00Z,2013
118,Berichtigung der Bundesstraßenmaut-Knotenpunkteverordnung,2013-10-08T00:00:00Z,2013
119,"Gesetz zur Neuorganisation der bundesunmittelbaren Unfallkassen, zur Änderung des Sozialgerichtsgesetzes und zur Änd...",2013-10-24T00:00:00Z,2013
120,Verordnung über die Erprobung abweichender Ausbildungs- und Prüfungsbestimmungen in der Büromanagementkaufleute-Ausb...,2013-12-17T00:00:00Z,2013
121,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Handelsfachwirt und Geprüfte Handelsfach...,2014-05-16T00:00:00Z,2014
122,Verordnung zur Umsetzung der Regelungen der Europäischen Union über die Anerkennung von in anderen Mitgliedstaaten a...,2014-06-03T00:00:00Z,2014
123,Verordnung zur Festlegung der der Revision unterliegenden Bundesbeteiligung an den Kosten der Unterkunft und Heizung...,2014-07-18T00:00:00Z,2014
124,Verordnung über die Abgabe von Medizinprodukten und zur Änderung medizinprodukterechtlicher Vorschriften,2014-07-28T00:00:00Z,2014
125,Gesetz zur Stärkung der Tarifautonomie (Tarifautonomiestärkungsgesetz),2014-08-15T00:00:00Z,2014
126,Gesetz zur Einstufung weiterer Staaten als sichere Herkunftsstaaten und zur Erleichterung des Arbeitsmarktzugangs fü...,2014-11-05T00:00:00Z,2014
127,Verordnung zur Änderung der Medizinprodukte-Gebührenverordnung,2014-11-10T00:00:00Z,2014
128,Bundesbesoldungs- und -versorgungsanpassungsgesetz 2014/2015 (BBVAnpG 2014/2015),2014-11-28T00:00:00Z,2014
129,Verordnung zur Bestimmung der zuständigen Behörde nach § 16 Absatz 6 des Mindestlohngesetzes (MiLoGMeldStellV),2014-12-04T00:00:00Z,2014
130,"Verordnung über Meldepflichten nach dem Mindestlohngesetz, dem Arbeitnehmer-Entsendegesetz und dem Arbeitnehmerüberl...",2014-12-04T00:00:00Z,2014
131,"Verordnung zur Änderung der Arzneimittelverschreibungsverordnung, der Apothekenbetriebsordnung, der Verordnung über ...",2014-12-29T00:00:00Z,2014
132,Gesetz zur Änderung der Abgabenordnung und des Einführungsgesetzes zur Abgabenordnung,2014-12-30T00:00:00Z,2014
133,Neufassung des Bundeselterngeld- und Elternzeitgesetzes,2015-01-29T00:00:00Z,2015
134,Verordnung zur Änderung der Arzneimittelverschreibungsverordnung und der Apothekenbetriebsordnung,2015-03-13T00:00:00Z,2015
135,Gebührenverordnung zum Mess- und Eichwesen (Mess- und Eichgebührenverordnung  MessEGebV),2015-03-27T00:00:00Z,2015
136,Verordnung zur Änderung der Verordnung zur Durchführung des Bundesdisziplinargesetzes bei den bundesunmittelbaren Kö...,2015-05-18T00:00:00Z,2015
137,Gesetz zur Tarifeinheit (Tarifeinheitsgesetz),2015-07-09T00:00:00Z,2015
138,Gesetz zur Stärkung der Gesundheitsförderung und der Prävention (Präventionsgesetz  PrävG),2015-07-24T00:00:00Z,2015
139,Verordnung zum Erlass und zur Änderung tierarzneimittelrechtlicher Verordnungen,2015-07-24T00:00:00Z,2015
140,Verordnung zur Festlegung der der Revision unterliegenden Bundesbeteiligung an den Kosten der Unterkunft und Heizung...,2015-07-31T00:00:00Z,2015
141,"Entscheidung des Bundesverfassungsgerichts (zu den §§ 4a bis 4d des Bundeselterngeld- und Elternzeitgesetzes, hier: ...",2015-09-07T00:00:00Z,2015
142,Fünfte Verordnung zur Änderung EU-rechtlicher Verweisungen im Arzneimittelgesetz,2015-09-25T00:00:00Z,2015
143,Berichtigung des Präventionsgesetzes,2015-10-23T00:00:00Z,2015
144,Gesetz zur Änderung des Berufsqualifikationsfeststellungsgesetzes und anderer Gesetze,2015-12-30T00:00:00Z,2015
145,Bekanntmachung nach § 9 Absatz 1 Satz 3 des Unterhaltssicherungsgesetzes,2019-03-28T00:00:00Z,2019
146,Gesetz zur Verbesserung der Information über einen Schwangerschaftsabbruch,2019-03-28T00:00:00Z,2019
147,Siebzehnte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2019-03-28T00:00:00Z,2019
148,Verordnung zur Festsetzung eines vergabespezifischen Mindestentgelts für Aus- und Weiterbildungsdienstleistungen nac...,2019-03-28T00:00:00Z,2019
149,Siebte Verordnung zur Änderung EU-rechtlicher Verweisungen im Arzneimittelgesetz,2019-05-03T00:00:00Z,2019
150,Fünfundzwanzigste Verordnung zur Anpassung des Bemessungsbetrages und von Geldleistungen nach dem Bundesversorgungsg...,2019-06-19T00:00:00Z,2019
151,Gesetz zur Anpassung der Betreuer- und Vormündervergütung,2019-06-27T00:00:00Z,2019
152,Verordnung zur Festlegung und Anpassung der Bundesbeteiligung an den Leistungen für Unterkunft und Heizung für das J...,2019-07-04T00:00:00Z,2019
153,Gesetz zur Entfristung des Integrationsgesetzes,2019-07-11T00:00:00Z,2019
154,Sechsundzwanzigstes Gesetz zur Änderung des Bundesausbildungsförderungsgesetzes (26. BAföGÄndG),2019-07-15T00:00:00Z,2019
155,Zweite Verordnung zur Änderung der Mindestunterhaltsverordnung,2019-09-30T00:00:00Z,2019
156,Verordnung zur Änderung der Apothekenbetriebsordnung und der Arzneimittelpreisverordnung,2019-10-21T00:00:00Z,2019
157,Achtzehnte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2019-10-31T00:00:00Z,2019
158,Gesetz zur Änderung des Gesetzes zur Errichtung der Deutschen Rentenversicherung Bund und der Deutschen Rentenversic...,2019-11-20T00:00:00Z,2019
159,Fünftes Gesetz zur Änderung des Deutschen Richtergesetzes,2019-11-28T00:00:00Z,2019
160,Gesetz zur Reform der Hebammenausbildung und zur Änderung des Fünften Buches Sozialgesetzbuch (Hebammenreformgesetz...,2019-11-28T00:00:00Z,2019
161,Gesetz zur Entlastung unterhaltsverpflichteter Angehöriger in der Sozialhilfe und in der Eingliederungshilfe (Angehö...,2019-12-12T00:00:00Z,2019
162,Neunzehnte Verordnung zur Änderung der Arzneimittelverschreibungsverordnung,2020-02-21T00:00:00Z,2020
163,Gesetz für einen fairen Kassenwettbewerb in der gesetzlichen Krankenversicherung (Fairer-Kassenwettbewerb-Gesetz – G...,2020-03-31T00:00:00Z,2020

### §5a. Decision — System 1 only

Review the table above (the left-most column is the 0-based row index).  
Set `S1_INCLUDED_INDICES` in the cell below to the indices you want to **include**, then run **§8**.  
Leave as `[]` to exclude all System-1-only policies.

In [6]:
# ── DECISION: System 1 only ───────────────────────────────────────────────────
# Row indices (0-based, from the §5 table above) to include in the final set.
# Example: S1_INCLUDED_INDICES = [0, 3, 7]
# Leave as [] to exclude all System-1-only policies.

S1_INCLUDED_INDICES = [0, 5, 7, 11, 13, 14, 15, 23, 24, 25 ,26, 31, 33, 35, 38, 40, 46, 51, 53, 56, 61, 62, 63, 70, 74, 75, 80, 82, 83, 89, 96, 
                       97, 100, 102, 104, 105, 107, 114, 117, 119, 123, 125, 126, 128, 129, 130, 133, 137, 140, 141, 144, 145, 148, 150, 151, 
                       152, 153, 155, 158, 160, 161, 163, 165, 166, 168, 168, 170, 171, 172, 173, 174, 176, 178, 180, 181, 191, 195, 198, 205, 206, 
                       207, 208, 210 , 211]   # ← edit this list

## §6. System 2 only (BERTopic)

Found by BERTopic but not by cosine similarity — likely welfare-policy laws with
unusual vocabulary that did not match the seed descriptions. Inspect topic by topic.

Topic metadata is joined from `_berttopic_topic_assignments.json` since the
candidates file contains only raw documents without topic labels.

In [7]:
title_to_topic = {entry['doc']['title'].strip(): entry['topic_id'] for entry in topic_assign}
topic_to_words = {t['topic_id']: t['top_words'] for t in topic_info}

df_s2 = df_union[df_union['system_sources'] == 's2_only'].copy()
df_s2['berttopic_topic'] = df_s2['title'].str.strip().map(title_to_topic)
print(f'{len(df_s2)} docs found only by BERTopic\n')

for topic_id, group in df_s2.groupby('berttopic_topic'):
    words = topic_to_words.get(topic_id, [])
    top_words_str = ', '.join(words[:6])
    print(f'── topic {int(topic_id)}  (n={len(group)})  top words: {top_words_str}')
    display(group[['title', 'date_published']].reset_index(drop=True))
    print()

502 docs found only by BERTopic

── topic 7  (n=42)  top words: meisterprfung, meisterprfung ii, ii, fortbildungsabschluss, anerkannt fortbildungsabschluss, professional

,title,date_published
0,Verordnung über das Meisterprüfungsberufsbild und über die Prüfungsanforderungen in den Teilen I und II der Meisterp...,2008-03-18T00:00:00Z
1,Verordnung über die Berufsausbildung zum Seiler und zur Seilerin (Seiler-Ausbildungsverordnung -SeilAusbV),2008-05-31T00:00:00Z
2,Verordnung über das Meisterprüfungsberufsbild und über die Prüfungsanforderungen in den Teilen I und II der Meisterp...,2008-06-30T00:00:00Z
3,Verordnung über das Meisterprüfungsberufsbild und über die Prüfungsanforderungen in den Teilen I und II der Meisterp...,2008-06-30T00:00:00Z
4,Verordnung über das Meisterprüfungsberufsbild und über die Prüfungsanforderungen in den Teilen I und II der Meisterp...,2009-03-11T00:00:00Z
5,Verordnung über das Meisterprüfungsberufsbild und über die Prüfungsanforderungen in den Teilen I und II der Meisterp...,2009-09-24T00:00:00Z
6,Verordnung über die Berufsausbildung zum Milchtechnologen/zur Milchtechnologin,2010-04-16T00:00:00Z
7,Verordnung über die Berufsausbildung zum Böttcher und zur Böttcherin (Böttchergewerbe-Ausbildungsverordnung  Böttch...,2010-05-18T00:00:00Z
8,Verordnung über die Berufsausbildung zum Büchsenmacher und zur Büchsenmacherin (Büchsenmacher-Ausbildungsverordnung ...,2010-06-02T00:00:00Z
9,Verordnung über die Meisterprüfung zum anerkannten Fortbildungsabschluss Agrarservicemeister und Agrarservicemeister...,2010-08-23T00:00:00Z
10,Verordnung über die Meisterprüfung zum anerkannten Fortbildungsabschluss Tierwirtschaftsmeister und Tierwirtschaftsm...,2010-08-23T00:00:00Z
11,Verordnung über die Berufsausbildung zum Medientechnologen Druck und zur Medientechnologin Druck (Drucker-Ausbildung...,2011-04-13T00:00:00Z
12,Verordnung über die Berufsausbildung zum Buchbinder und zur Buchbinderin (Buchbinder-Ausbildungsverordnung  BuchbAu...,2011-05-30T00:00:00Z
13,Verordnung über die Meisterprüfung in den Teilen I und II im Schneidwerkzeugmechaniker-Handwerk (Schneidwerkzeugmech...,2011-12-02T00:00:00Z
14,Verordnung über die Berufsausbildung zum Schilder- und Lichtreklame-hersteller und zur Schilder- und Lichtreklameher...,2012-04-05T00:00:00Z
15,Verordnung über die Berufsausbildung zum Schornsteinfeger und zur Schornsteinfegerin (Schornsteinfeger-Ausbildungsve...,2012-07-04T00:00:00Z
16,Verordnung über die Meisterprüfung in den Teilen I und II im Holz- und Bautenschutzgewerbe (Holz- und Bautenschutzme...,2012-09-17T00:00:00Z
17,Verordnung über die Meisterprüfung in den Teilen I und II im Modellbauer-Handwerk (Modellbauermeisterverordnung  Mb...,2013-01-14T00:00:00Z
18,Verordnung über die Meisterprüfung in den Teilen I und II im Behälter- und Apparatebauer-Handwerk (Behälter- und App...,2013-05-14T00:00:00Z
19,Verordnung über die Meisterprüfung in den Teilen I und II im Textilgestalter-Handwerk (Textilgestaltermeisterverordn...,2013-05-14T00:00:00Z
20,Verordnung über die Berufsausbildung zum Klempner und zur Klempnerin (Klempner-Ausbildungsverordnung  KlempnerAusbV),2013-06-26T00:00:00Z
21,Verordnung über die Berufsausbildung zum Polsterer und zur Polsterin (Polstererausbildungsverordnung  PolstAusbV),2014-05-28T00:00:00Z
22,Verordnung über die Meisterprüfung in den Teilen I und II im Galvaniseur-Handwerk (Galvaniseurmeisterverordnung  Ga...,2014-09-25T00:00:00Z
23,Verordnung über die Meisterprüfung in den Teilen I und II im Glaser-Handwerk (Glasermeisterverordnung  GlaserMstrV),2014-12-29T00:00:00Z
24,Verordnung über die Berufsausbildung zum Geigenbauer und zur Geigenbauerin (Geigenbauerausbildungsverordnung  GbAusV),2015-07-22T00:00:00Z
25,Verordnung über die Berufsausbildung zum Kerzenhersteller und Wachsbildner und zur Kerzenherstellerin und Wachsbildn...,2015-07-22T00:00:00Z
26,Verordnung über die Berufsausbildung zum Orgelbauer und zur Orgelbauerin (Orgelbauerausbildungsverordnung  OrgBAusbV),2019-02-15T00:00:00Z
27,Verordnung über die Meisterprüfung in den Teilen I und II im Fotografen-Handwerk (Fotografenmeisterverordnung  Foto...,2019-10-09T00:00:00Z
28,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Meister für Veranstaltungstechnik oder G...,2019-11-20T00:00:00Z
29,Verordnung über die Meisterprüfung in den Teilen I und II im Karosserie- und Fahrzeugbauer-Handwerk (Karosserie- und...,2019-12-20T00:00:00Z
30,Verordnung über die Meisterprüfung in den Teilen I und II im Klavier- und Cembalobauer-Handwerk (Klavier- und Cembal...,2019-12-20T00:00:00Z
31,Verordnung über die Meisterprüfung in den Teilen I und II im Parkettleger-Handwerk (Parkettlegermeisterverordnung – ...,2020-05-28T00:00:00Z
32,Verordnung über die Meisterprüfung in den Teilen I und II im Metallblasinstrumentenmacher-Handwerk (Metallblasinstru...,2020-06-05T00:00:00Z
33,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Kaufmännischer Fachwirt nach der Handwer...,2020-12-21T00:00:00Z
34,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Meister für Veranstaltungstechnik und Ge...,2020-12-21T00:00:00Z
35,Verordnung über die Berufsausbildung zum Brauer und Mälzer und zur Brauerin und Mälzerin (Brauer- und Mälzerausbildu...,2021-06-09T00:00:00Z
36,Verordnung über die Meisterprüfung zum anerkannten Fortbildungsabschluss Milchwirtschaftlicher Labormeister – Bachel...,2021-09-15T00:00:00Z
37,Verordnung über die Meisterprüfung zum anerkannten Fortbildungsabschluss Molkereimeister – Bachelor Professional in ...,2021-09-15T00:00:00Z
38,Verordnung zum Betrieb des Implantateregisters Deutschland (Implantateregister-Betriebsverordnung – IRegBV),2021-09-24T00:00:00Z
39,Verordnung über die Berufsausbildung zum Binnenschiffer und zur Binnenschifferin (Binnenschifferausbildungsverordnun...,2022-03-08T00:00:00Z
40,Verordnung über die Berufsausbildung zum Binnenschifffahrtskapitän und zur Binnenschifffahrtskapitänin (Binnenschiff...,2022-03-08T00:00:00Z
41,Verordnung über die Berufsausbildung zum Koch und zur Köchin (Kochausbildungsverordnung – KochAusbV),2022-03-14T00:00:00Z

── topic 15  (n=61)  top words: nderung steuerlich, steuerlich, prfungsordnung, einkommensteuergesetz, vermgen, verhinderung

,title,date_published
0,Verordnung zur Änderung von Verbrauchsteuerverordnungen sowie der Brennereiordnung,2008-03-31T00:00:00Z
1,Achtes Gesetz zur Änderung des Steuerberatungsgesetzes,2008-04-11T00:00:00Z
2,Gesetz zur Modernisierung und Entbürokratisierung des Steuerverfahrens (Steuerbürokratieabbaugesetz),2008-12-24T00:00:00Z
3,Jahressteuergesetz 2009 (JStG 2009),2008-12-24T00:00:00Z
4,Gesetz zur Reform des Erbschaftsteuer- und Bewertungsrechts (Erbschaftsteuerreformgesetz - ErbStRG),2008-12-31T00:00:00Z
5,Viertes Gesetz zur Änderung von Verbrauchsteuergesetzen,2009-07-21T00:00:00Z
6,Gesetz zur Bekämpfung der Steuerhinterziehung (Steuerhinterziehungsbekämpfungsgesetz),2009-07-31T00:00:00Z
7,Steuerhinterziehungsbekämpfungsverordnung (SteuerHBekV),2009-09-24T00:00:00Z
8,Bekanntmachung über das Inkrafttreten von Teilen des Vierten Gesetzes zur Änderung von Verbrauchsteuergesetzen,2009-10-02T00:00:00Z
9,Fünfte Verordnung zur Änderung von Verbrauchsteuerverordnungen,2009-10-09T00:00:00Z
10,Neufassung des Einkommensteuergesetzes,2009-10-13T00:00:00Z
11,Berichtigung der Bekanntmachung der Neufassung des Einkommensteuergesetzes,2009-12-18T00:00:00Z
12,Gesetz zur Umsetzung steuerlicher EU-Vorgaben sowie zur Änderung steuerlicher Vorschriften,2010-04-14T00:00:00Z
13,Verordnung zur Änderung steuerlicher Verordnungen,2010-11-22T00:00:00Z
14,Jahressteuergesetz 2010 (JStG 2010),2010-12-13T00:00:00Z
15,Verordnung zur Festlegung eines späteren Anwendungszeitpunktes der Verpflichtungen nach § 5b des Einkommensteuergese...,2010-12-22T00:00:00Z
16,Fünftes Gesetz zur Änderung von Verbrauchsteuergesetzen,2010-12-27T00:00:00Z
17,Sechstes Gesetz zur Änderung von Verbrauchsteuergesetzen,2011-06-24T00:00:00Z
18,Sechste Verordnung zur Änderung von Verbrauchsteuerverordnungen,2011-07-05T00:00:00Z
19,Steuervereinfachungsgesetz 2011,2011-11-04T00:00:00Z
20,Zweite Verordnung zur Änderung steuerlicher Verordnungen,2011-12-06T00:00:00Z
21,Drittes Gesetz zur Änderung des Umsatzsteuergesetzes,2011-12-13T00:00:00Z
22,Gesetz zur Umsetzung der Beitreibungsrichtlinie sowie zur Änderung steuerlicher Vorschriften (Beitreibungsrichtlinie...,2011-12-13T00:00:00Z
23,Vierte Verordnung zur Änderung der Ausbildungs- und Prüfungsordnung für die Steuerbeamten,2012-05-21T00:00:00Z
24,Gesetz zum Abkommen vom 19. und 28. Dezember 2011 zwischen dem Deutschen Institut in Taipeh und der Taipeh Vertretun...,2012-10-08T00:00:00Z
25,Bekanntmachung über das Inkrafttreten des Abkommens zwischen dem Deutschen Institut in Taipeh und der Taipeh Vertret...,2012-12-11T00:00:00Z
26,Verordnung zum Erlass und zur Änderung steuerlicher Verordnungen,2012-12-19T00:00:00Z
27,Gesetz zur Änderung und Vereinfachung der Unternehmensbesteuerung und des steuerlichen Reisekostenrechts,2013-02-25T00:00:00Z
28,Elfte Verordnung zur Änderung der Umsatzsteuer-Durchführungsverordnung,2013-03-28T00:00:00Z
29,Verordnung zur Übertragung der Zuständigkeit für das Steuerabzugs- und Veranlagungsverfahren nach den §§ 50 und 50a ...,2013-06-28T00:00:00Z
30,Gesetz zur Änderung des Einkommensteuergesetzes in Umsetzung der Entscheidung des Bundesverfassungsgerichtes vom 7. ...,2013-07-18T00:00:00Z
31,Verordnung zur Änderung steuerlicher Verordnungen und weiterer Vorschriften,2014-12-29T00:00:00Z
32,Steueränderungsgesetz 2015,2015-11-05T00:00:00Z
33,Fünfte Verordnung zur Änderung der Steuerbeamtenausbildungs- und prüfungsordnung,2019-03-08T00:00:00Z
34,Verordnung zur Umsetzung der Notifizierung zur Anwendung der Anrechnungsmethode bei bestimmten Einkünften nach dem d...,2019-03-08T00:00:00Z
35,Gesetz zur Reform des Grundsteuer- und Bewertungsrechts (Grundsteuer-Reformgesetz  GrStRefG),2019-12-02T00:00:00Z
36,Fünfte Verordnung zur Änderung steuerlicher Verordnungen,2020-06-29T00:00:00Z
37,Verordnung zu § 27 Absatz 15 des Umwandlungssteuergesetzes,2020-12-23T00:00:00Z
38,Jahressteuergesetz 2020 (JStG 2020),2020-12-28T00:00:00Z
39,Siebtes Gesetz zur Änderung von Verbrauchsteuergesetzen,2021-04-06T00:00:00Z
40,Gesetz zur Änderung des Grunderwerbsteuergesetzes,2021-05-17T00:00:00Z
41,Gesetz zur Modernisierung der Entlastung von Abzugsteuern und der Bescheinigung der Kapitalertragsteuer (Abzugsteuer...,2021-06-08T00:00:00Z
42,Gesetz zur Abwehr von Steuervermeidung und unfairem Steuerwettbewerb und zur Änderung weiterer Gesetze,2021-06-30T00:00:00Z
43,Gesetz zur Modernisierung des Körperschaftsteuerrechts,2021-06-30T00:00:00Z
44,Gesetz zur Umsetzung der Anti-Steuervermeidungsrichtline (ATAD-Umsetzungsgesetz – ATADUmsG),2021-06-30T00:00:00Z
45,Sechstes Gesetz zur Änderung des Steuerbeamten-Ausbildungsgesetzes,2021-07-14T00:00:00Z
46,Gesetz zur erleichterten Umsetzung der Reform der Grundsteuer und Änderung weiterer steuerrechtlicher Vorschriften (...,2021-07-22T00:00:00Z
47,Siebte Verordnung zur Änderung von Verbrauchsteuerverordnungen,2021-08-20T00:00:00Z
48,Verordnung zur Durchführung des § 3 des Steueroasen-Abwehrgesetzes (Steueroasen-Abwehrverordnung – StAbwV),2021-12-23T00:00:00Z
49,Verordnung zur Umsetzung der Notifizierung über die Anwendung der Anrechnungsmethode bei bestimmten Einkünften nach ...,2021-12-23T00:00:00Z
50,Steuerentlastungsgesetz 2022,2022-05-27T00:00:00Z
51,Vierte Verordnung zur Änderung der Steuerberatervergütungsverordnung,2022-06-17T00:00:00Z
52,Verordnung über die Berufsausbildung zum Steuerfachangestellten und zur Steuerfachangestellten (Steuerfachangestellt...,2022-08-22T00:00:00Z
53,Achtes Gesetz zur Änderung von Verbrauchsteuergesetzen,2022-10-28T00:00:00Z
54,Ausbildungs- und Prüfungsordnung für die Steuerbeamtinnen und Steuerbeamten (Steuerbeamtenausbildungs- und -prüfungs...,2022-11-03T00:00:00Z
55,Berichtigung der Siebten Verordnung zur Änderung von Verbrauchsteuerverordnungen,2022-11-08T00:00:00Z
56,Verordnung über die Steuerberaterplattform und die besonderen elektronischen Steuerberaterpostfächer (Steuerberaterp...,2022-11-30T00:00:00Z
57,Gesetz zum Ausgleich der Inflation durch einen fairen Einkommensteuertarif sowie zur Anpassung weiterer steuerlicher...,2022-12-13T00:00:00Z
58,Jahressteuergesetz 2022 (JStG 2022),2022-12-20T00:00:00Z
59,Verordnung zur Änderung der Steueroasen-Abwehrverordnung,2022-12-21T00:00:00Z
60,Sechste Verordnung zur Änderung steuerlicher Verordnungen,2022-12-22T00:00:00Z

── topic 16  (n=26)  top words: beschftigung, arbeitnehmerentsendegesetz, arbeitszeit, arbeitnehmer, instrument, verbesserung international

,title,date_published
0,Gesetz zur Sicherung von Werkunternehmeransprüchen und zur verbesserten Durchsetzung von Forderungen (Forderungssich...,2008-10-28T00:00:00Z
1,Dritte Verordnung zur Änderung der Winterbeschäftigungs-Verordnung,2008-12-24T00:00:00Z
2,Gesetz zur arbeitsmarktadäquaten Steuerung der Zuwanderung Hochqualifizierter und zur Änderung weiterer aufenthaltsr...,2008-12-24T00:00:00Z
3,Gesetz über zwingende Arbeitsbedingungen für grenzüberschreitend entsandte und für regelmäßig im Inland beschäftigte...,2009-04-23T00:00:00Z
4,Neufassung des Arbeitsplatzschutzgesetzes,2009-07-24T00:00:00Z
5,Verordnung über Meldepflichten nach dem Arbeitnehmer-Entsendegesetz (Arbeitnehmer-Entsendegesetz-Meldeverordnung  A...,2010-10-08T00:00:00Z
6,Dritte Verordnung zur Änderung der Arbeitsgenehmigungsverordnung,2010-11-22T00:00:00Z
7,Verordnung zur Änderung und Aufhebung arbeitsgenehmigungsrechtlicher Vorschriften,2011-12-15T00:00:00Z
8,Berichtigung des Gesetzes zur Unterstützung der Fachkräftegewinnung im Bund und zur Änderung weiterer dienstrechtlic...,2012-07-16T00:00:00Z
9,Gesetz zur Regelung der Arbeitszeit von selbständigen Kraftfahrern,2012-07-16T00:00:00Z
10,Vierte Verordnung zur Änderung der Winterbeschäftigungs-Verordnung,2012-12-11T00:00:00Z
11,Verordnung zur Änderung des Ausländerbeschäftigungsrechts,2013-06-13T00:00:00Z
12,Fünfte Verordnung zur Änderung der Winterbeschäftigungs-Verordnung,2013-06-28T00:00:00Z
13,Verordnung über eine statistische Erhebung zur Arbeitsmarktsituation von Zuwanderern sowie ihren Nachkommen für das ...,2013-08-17T00:00:00Z
14,Gesetz zur Verbesserung der Rechte von international Schutzberechtigten und ausländischen Arbeitnehmern,2013-09-05T00:00:00Z
15,Berichtigung des Gesetzes zur Verbesserung der Rechte von international Schutzberechtigten und ausländischen Arbeitn...,2013-10-30T00:00:00Z
16,Erste Verordnung zur Änderung der Beschäftigungsverordnung,2013-11-06T00:00:00Z
17,Zweite Verordnung zur Änderung der Beschäftigungsverordnung,2014-11-10T00:00:00Z
18,Fachkräfteeinwanderungsgesetz,2019-08-20T00:00:00Z
19,"Gesetz zur Einführung einer Nachunternehmerhaftung in der Kurier-, Express- und Paketbranche zum Schutz der Beschäft...",2019-11-22T00:00:00Z
20,Fünfte Verordnung zur Änderung der Beschäftigungsverordnung,2019-12-02T00:00:00Z
21,Verordnung zur Änderung der Beschäftigungsverordnung und der Aufenthaltsverordnung,2020-03-31T00:00:00Z
22,Zweite Verordnung zur Änderung der Beschäftigungsverordnung und der Aufenthaltsverordnung,2020-12-23T00:00:00Z
23,Sechste Verordnung zur Änderung der Winterbeschäftigungs-Verordnung (Sechste Winterbeschäftigungs-Änderungs-Verordnu...,2021-05-07T00:00:00Z
24,Siebte Verordnung zur Änderung der Beschäftigungsverordnung,2021-06-04T00:00:00Z
25,Berichtigung der Sechsten Winterbeschäftigungs-Änderungs-Verordnung,2021-06-10T00:00:00Z

── topic 17  (n=57)  top words: berufsausbildung, nderung berufsausbildung, technischen, berufsausbildung technischen, technisch, entwicklung erprobung

,title,date_published
0,Verordnung über die Berufsausbildung zum Produktionstechnologen/zur Produktionstechnologin,2008-06-25T00:00:00Z
1,Verordnung über die Berufsausbildung zum Elektroniker für Maschinen und Antriebstechnik und zur Elektronikerin für M...,2008-07-30T00:00:00Z
2,Verordnung über die Berufsausbildung zum Elektroniker und zur Elektronikerin,2008-07-30T00:00:00Z
3,Verordnung über die Berufsausbildung zum Feinwerkmechaniker und zur Feinwerkmechanikerin,2008-07-30T00:00:00Z
4,Verordnung über die Berufsausbildung zum Mechaniker für Karosserieinstandhaltungstechnik und zur Mechanikerin für Ka...,2008-07-30T00:00:00Z
5,Verordnung über die Berufsausbildung zum Metallbauer und zur Metallbauerin,2008-07-30T00:00:00Z
6,Verordnung über die Berufsausbildung zum Systemelektroniker und zur Systemelektronikerin,2008-07-30T00:00:00Z
7,Verordnung über die Berufsausbildung zum Karosserie- und Fahrzeugbaumechaniker und zur Karosserie- und Fahrzeugbaume...,2008-07-31T00:00:00Z
8,Verordnung über die Berufsausbildung zum Mechaniker und zur Mechanikerin für Land- und Baumaschinentechnik,2008-07-31T00:00:00Z
9,Verordnung über die Berufsausbildung zum Zweiradmechaniker und zur Zweiradmechanikerin,2008-07-31T00:00:00Z
10,Zweite Verordnung zur Änderung der Verordnung über die Berufsausbildung in der Bauwirtschaft,2009-02-27T00:00:00Z
11,Verordnung über die Berufsausbildung zum Industrieelektriker/zur Industrieelektrikerin,2009-06-04T00:00:00Z
12,Verordnung über die Berufsausbildung zum Keramiker und zur Keramikerin (Keramikgewerbe-Ausbildungsverordnung  KerAu...,2009-06-04T00:00:00Z
13,Verordnung über die Berufsausbildung zum Bergbautechnologen/zur Bergbautechnologin,2009-06-17T00:00:00Z
14,Erste Verordnung zur Änderung der Verordnung über die Entwicklung und Erprobung des Ausbildungsberufes Kraftfahrzeug...,2009-07-02T00:00:00Z
15,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Prozessmanager Elektrotechnik/Geprüfte P...,2009-08-19T00:00:00Z
16,Berichtigung der Verordnung über die Berufsausbildung zum Technischen Modellbauer/zur Technischen Modellbauerin,2009-08-25T00:00:00Z
17,Berichtigung der Verordnung über die Berufsausbildung zum Produktionstechnologen/zur Produktionstechnologin,2009-12-10T00:00:00Z
18,Verordnung über die Berufsausbildung zum Technischen Konfektionär/zur Technischen Konfektionärin,2010-05-18T00:00:00Z
19,Verordnung über die Berufsausbildung zum Feinwerkmechaniker und zur Feinwerkmechanikerin (FeinwAusbV),2010-07-14T00:00:00Z
20,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Papiertechnologen/zur Papiertechnologin,2010-10-27T00:00:00Z
21,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Keramiker/zur Keramikerin,2010-11-22T00:00:00Z
22,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Schuhfertiger/zur Schuhfertigerin,2011-02-25T00:00:00Z
23,Verordnung über die Berufsausbildung zur Fachkraft für Lederverarbeitung,2011-02-25T00:00:00Z
24,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung in den industriellen Metallberufen,2011-03-08T00:00:00Z
25,Berichtigung der Ersten Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Keramiker/zur Keramikerin,2011-03-11T00:00:00Z
26,"Verordnung über die Berufsausbildung zur Fachkraft für Möbel-, Küchen- und Umzugsservice",2011-04-11T00:00:00Z
27,Verordnung über die Berufsausbildung zum Textilgestalter und zur Textilgestalterin im Handwerk,2011-06-27T00:00:00Z
28,Verordnung über die Berufsausbildung zum Technischen Produktdesigner und zur Technischen Produktdesignerin sowie zum...,2011-06-28T00:00:00Z
29,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Textilgestalter und zur Textilgestalterin...,2011-07-29T00:00:00Z
30,Verordnung über die Berufsausbildung zum Mechatroniker und zur Mechatronikerin (Mechatroniker-Ausbildungsverordnung ...,2011-07-29T00:00:00Z
31,Berichtigung der Mechatroniker-Ausbildungsverordnung,2011-09-21T00:00:00Z
32,Verordnung zur Änderung von Verordnungen über die Meisterprüfung im Handwerk und in handwerksähnlichen Gewerben,2011-11-24T00:00:00Z
33,Verordnung über die Berufsausbildung zum Verfahrensmechaniker für Kunststoff- und Kautschuktechnik und zur Verfahren...,2012-05-31T00:00:00Z
34,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung in den industriellen Elektroberufen,2013-02-25T00:00:00Z
35,Erste Verordnung zur Änderung der Verordnung über die Entwicklung und Erprobung der Berufsausbildung in der Automate...,2013-04-08T00:00:00Z
36,Verordnung über die Berufsausbildung zum Fertigungsmechaniker und zur Fertigungsmechanikerin,2013-04-08T00:00:00Z
37,Verordnung über die Berufsausbildung zum Stanz- und Umformmechaniker und zur Stanz- und Umformmechanikerin,2013-04-08T00:00:00Z
38,Verordnung über die Berufsausbildung zur Fachkraft für Metalltechnik,2013-04-08T00:00:00Z
39,Verordnung über die Berufsausbildung zum Kraftfahrzeugmechatroniker und zur Kraftfahrzeugmechatronikerin,2013-06-20T00:00:00Z
40,Verordnung über die Berufsausbildung zum Fluggerätelektroniker und zu den Elektroberufen in der Industrie,2013-07-12T00:00:00Z
41,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Berg- und Maschinenmann,2013-08-02T00:00:00Z
42,Verordnung über die Berufsausbildung zum Zweiradmechatroniker und zur Zweiradmechatronikerin (Zweiradmechatronikerau...,2014-06-20T00:00:00Z
43,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Mechaniker und zur Mechanikerin für Land-...,2014-06-26T00:00:00Z
44,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Technischen Produktdesigner und zur Techn...,2014-10-29T00:00:00Z
45,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Bergbautechnologen/zur Bergbautechnologin,2015-05-18T00:00:00Z
46,Verordnung über die Berufsausbildung zum Holzmechaniker und zur Holzmechanikerin (Holzmechanikerausbildungsverordnun...,2015-05-26T00:00:00Z
47,Verordnung über die Berufsausbildung zum Textil- und Modenäher und zur Textil- und Modenäherin (Textil- und Modenähe...,2015-07-02T00:00:00Z
48,Verordnung über die Berufsausbildung zum Textil- und Modeschneider und zur Textil- und Modeschneiderin (Textil- und ...,2015-07-02T00:00:00Z
49,Verordnung über die Berufsausbildung zum Gießereimechaniker und zur Änderung der Verordnung über die Berufsausbildun...,2015-07-09T00:00:00Z
50,Erste Verordnung zur Änderung der Werksteinherstellerausbildungsverordnung,2015-12-02T00:00:00Z
51,Verordnung über die Berufsausbildung zum Gebäudereiniger und zur Gebäudereinigerin (Gebäudereinigerausbildungsverord...,2019-07-04T00:00:00Z
52,Zweite Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Papiertechnologen/zur Papiertechnologin,2019-07-11T00:00:00Z
53,Verordnung über die Berufsausbildung zum IT-System-Elektroniker und zur IT-System-Elektronikerin (IT-System-Elektron...,2020-03-05T00:00:00Z
54,Verordnung über die Berufsausbildung zum Fahrzeuginterieur-Mechaniker und zur Fahrzeuginterieur-Mechanikerin (Fahrze...,2020-10-19T00:00:00Z
55,Erste Verordnung zur Änderung der Textil- und Modenäherausbildungsverordnung,2021-01-20T00:00:00Z
56,Verordnung zur Neuordnung der Ausbildung in handwerklichen Elektroberufen,2021-04-09T00:00:00Z

── topic 18  (n=50)  top words: entscheidung bundesverfassungsgericht, entscheidung, bundesverfassungsgericht, verbindung, buch, buch sozialgesetzbuch

,title,date_published
0,Entscheidung des Bundesverfassungsgerichts (zu § 44b des Zweiten Buches Sozialgesetzbuch),2008-01-21T00:00:00Z
1,Entscheidung des Bundesverfassungsgerichts (zu § 33 Abs. 1 Satz 1 und Abs. 3 des Gesetzes über die Angelegenheiten d...,2008-04-30T00:00:00Z
2,Entscheidung des Bundesverfassungsgerichts (zu § 7 Abs. 3 Satz 2 i. V. m. § 6 Abs. 4 und 5 des Bundeswahlgesetzes),2008-07-18T00:00:00Z
3,Entscheidung des Bundesverfassungsgerichts (zu § 85 Abs. 4 Satz 2 des Beamtenversorgungsgesetzes),2008-07-25T00:00:00Z
4,Entscheidung des Bundesverfassungsgerichts (zu § 8 Abs. 1 Nr. 2 des Transsexuellengesetzes),2008-08-08T00:00:00Z
5,Entscheidung des Bundesverfassungsgerichts (zu § 2 Abs. 2 des Beratungshilfegesetzes),2008-11-13T00:00:00Z
6,Entscheidung des Bundesverfassungsgerichts (zu § 237 Absatz 4 Satz 1 Nummer 3 sowie § 237 Absatz 3 in Verbindung mit...,2008-12-23T00:00:00Z
7,"Entscheidung des Bundesverfassungsgerichts (zu den §§ 2, 4 Absatz 1 mit Anlage 1, § 5 Absatz 1 und § 6 Absatz 1 mit ...",2009-01-23T00:00:00Z
8,"Entscheidung des Bundesverfassungsgerichts (zu § 2 Absatz 1 bis 4 Satz 1 und Absatz 6, § 10 Absatz 1 bis 8, § 11 und...",2009-02-18T00:00:00Z
9,Entscheidung des Bundesverfassungsgerichts,2009-05-28T00:00:00Z
10,Entscheidung des Bundesverfassungsgerichts (zum Forstabsatzfondsgesetz bzw. Holzabsatzfondsgesetz),2009-06-19T00:00:00Z
11,Entscheidung des Bundesverfassungsgerichts (zu § 12 Absatz 1b Satz 1 des Gesetzes über die Beaufsichtigung der Versi...,2009-07-24T00:00:00Z
12,Entscheidung des Bundesverfassungsgerichts (zu § 45a Absatz 2 Satz 3 Variante 1 des Personenbeförderungsgesetzes),2010-02-17T00:00:00Z
13,Entscheidung des Bundesverfassungsgerichts (zu den §§ 20 und 28 des Zweiten Buches Sozialgesetzbuch sowie den Bekann...,2010-03-03T00:00:00Z
14,Entscheidung des Bundesverfassungsgerichts (zu § 6 Absatz 2 Nummer 4 des Anspruchs- und Anwartschaftsüberführungsges...,2010-08-13T00:00:00Z
15,Entscheidung des Bundesverfassungsgerichts (zu § 1626a Absatz 1 Nummer 1 und § 1672 Absatz 1 des Bürgerlichen Gesetz...,2010-08-17T00:00:00Z
16,"Entscheidung des Bundesverfassungsgerichts (zu Artikel 15 Absatz 3 des RV-Nachhaltigkeitsgesetzes, hier: § 22b des F...",2010-10-08T00:00:00Z
17,"Entscheidung des Bundesverfassungsgerichts (zu § 3 Nummer 3 und 6, § 16a Absatz 1 bis 5, § 16b Absatz 1 bis 4 und § ...",2010-12-13T00:00:00Z
18,Entscheidung des Bundesverfassungsgerichts (zu § 8 Absatz 1 Nummer 3 und 4 des Transsexuellengesetzes),2011-02-10T00:00:00Z
19,"Entscheidung des Bundesverfassungsgerichts (zu den §§ 66, 66a, 66b und § 67d in Verbindung mit § 2 des Strafgesetzbu...",2011-06-08T00:00:00Z
20,Entscheidung des Bundesverfassungsgerichts (zu § 18b Absatz 3 Satz 1 des Bundesausbildungsförderungsgesetzes),2011-08-19T00:00:00Z
21,Entscheidung des Bundesverfassungsgerichts (zu § 10 Absatz 1 des Postpersonalrechtsgesetzes),2012-04-05T00:00:00Z
22,Entscheidung des Bundesverfassungsgerichts (zu § 67 Absatz 4 des Strafgesetzbuches),2012-05-09T00:00:00Z
23,Entscheidung des Bundesverfassungsgerichts (zu Artikel 17 Absatz 1 des Dienstrechtsneuordnungsgesetzes),2012-06-22T00:00:00Z
24,Entscheidung des Bundesverfassungsgerichts (zu § 3 Absatz 2 Satz 2 Nummer 1 und § 3 Absatz 2 Satz 3 in Verbindung mi...,2012-08-20T00:00:00Z
25,Entscheidung des Bundesverfassungsgerichts (zu § 12 Absatz 2 Satz 1 des Bundeswahlgesetzes),2012-08-23T00:00:00Z
26,Entscheidung des Bundesverfassungsgerichts (zu § 40 Absatz 1 Nummer 1 des Bundesbesoldungsgesetzes),2012-08-23T00:00:00Z
27,Entscheidung des Bundesverfassungsgerichts (zu § 6 Absatz 1 Satz 1 und Absatz 2a sowie § 6 Absatz 5 des Bundeswahlge...,2012-08-23T00:00:00Z
28,"Entscheidung des Bundesverfassungsgerichts (zu § 13 Absatz 3 Satz 2 und 3, den §§ 13 bis 15 und § 16 Absatz 2 und 3 ...",2013-05-08T00:00:00Z
29,Entscheidung des Bundesverfassungsgerichts (zum Antiterrordateigesetz),2013-05-17T00:00:00Z
30,Entscheidung des Bundesverfassungsgerichts (zu § 1600 Absatz 1 Nummer 5 des Bürgerlichen Gesetzbuchs und Artikel 229...,2014-02-19T00:00:00Z
31,Entscheidung des Bundesverfassungsgerichts (zu § 59e Absatz 2 Satz 1 und § 59f Absatz 1 der Bundesrechtsanwaltsordnu...,2014-02-19T00:00:00Z
32,Entscheidung des Bundesverfassungsgerichts (zu § 32 des Gesetzes über den Versorgungsausgleich),2014-07-10T00:00:00Z
33,"Entscheidung des Bundesverfassungsgerichts (zu § 1, § 2 Nummern 4 und 5, § 4, § 5 Nummern 2, 4c und 5, §§ 10 und 11 ...",2014-11-25T00:00:00Z
34,Bekanntmachung der Geschäftsordnung des Bundesverfassungsgerichts,2015-03-13T00:00:00Z
35,Entscheidung des Bundesverfassungsgerichts (zu § 13 Nummer 2 und 3 des Bundeswahlgesetzes),2019-03-28T00:00:00Z
36,Entscheidung des Bundesverfassungsgerichts (zu § 1754 Absatz 1 und 2 und § 1755 Absatz 1 Satz 1 und Absatz 2 des Bür...,2019-05-24T00:00:00Z
37,Entscheidung des Bundesverfassungsgerichts (zu § 31a in Verbindung mit den §§ 31 und 31b des Zweiten Buches Sozialge...,2019-12-11T00:00:00Z
38,Entscheidung des Bundesverfassungsgerichts (zu § 217 des Strafgesetzbuches),2020-03-19T00:00:00Z
39,Entscheidung des Bundesverfassungsgerichts (zu Artikel 1 Absatz 1 Satz 1 des Gesetzes zu dem Übereinkommen vom 19. F...,2020-04-30T00:00:00Z
40,"Entscheidung des Bundesverfassungsgerichts (zu § 58 Absatz 3 Nummer 2 und § 62 Absatz 1 Nummer 1 des Lebensmittel-, ...",2020-05-22T00:00:00Z
41,"Entscheidung des Bundesverfassungsgerichts (zu den §§ 6, 7, 13 bis 15, 19 Absatz 1, § 24 Absatz 1 Satz 1, Absatz 2 S...",2020-06-23T00:00:00Z
42,Entscheidung des Bundesverfassungsgerichts (zu § 17 des Gesetzes über den Versorgungsausgleich),2020-06-29T00:00:00Z
43,Entscheidung des Bundesverfassungsgerichts (zu § 6a Absatz 2 Satz 1 des Antiterrordateigesetzes),2021-02-17T00:00:00Z
44,Entscheidung des Bundesverfassungsgerichts (zu Artikel 316h Satz 1 des Einführungsgesetzes zum Strafgesetzbuch),2021-05-21T00:00:00Z
45,Entscheidung des Bundesverfassungsgerichts (zu § 233a in Verbindung mit § 238 Absatz 1 Satz 1 der Abgabenordnung),2021-09-21T00:00:00Z
46,Entscheidung des Bundesverfassungsgerichts (zu § 315d Absatz 1 Nummer 3 des Strafgesetzbuches),2022-03-18T00:00:00Z
47,Entscheidung des Bundesverfassungsgerichts (zu § 12 Absatz 3 Satz 1 Nummer 4 i. V. m. Satz 2 des Zweiten Buches Sozi...,2022-06-30T00:00:00Z
48,Entscheidung des Bundesverfassungsgerichts (zu § 20 Absatz 1 Satz 1 und 2 und § 21 Absatz 1 Satz 1 in Verbindung mit...,2022-11-28T00:00:00Z
49,Entscheidung des Bundesverfassungsgerichts (zu § 2 Absatz 1 Satz 4 Nummer 1 des Asylbewerberleistungsgesetzes),2022-12-20T00:00:00Z

── topic 20  (n=15)  top words: nderung sozialversicherungsentgeltverordnung, sozialversicherungsentgeltverordnung, sozialversicherung, beitragssatz gesetzlich, gesetzlich rentenversicherung, gesetzlich

,title,date_published
0,Dritte Verordnung zur Änderung der Altersvorsorge-Durchführungsverordnung,2009-01-15T00:00:00Z
1,Gesetz zur Stabilisierung der Finanzlage der Sozialversicherungssysteme und zur Einführung eines Sonderprogramms mit...,2010-04-16T00:00:00Z
2,Erste Verordnung zur Änderung der Pensionsfondsberichterstattungsverordnung,2010-05-03T00:00:00Z
3,Vierte Verordnung zur Änderung der Sozialversicherungs-Rechnungsverordnung,2010-12-13T00:00:00Z
4,Erste Verordnung zur Änderung der Pensionsfonds-Kapitalanlagenverordnung,2011-05-11T00:00:00Z
5,Erste Verordnung zur Änderung der Pensionsfonds-Aktuarverordnung,2011-10-28T00:00:00Z
6,Zweite Verordnung zur Änderung der Pensionsfondsberichterstattungsverordnung,2011-12-30T00:00:00Z
7,Verordnung über die Prüfung zum anerkannten Fortbildungsabschluss Geprüfter Sozialversicherungsfachwirt  Fachrichtu...,2013-02-18T00:00:00Z
8,Sechste Verordnung zur Änderung der Sozialversicherungsentgeltverordnung,2013-10-30T00:00:00Z
9,Dritte Verordnung zur Änderung der Pensionsfondsberichterstattungsverordnung,2013-12-23T00:00:00Z
10,Gesetz über Leistungsverbesserungen in der gesetzlichen Rentenversicherung (RV-Leistungsverbesserungsgesetz),2014-06-26T00:00:00Z
11,Gesetz zur Verbesserung der Transparenz in der Alterssicherung und der Rehabilitation sowie zur Modernisierung der S...,2021-02-17T00:00:00Z
12,Gesetz zur Koordinierung der sozialen Sicherheit mit dem Vereinigten Königreich Großbritannien und Nordirland (SozSi...,2021-04-09T00:00:00Z
13,Verordnung über das Steuerungsgremium bei der Zentralen Stelle für die Digitale Rentenübersicht,2021-06-22T00:00:00Z
14,Berichtigung des Gesetzes Digitale Rentenübersicht,2022-01-27T00:00:00Z

── topic 38  (n=2)  top words: bundesanzeiger, verkndunge, hinweis verkndunge, hinweis, sgb, neufassung buch

,title,date_published
0,Erlass über die Genehmigung einer Änderung des Erlasses über die Stiftung und Verleihung der Goethe-Medaille,2009-03-20T00:00:00Z
1,Erlass über die Stiftung des Silbernen Lorbeerblattes,2013-05-27T00:00:00Z

── topic 39  (n=8)  top words: kind, familie, ausbau, bundeselterngeld, elternzeitgesetz, bundeselterngeld elternzeitgesetz

,title,date_published
0,Gesetz zur Förderung von Jugendfreiwilligendiensten,2008-05-26T00:00:00Z
1,Zehntes Gesetz zur Änderung des Bundes-Immissionsschutzgesetzes  Privilegierung des von Kindertageseinrichtungen un...,2011-07-27T00:00:00Z
2,Verordnung über einen Vorschuss für Beamtinnen und Beamte bei Inanspruchnahme von Familienpflegezeit (Beamten-Pflege...,2013-07-26T00:00:00Z
3,"Gesetz zur Verbesserung der Unterbringung, Versorgung und Betreuung ausländischer Kinder und Jugendlicher",2015-10-30T00:00:00Z
4,Bekanntmachung über das Inkrafttreten der Artikel 3 und 4 des Gesetzes zur Weiterentwicklung der Qualität und zur Te...,2019-12-02T00:00:00Z
5,Gesetz zur Digitalisierung von Verwaltungsverfahren bei der Gewährung von Familienleistungen,2020-12-09T00:00:00Z
6,Gesetz zur Verbesserung der Hilfen für Familien bei Adoption (Adoptionshilfe-Gesetz),2021-02-18T00:00:00Z
7,Gesetz zur Stärkung von Kindern und Jugendlichen (Kinder- und Jugendstärkungsgesetz – KJSG),2021-06-09T00:00:00Z

── topic 42  (n=26)  top words: nderung buch, sozialgesetzbuch nderung, buch, buch sozialgesetzbuch, sozialgesetzbuch, zwlft buch

,title,date_published
0,Siebtes Gesetz zur Änderung des Dritten Buches Sozialgesetzbuch und anderer Gesetze,2008-04-11T00:00:00Z
1,Viertes Gesetz zur Änderung des Zweiten Buches Sozialgesetzbuch,2008-07-31T00:00:00Z
2,Achtes Gesetz zur Änderung des Dritten Buches Sozialgesetzbuch und anderer Gesetze,2008-12-24T00:00:00Z
3,Fünftes Gesetz zur Änderung des Zweiten Buches Sozialgesetzbuch,2008-12-24T00:00:00Z
4,Zweites Gesetz zur Änderung des Vierten Buches Sozialgesetzbuch und anderer Gesetze,2008-12-29T00:00:00Z
5,Drittes Gesetz zur Änderung des Vierten Buches Sozialgesetzbuch und anderer Gesetze,2010-08-10T00:00:00Z
6,Sechstes Gesetz zur Änderung des Zweiten Buches Sozialgesetzbuch,2010-12-14T00:00:00Z
7,Berichtigung der Bekanntmachung der Neufassung des Vierten Buches Sozialgesetzbuch,2011-03-11T00:00:00Z
8,Gesetz zur Ermittlung von Regelbedarfen und zur Änderung des Zweiten und Zwölften Buches Sozialgesetzbuch,2011-03-29T00:00:00Z
9,Siebtes Gesetz zur Änderung des Zweiten Buches Sozialgesetzbuch,2011-03-29T00:00:00Z
10,Berichtigung der Bekanntmachung der Neufassung des Zweiten Buches Sozialgesetzbuch,2011-10-26T00:00:00Z
11,Viertes Gesetz zur Änderung des Vierten Buches Sozialgesetzbuch und anderer Gesetze,2011-12-29T00:00:00Z
12,Berichtigung des Vierten Gesetzes zur Änderung des Vierten Buches Sozialgesetzbuch und anderer Gesetze,2012-04-27T00:00:00Z
13,Zweites Gesetz zur Änderung des Siebten Buches Sozialgesetzbuch,2012-12-11T00:00:00Z
14,Gesetz zur Änderung des Neunten Buches Sozialgesetzbuch,2012-12-13T00:00:00Z
15,Gesetz zur Änderung des Zwölften Buches Sozialgesetzbuch,2012-12-27T00:00:00Z
16,Gesetz zur Änderung des Zweiten Buches Sozialgesetzbuch und anderer Gesetze,2013-05-14T00:00:00Z
17,Zweites Gesetz zur Änderung des Zwölften Buches Sozialgesetzbuch,2013-10-08T00:00:00Z
18,Achtes Gesetz zur Änderung des Zweiten Buches Sozialgesetzbuch  Ergänzung personalrechtlicher Bestimmungen,2014-08-04T00:00:00Z
19,Fünftes Gesetz zur Änderung des Vierten Buches Sozialgesetzbuch und anderer Gesetze (5. SGB IV-ÄndG),2015-04-21T00:00:00Z
20,Berichtigung des Fünften Gesetzes zur Änderung des Vierten Buches Sozialgesetzbuch und anderer Gesetze,2015-06-29T00:00:00Z
21,Siebtes Besoldungsänderungsgesetz (7. BesÄndG),2015-12-09T00:00:00Z
22,Gesetz zur Änderung des Neunten und des Zwölften Buches Sozialgesetzbuch und anderer Rechtsvorschriften,2019-12-05T00:00:00Z
23,Siebtes Gesetz zur Änderung des Vierten Buches Sozialgesetzbuch und anderer Gesetze,2020-06-23T00:00:00Z
24,Zweite Verordnung zur Neufestsetzung der Neurenten-Faktoren nach § 178 Absatz 1 des Siebten Buches Sozialgesetzbuch,2020-12-21T00:00:00Z
25,Elftes Gesetz zur Änderung des Zweiten Buches Sozialgesetzbuch,2022-06-22T00:00:00Z

── topic 43  (n=20)  top words: versicherung, krankenkasse, pensionsfonds, informationspflicht, versicherungsunternehmen, unfallversicherung

,title,date_published
0,Verordnung zur Bildung von Altersrückstellungen durch die gesetzlichen Unfallversicherungsträger (Unfallversicherung...,2009-10-02T00:00:00Z
1,Verordnung zur Änderung der Versicherungsunternehmens-Rechnungslegungsverordnung sowie zur Änderung weiterer Rechnun...,2009-12-23T00:00:00Z
2,Verordnung zur Aufteilung und Geltendmachung der Haftungsbeträge durch den Spitzenverband Bund der Krankenkassen bei...,2010-01-13T00:00:00Z
3,Gesetz über die aufsichtsrechtlichen Anforderungen an die Vergütungssysteme von Instituten und Versicherungsunternehmen,2010-07-26T00:00:00Z
4,Verordnung über die aufsichtsrechtlichen Anforderungen an Vergütungssysteme im Versicherungsbereich (Versicherungs-V...,2010-10-12T00:00:00Z
5,Verordnung zur Anpassung der Mindestversicherungssummen und zur Änderung der Kraftfahrzeug-Pflichtversicherungsveror...,2011-12-13T00:00:00Z
6,Zweite Verordnung zur Änderung der Versicherungsberichterstattungs-Verordnung,2011-12-30T00:00:00Z
7,Dritte Verordnung zur Änderung der Versicherungsberichterstattungs-Verordnung,2013-12-23T00:00:00Z
8,Erste Verordnung zur Änderung der Verordnung über die Berufsausbildung zum Kaufmann für Versicherungen und Finanzen/...,2014-06-13T00:00:00Z
9,Verordnung zum Produktinformationsblatt und zu weiteren Informationspflichten bei zertifizierten Altersvorsorge- und...,2015-07-31T00:00:00Z
10,Verordnung zur Aufhebung von Verordnungen nach dem Versicherungsaufsichtsgesetz,2015-12-23T00:00:00Z
11,Berichtigung der Verordnung zur Umsetzung der Richtlinie (EU) 2016/97 des Europäischen Parlaments und des Rates vom ...,2019-04-03T00:00:00Z
12,"Verordnung über Informationspflichten in der betrieblichen Altersversorgung, die von Pensionsfonds, Pensionskassen u...",2019-06-27T00:00:00Z
13,Vierte Verordnung zur Änderung von Verordnungen nach dem Versicherungsaufsichtsgesetz,2020-07-16T00:00:00Z
14,Fünfte Verordnung zur Änderung von Verordnungen nach dem Versicherungsaufsichtsgesetz,2021-04-27T00:00:00Z
15,Gesetz über die Insolvenzsicherung durch Reisesicherungsfonds und zur Änderung reiserechtlicher Vorschriften,2021-06-30T00:00:00Z
16,Bekanntmachung nach Artikel 5 Absatz 2 Satz 2 des Gesetzes über die Insolvenzsicherung durch Reisesicherungsfonds un...,2021-07-27T00:00:00Z
17,Verordnung über die Ausstellung von Pflichtversicherungsbescheinigungen nach dem HNS-Gesetz (HNS-Pflichtversicherung...,2021-09-17T00:00:00Z
18,Verordnung über die Erhebung eines Entgelts für die staatliche Absicherung nach dem Reisesicherungsfondsgesetz,2021-11-30T00:00:00Z
19,Verordnung über die Anzeigen von Versicherungsunternehmen und Pensionsfonds zur Ausgliederung von Funktionen und Ver...,2022-11-28T00:00:00Z

── topic 44  (n=29)  top words: covid19pandemie, sicherung, anlass covid19pandemie, anlass, folge, heimat

,title,date_published
0,Gesetz zur Verbesserung der Absicherung von Zivilpersonal in internationalen Einsätzen zur zivilen Krisenprävention,2009-07-22T00:00:00Z
1,Gesetz zum Ausgleich COVID-19 bedingter finanzieller Belastungen der Krankenhäuser und weiterer Gesundheitseinrichtu...,2020-03-27T00:00:00Z
2,"Gesetz zur Abmilderung der Folgen der COVID-19-Pandemie im Zivil-, Insolvenz- und Strafverfahrensrecht",2020-03-27T00:00:00Z
3,Gesetz zur Abmilderung der Folgen der COVID-19-Pandemie im Veranstaltungsvertragsrecht und im Recht der Europäischen...,2020-05-19T00:00:00Z
4,Gesetz zur Abmilderung der Folgen der COVID-19-Pandemie im Wettbewerbsrecht und für den Bereich der Selbstverwaltung...,2020-05-28T00:00:00Z
5,Gesetz zur Sicherstellung ordnungsgemäßer Planungs- und Genehmigungsverfahren während der COVID-19-Pandemie (Planung...,2020-05-28T00:00:00Z
6,Zweites Gesetz zur Änderung des Bundespersonalvertretungsgesetzes und weiterer dienstrechtlicher Vorschriften aus An...,2020-05-28T00:00:00Z
7,Verordnung zur Verlängerung des Zeitraums für das vereinfachte Verfahren für den Zugang zu den Grundsicherungssystem...,2020-06-29T00:00:00Z
8,Gesetz zur Abmilderung der Folgen der COVID-19-Pandemie im Pauschalreisevertragsrecht und zur Sicherstellung der Fun...,2020-07-16T00:00:00Z
9,Bekanntmachung über das Inkrafttreten von Artikel 1 des Gesetzes zur Abmilderung der Folgen der COVID-19-Pandemie im...,2020-08-13T00:00:00Z
10,Gesetz zur Änderung des COVID-19-Insolvenzaussetzungsgesetzes,2020-09-30T00:00:00Z
11,Verordnung zur weiteren Verlängerung der zulässigen Befristungsdauer nach § 2 Absatz 1 des Wissenschaftszeitvertrags...,2020-09-30T00:00:00Z
12,Verordnung zur Erhebung von Garantieprämien für die ergänzende staatliche Absicherung von Reisegutscheinen wegen der...,2020-10-19T00:00:00Z
13,"Verordnung zur Verlängerung von Maßnahmen im Gesellschafts-, Genossenschafts-, Vereins- und Stiftungsrecht zur Bekäm...",2020-10-28T00:00:00Z
14,"Gesetz zur Änderung des Bundeswahlgesetzes und des Gesetzes über Maßnahmen im Gesellschafts-, Genossenschafts-, Vere...",2020-11-05T00:00:00Z
15,Verordnung zur Verlängerung der Maßnahmen zur Sicherstellung der Funktionsfähigkeit der Kammern im Bereich der Bunde...,2020-12-21T00:00:00Z
16,Gesetz zur Änderung des Justizkosten- und des Rechtsanwaltsvergütungsrechts und zur Änderung des Gesetzes zur Abmild...,2020-12-29T00:00:00Z
17,"Verordnung zur Sicherung von Vorbereitungsdiensten des Bundeskanzleramts und des Bundesministeriums des Innern, für ...",2021-08-19T00:00:00Z
18,Verordnung zur Sicherung von Vorbereitungsdiensten des Bundesministeriums der Finanzen während der COVID-19-Pandemie,2021-08-19T00:00:00Z
19,"Verordnung zur Sicherung von Vorbereitungsdiensten des Bundesministeriums des Innern, für Bau und Heimat während der...",2021-08-19T00:00:00Z
20,Verordnung zur Sicherung von Vorbereitungsdiensten des Auswärtigen Amts während der COVID-19-Pandemie,2021-09-03T00:00:00Z
21,Berichtigung der Verordnung zur Sicherung von Vorbereitungsdiensten des Auswärtigen Amts während der COVID-19-Pandemie,2021-09-28T00:00:00Z
22,Erste Verordnung zur Änderung der COVID-19-Schutzmaßnahmen-Ausnahmenverordnung,2021-12-11T00:00:00Z
23,Zweite Verordnung zur Änderung der COVID-19-Schutzmaßnahmen-Ausnahmenverordnung,2022-03-18T00:00:00Z
24,Gesetz zur Abschaffung des Güterrechtsregisters und zur Änderung des COVID-19-Insolvenzaussetzungsgesetzes,2022-11-08T00:00:00Z
25,Zweite Verordnung zur Sicherung von Vorbereitungsdiensten des Auswärtigen Amts während der COVID-19-Pandemie,2022-12-30T00:00:00Z
26,Zweite Verordnung zur Sicherung von Vorbereitungsdiensten des Bundeskanzleramts und des Bundesministeriums des Inner...,2022-12-30T00:00:00Z
27,Zweite Verordnung zur Sicherung von Vorbereitungsdiensten des Bundesministeriums der Finanzen während der COVID-19-P...,2022-12-30T00:00:00Z
28,Zweite Verordnung zur Sicherung von Vorbereitungsdiensten des Bundesministeriums des Innern und für Heimat während d...,2022-12-30T00:00:00Z

── topic 46  (n=23)  top words: krankenhaus, pflegepersonaluntergrenzenverordnung, pflege, pflegerisch, pflegerisch versorgung, versorgung

,title,date_published
0,"Verordnung über Beihilfe in Krankheits-, Pflege- und Geburtsfällen (Bundesbeihilfeverordnung  BBhV)",2009-02-13T00:00:00Z
1,Gesetz zur Regelung des Assistenzpflegebedarfs im Krankenhaus,2009-08-04T00:00:00Z
2,Dritte Verordnung zur Änderung der Schwerbehindertenausweisverordnung,2012-06-14T00:00:00Z
3,Gesetz zur Einführung eines pauschalierenden Entgeltsystems für psychiatrische und psychosomatische Einrichtungen (P...,2012-07-25T00:00:00Z
4,Verordnung zum pauschalierenden Entgeltsystem für psychiatrische und psychosomatische Einrichtungen für das Jahr 201...,2012-11-26T00:00:00Z
5,Gesetz zur Regelung des Assistenzpflegebedarfs in stationären Vorsorge- oder Rehabilitationseinrichtungen,2012-12-27T00:00:00Z
6,Verordnung zur Durchführung der Zulage für die private Pflegevorsorge nach dem Dreizehnten Kapitel des Elften Buches...,2012-12-31T00:00:00Z
7,Verordnung über das Ausbildungsgeld für Sanitätsoffizier-Anwärterinnen und -Anwärter (Sanitätsoffizier-Anwärter-Ausb...,2013-01-28T00:00:00Z
8,Gesetz zur Regelung der betreuungsrechtlichen Einwilligung in eine ärztliche Zwangsmaßnahme,2013-02-25T00:00:00Z
9,Gesetz zur Verbesserung der Rechte von Patientinnen und Patienten,2013-02-25T00:00:00Z
10,Verordnung zur Beteiligung der auf Bundesebene maßgeblichen Organisationen für die Wahrnehmung der Interessen und de...,2013-03-28T00:00:00Z
11,Verordnung zur Änderung der Pflegestatistik-Verordnung,2013-07-26T00:00:00Z
12,Gesetz zur Reform der Strukturen der Krankenhausversorgung(Krankenhausstrukturgesetz  KHSG),2015-12-17T00:00:00Z
13,Verordnung zur Verwaltung des Strukturfonds im Krankenhausbereich (Krankenhausstrukturfonds-Verordnung  KHSFV),2015-12-23T00:00:00Z
14,Verordnung zur Festlegung von Pflegepersonaluntergrenzen in pflegesensitiven Bereichen in Krankenhäusern (Pflegepers...,2019-10-31T00:00:00Z
15,Vierte Verordnung zur Änderung der Schwerbehinderten-Ausgleichsabgabeverordnung,2020-07-08T00:00:00Z
16,Zweite Verordnung zur Änderung der Pflegepersonaluntergrenzen-Verordnung,2020-07-24T00:00:00Z
17,Gesetz für ein Zukunftsprogramm Krankenhäuser (Krankenhauszukunftsgesetz – KHZG),2020-10-28T00:00:00Z
18,Gesetz zur Stärkung von intensivpflegerischer Versorgung und medizinischer Rehabilitation in der gesetzlichen Kranke...,2020-10-28T00:00:00Z
19,Verordnung zur Festlegung von Pflegepersonaluntergrenzen in pflegesensitiven Bereichen in Krankenhäusern für das Jah...,2020-11-13T00:00:00Z
20,Erste Verordnung zur Änderung der Pflegepersonaluntergrenzen-Verordnung,2021-11-10T00:00:00Z
21,Erste Verordnung zur Änderung der Wahlordnung Schwerbehindertenvertretungen,2022-03-18T00:00:00Z
22,Gesetz zur Pflegepersonalbemessung im Krankenhaus sowie zur Anpassung weiterer Regelungen im Krankenhauswesen und in...,2022-12-28T00:00:00Z

── topic 51  (n=12)  top words: wohngeld, grundsatz, wohnungseigentumsgesetz, reform, einstufung, geldwschegesetz

,title,date_published
0,Verordnung über die Prüfung zum anerkannten Abschluss Geprüfter Immobilienfachwirt/Geprüfte Immobilienfachwirtin,2008-01-30T00:00:00Z
1,Verordnung über die Grundsätze für die Ermittlung der Verkehrswerte von Grundstücken (Immobilienwertermittlungsveror...,2010-05-27T00:00:00Z
2,Verordnung zur Übertragung von Disziplinarbefugnissen auf die Bundesanstalt für Immobilienaufgaben (BImADiszV),2010-08-23T00:00:00Z
3,Erstes Gesetz zur Änderung des Gesetzes zur Zahlbarmachung von Renten aus Beschäftigungen in einem Ghetto,2014-07-18T00:00:00Z
4,Gesetz zur Einführung einer Wohnungslosenberichterstattung sowie einer Statistik untergebrachter wohnungsloser Perso...,2020-03-12T00:00:00Z
5,Gesetz über die Verteilung der Maklerkosten bei der Vermittlung von Kaufverträgen über Wohnungen und Einfamilienhäuser,2020-06-23T00:00:00Z
6,Verordnung zu den nach dem Geldwäschegesetz meldepflichtigen Sachverhalten im Immobilienbereich (Geldwäschegesetzmel...,2020-08-31T00:00:00Z
7,Verordnung zur Durchführung von Maßnahmen zur Begrenzung makroprudenzieller Risiken im Bereich der Darlehensvergabe ...,2021-02-02T00:00:00Z
8,Verordnung über die Grundsätze für die Ermittlung der Verkehrswerte von Immobilien und der für die Wertermittlung er...,2021-07-19T00:00:00Z
9,Verordnung zur Einstufung der Gemeinden in eine Mietniveaustufe im Sinne des § 254 des Bewertungsgesetzes (Mietnivea...,2021-08-26T00:00:00Z
10,Verordnung über den Inhalt und das Verfahren zur Erstellung und zur Anpassung von Mietspiegeln sowie zur Konkretisie...,2021-11-02T00:00:00Z
11,Verordnung über die Prüfung zum zertifizierten Verwalter nach dem Wohnungseigentumsgesetz (Zertifizierter-Verwalter-...,2021-12-16T00:00:00Z

── topic 53  (n=23)  top words: national, bevlkerung, schutz bevlkerung, aufgrund, beschlu deutsch, schutz

,title,date_published
0,Verordnung zur Änderung der Verordnung über bestimmte Impfstoffe zum Schutz vor der Blauzungenkrankheit und zur Ände...,2008-10-02T00:00:00Z
1,Verordnung zur Anpassung der Meldepflicht nach § 7 des Infektionsschutzgesetzes an die epidemische Lage (Labormeldep...,2009-05-28T00:00:00Z
2,Verordnung über die Änderung der Auswahlkriterien für Blut oder Blutbestandteile spendende Personen im Fall einer In...,2009-12-23T00:00:00Z
3,Verordnung zum Schutz gegen die Ansteckende Blutarmut der Einhufer (Einhufer-Blutarmut-Verordnung),2010-10-08T00:00:00Z
4,Gesetz zur Änderung des Infektionsschutzgesetzes und weiterer Gesetze,2011-08-03T00:00:00Z
5,Gesetz zur Durchführung der Internationalen Gesundheitsvorschriften (2005) und zur Änderung weiterer Gesetze,2013-03-28T00:00:00Z
6,Gesetz zum Schutz der Bevölkerung bei einer epidemischen Lage von nationaler Tragweite,2020-03-27T00:00:00Z
7,Zweites Gesetz zum Schutz der Bevölkerung bei einer epidemischen Lage von nationaler Tragweite,2020-05-22T00:00:00Z
8,Entscheidung des Bundesverfassungsgerichts (zu § 1 Absatz 5 Satz 1 Nummer 3 der Niedersächsischen Verordnung zum Sch...,2020-06-17T00:00:00Z
9,Verordnung zur Anpassung der Ausgleichszahlungen an Krankenhäuser aufgrund von Sonderbelastungen durch das Coronavir...,2020-07-08T00:00:00Z
10,Drittes Gesetz zum Schutz der Bevölkerung bei einer epidemischen Lage von nationaler Tragweite,2020-11-18T00:00:00Z
11,Bekanntmachung des Beschlusses des Deutschen Bundestages über die Feststellung des Fortbestehens der epidemischen La...,2021-03-30T00:00:00Z
12,Gesetz zur Fortgeltung der die epidemische Lage von nationaler Tragweite betreffenden Regelungen,2021-03-30T00:00:00Z
13,Viertes Gesetz zum Schutz der Bevölkerung bei einer epidemischen Lage von nationaler Tragweite,2021-04-22T00:00:00Z
14,Gesetz zur Verbesserung des Schutzes von Gerichtsvollziehern vor Gewalt sowie zur Änderung weiterer zwangsvollstreck...,2021-05-07T00:00:00Z
15,Verordnung zur Vernichtung und zum Laborcontainment des Poliovirus Typ 3 (Poliovirus-Verordnung – PolioV),2021-05-31T00:00:00Z
16,Zweites Gesetz zur Änderung des Infektionsschutzgesetzes und weiterer Gesetze,2021-05-31T00:00:00Z
17,Gesetz zur Vereinheitlichung des Stiftungsrechts und zur Änderung des Infektionsschutzgesetzes,2021-07-22T00:00:00Z
18,Verordnung zur Änderung der Verordnung zur weiteren Modernisierung des Strahlenschutzrechts – Friständerung zur Mild...,2021-10-14T00:00:00Z
19,Berichtigung der Verordnung zur Änderung der Verordnung zur weiteren Modernisierung des Strahlenschutzrechts – Frist...,2021-12-29T00:00:00Z
20,Dritte Verordnung zur Verlängerung von Maßnahmen zur Aufrechterhaltung der pflegerischen Versorgung während der durc...,2022-03-18T00:00:00Z
21,Gesetz zur Änderung des Infektionsschutzgesetzes und anderer Vorschriften,2022-03-18T00:00:00Z
22,Zweites Gesetz zur Änderung des Infektionsschutzgesetzes,2022-12-13T00:00:00Z

── topic 54  (n=30)  top words: einkommensteuergesetz, entscheidung bundesverfassungsgericht, bundesverfassungsgericht, entscheidung, 52, verbindung

,title,date_published
0,Entscheidung des Bundesverfassungsgerichts (zu Artikel 3 Nr. 4 Buchstabe a des Gesetzes zur Fortsetzung der Unterneh...,2008-03-31T00:00:00Z
1,Entscheidung des Bundesverfassungsgerichts (zu § 10 Abs. 1 Nr. 2 Buchstabe a i. V. m. § 10 Abs. 3 bzw. § 10 Abs. 1 N...,2008-04-04T00:00:00Z
2,Entscheidung des Bundesverfassungsgerichts (zu § 2 Abs. 1 Satz 2 des Gewerbesteuergesetzes und § 15 Abs. 3 Nr. 1 des...,2008-06-16T00:00:00Z
3,Entscheidung des Bundesverfassungsgerichts (zu § 13 Abs. 1 Nr. 18 des Erbschaftsteuer- und Schenkungsteuergesetzes),2008-06-30T00:00:00Z
4,Entscheidung des Bundesverfassungsgerichts (zu § 9 Absatz 2 Satz 1 und 2 des Einkommensteuergesetzes),2008-12-24T00:00:00Z
5,Entscheidung des Bundesverfassungsgerichts (zu § 52 Absatz 6 Satz 1 und 2 des Einkommensteuergesetzes),2009-06-29T00:00:00Z
6,Entscheidung des Bundesverfassungsgerichts (zu § 31 Satz 5 und § 36 Absatz 2 Satz 1 des Einkommensteuergesetzes),2009-11-19T00:00:00Z
7,Entscheidung des Bundesverfassungsgerichts (zu § 36 Absatz 3 und 4 des Körperschaftsteuergesetzes),2010-03-26T00:00:00Z
8,Entscheidung des Bundesverfassungsgerichts (zu § 4 Absatz 5 Satz 1 Nummer 6b des Einkommensteuergesetzes),2010-08-13T00:00:00Z
9,Entscheidung des Bundesverfassungsgerichts (zu § 10 Absatz 1 Satz 1 Nummer 7 Satz 2 des Gesetzes über die Entschädig...,2010-08-23T00:00:00Z
10,"Entscheidung des Bundesverfassungsgerichts (zu § 16 Absatz 1, § 17, § 15 Absatz 1 und § 19 des Erbschaftsteuer- und ...",2010-09-13T00:00:00Z
11,Entscheidung des Bundesverfassungsgerichts (zu § 17 Absatz 1 Satz 4 in Verbindung mit § 52 Absatz 1 Satz 1 des Einko...,2010-09-13T00:00:00Z
12,Entscheidung des Bundesverfassungsgerichts (zu § 23 Absatz 1 Satz 1 Nummer 1 in Verbindung mit § 52 Absatz 39 Satz 1...,2010-09-13T00:00:00Z
13,Entscheidung des Bundesverfassungsgerichts (zu § 34 Absatz 1 in Verbindung mit § 52 Absatz 47 und § 39b Absatz 3 Sat...,2010-09-13T00:00:00Z
14,"Entscheidung des Bundesverfassungsgerichts (zu § 6a Satz 1, 3 und 4 des Zukunftsinvestitionsgesetzes)",2010-10-21T00:00:00Z
15,Entscheidung des Bundesverfassungsgerichts (zu § 8b Absatz 3 Satz 1 und Absatz 5 Satz 1 des Körperschaftsteuergesetzes),2010-12-08T00:00:00Z
16,"Entscheidung des Bundesverfassungsgerichts (zu § 3 Nummer 3 Satz 2 und 3, Nummer 4, 5, 6 Satz 3 und Nummer 7 Satz 2 ...",2012-08-23T00:00:00Z
17,Entscheidung des Bundesverfassungsgerichts (zu § 36 Absatz 4 des Gewerbesteuergesetzes),2012-11-26T00:00:00Z
18,"Entscheidung des Bundesverfassungsgerichts (zu den §§ 26, 26b und 32a Absatz 5 des Einkommensteuergesetzes)",2013-06-26T00:00:00Z
19,Entscheidung des Bundesverfassungsgerichts (zu § 4 Absatz 1 der Satzung über die Erhebung einer Zweitwohnungsteuer i...,2014-03-06T00:00:00Z
20,Entscheidung des Bundesverfassungsgerichts (zu § 43 Absatz 18 des Gesetzes über Kapitalanlagegesellschaften),2014-03-14T00:00:00Z
21,Gesetz zur Anpassung steuerlicher Regelungen an die Rechtsprechung des Bundesverfassungsgerichts,2014-07-23T00:00:00Z
22,Entscheidung des Bundesverfassungsgerichts (zu § 13a und § 13b jeweils in Verbindung mit § 19 Absatz 1 des Erbschaft...,2015-01-15T00:00:00Z
23,Entscheidung des Bundesverfassungsgerichts (zu § 8 Absatz 2 des Grunderwerbsteuergesetzes),2015-07-31T00:00:00Z
24,Entscheidung des Bundesverfassungsgerichts (zu § 2 Absatz 2 Satz 1 und 4 des Biersteuergesetzes 1993 sowie § 4 Absat...,2019-03-08T00:00:00Z
25,Entscheidung des Bundesverfassungsgerichts (zu § 54 Absatz 9 Satz 1 des Körperschaftsteuergesetzes 1999),2019-03-08T00:00:00Z
26,Entscheidung des Bundesverfassungsgerichts (zu § 11 Absatz 2 Satz 3 Halbsatz 1 i.V.m. § 52 Absatz 30 bzw. § 11 Absat...,2021-06-17T00:00:00Z
27,Entscheidung des Bundesverfassungsgerichts (zu § 32c sowie § 32b Absatz 2 Satz 2 und 3 in Verbindung mit § 32a Absat...,2022-02-18T00:00:00Z
28,Entscheidung des Bundesverfassungsgerichts (zu § 9 Absatz 6 des Einkommensteuergesetzes),2022-03-14T00:00:00Z
29,Entscheidung des Bundesverfassungsgerichts (zu § 62 Absatz 2 Nummer 3 Buchstabe b des Einkommensteuergesetzes),2022-08-31T00:00:00Z

── topic 76  (n=7)  top words: asylbewerberleistungsgesetz, hhe, aufenthalts, 3a, januar, unterbringung

,title,date_published
0,Bekanntmachung über den Beschluss der Bundesregierung zur Einführung eines jährlichen Gedenktages für die Opfer von ...,2014-10-14T00:00:00Z
1,Gesetz über Maßnahmen im Bauplanungsrecht zur Erleichterung der Unterbringung von Flüchtlingen,2014-11-25T00:00:00Z
2,Bekanntmachung über die Höhe der Leistungssätze nach § 14 des Asylbewerberleistungsgesetzes für die Zeit ab 1. März ...,2015-01-26T00:00:00Z
3,Gesetz zur Förderung von Investitionen finanzschwacher Kommunen und zur Entlastung von Ländern und Kommunen bei der ...,2015-06-29T00:00:00Z
4,Zweites Gesetz zur Verbesserung der Registrierung und des Datenaustausches zu aufenthalts- und asylrechtlichen Zweck...,2019-08-08T00:00:00Z
5,Bekanntmachung über die Höhe der Leistungssätze nach § 3a Absatz 4 des Asylbewerberleistungsgesetzes für die Zeit ab...,2019-10-09T00:00:00Z
6,Gesetz zur Anpassung der Ergänzungszuweisungen des Bundes nach § 11 Absatz 4 des Finanzausgleichsgesetzes und zur Be...,2020-12-09T00:00:00Z

── topic 86  (n=11)  top words: bundesausbildungsfrderungsgesetz, aufstiegsfortbildungsfrderungsgesetz, nderung bundesausbildungsfrderungsgesetz, bafgndg, nderung aufstiegsfortbildungsfrderungsgesetz, ausland

,title,date_published
0,Zweites Gesetz zur Änderung des Aufstiegsfortbildungsförderungsgesetzes,2009-06-22T00:00:00Z
1,Berichtigung der Bekanntmachung der Neufassung des Aufstiegsfortbildungsförderungsgesetzes,2009-07-15T00:00:00Z
2,Neufassung des Bundesausbildungsförderungsgesetzes,2010-12-16T00:00:00Z
3,Erste Verordnung zur Änderung der Verordnung über die örtliche Zuständigkeit für Ausbildungsförderung im Ausland,2011-10-28T00:00:00Z
4,Vierundzwanzigstes Gesetz zur Änderung des Bundesausbildungsförderungsgesetzes,2011-12-13T00:00:00Z
5,Berichtigung der Bekanntmachung der Neufassung des Bundesausbildungsförderungsgesetzes,2012-02-13T00:00:00Z
6,Neufassung des Aufstiegsfortbildungsförderungsgesetzes,2012-10-18T00:00:00Z
7,Gesetz zur Neuregelung der Professorenbesoldung und zur Änderung weiterer dienstrechtlicher Vorschriften (Professore...,2013-06-20T00:00:00Z
8,Viertes Gesetz zur Änderung des Aufstiegsfortbildungsförderungsgesetzes,2020-03-31T00:00:00Z
9,Erste Verordnung zur Änderung der Verordnung über die Zuschläge zu dem Bedarf nach dem Bundesausbildungsförderungsge...,2022-07-21T00:00:00Z
10,Siebenundzwanzigstes Gesetz zur Änderung des Bundesausbildungsförderungsgesetzes (27. BAföGÄndG),2022-07-21T00:00:00Z

── topic 95  (n=1)  top words: krankenversicherung, gesetzlich krankenversicherung, gesetzlich, pflegeversicherung, weiterentwicklung, sozial

,title,date_published
0,Gesetz zur Absicherung stabiler und fairer Leistungen für Lebensversicherte (Lebensversicherungsreformgesetz  LVRG),2014-08-06T00:00:00Z

── topic 100  (n=11)  top words: zwlfter, zwlfter buch, buch sozialgesetzbuch, buch, sozialgesetzbuch, regelbedarfsstufenfortschreibungsverordnung

,title,date_published
0,Bekanntmachung über die Höhe der Regelleistung nach § 20 Abs. 2 Satz 1 des Zweiten Buches Sozialgesetzbuch für die Z...,2008-06-30T00:00:00Z
1,Bekanntmachung über die Höhe der Regelleistung nach § 20 Absatz 2 Satz 1 des Zweiten Buches Sozialgesetzbuch für die...,2009-06-22T00:00:00Z
2,Bekanntmachung über die Höhe der Regelleistung nach § 20 Absatz 2 Satz 1 des Zweiten Buches Sozialgesetzbuch für die...,2010-06-25T00:00:00Z
3,Bekanntmachung über die Höhe der Regelbedarfe nach § 20 Absatz 5 des Zweiten Buches Sozialgesetzbuch für die Zeit ab...,2011-10-26T00:00:00Z
4,Bekanntmachung über die Höhe der Regelbedarfe nach § 20 Absatz 5 des Zweiten Buches Sozialgesetzbuch für die Zeit ab...,2012-10-24T00:00:00Z
5,Bekanntmachung über die Höhe der Regelbedarfe nach § 20 Absatz 5 des Zweiten Buches Sozialgesetzbuch für die Zeit ab...,2013-10-24T00:00:00Z
6,Verordnung zur Bestimmung des für die Fortschreibung der Regelbedarfsstufen nach § 28a des Zwölften Buches Sozialges...,2013-10-24T00:00:00Z
7,Bekanntmachung über die Höhe der Regelbedarfe nach § 20 Absatz 5 des Zweiten Buches Sozialgesetzbuch für die Zeit ab...,2014-10-17T00:00:00Z
8,Bekanntmachung über die Höhe der Regelbedarfe nach § 20 Absatz 5 des Zweiten Buches Sozialgesetzbuch für die Zeit ab...,2015-10-27T00:00:00Z
9,Verordnung zur Bestimmung des für die Fortschreibung der Regelbedarfsstufen nach § 28a des Zwölften Buches Sozialges...,2019-10-21T00:00:00Z
10,Verordnung zur Bestimmung des für die Fortschreibung der Regelbedarfsstufen nach § 28a und des Teilbetrags nach § 34...,2021-09-28T00:00:00Z

── topic 109  (n=2)  top words: stabilisierung, 2023, 2016, 2022, 2015, 2010

,title,date_published
0,Gesetz zur Stabilisierung des Künstlersozialabgabesatzes (Künstlersozialabgabestabilisierungsgesetz  KSAStabG),2014-08-04T00:00:00Z
1,Künstlersozialabgabe-Verordnung 2020,2019-09-05T00:00:00Z

── topic 121  (n=9)  top words: gesetzlich rentenversicherung, juli, alterssicherung landwirt, landwirt, alterssicherung, gesetzlich

,title,date_published
0,Verordnung zur Bestimmung der Rentenwerte in der gesetzlichen Rentenversicherung und in der Alterssicherung der Land...,2009-06-22T00:00:00Z
1,Verordnung zur Bestimmung der Rentenwerte in der gesetzlichen Rentenversicherung und in der Alterssicherung der Land...,2011-06-16T00:00:00Z
2,Gesetz zur Neuordnung der Organisation der landwirtschaftlichen Sozialversicherung (LSV-Neuordnungsgesetz  LSV-NOG),2012-04-18T00:00:00Z
3,Verordnung zur Bestimmung der Rentenwerte in der gesetzlichen Rentenversicherung und in der Alterssicherung der Land...,2013-06-20T00:00:00Z
4,Neufassung des Gesetzes über die Landwirtschaftliche Rentenbank,2013-12-17T00:00:00Z
5,Verordnung zur Bestimmung der Rentenwerte in der gesetzlichen Rentenversicherung und in der Alterssicherung der Land...,2014-06-20T00:00:00Z
6,Verordnung zur Bestimmung der Rentenwerte in der gesetzlichen Rentenversicherung und in der Alterssicherung der Land...,2019-06-19T00:00:00Z
7,Verordnung zur Bestimmung der Rentenwerte in der gesetzlichen Rentenversicherung und in der Alterssicherung der Land...,2020-06-17T00:00:00Z
8,Verordnung zur Bestimmung der Rentenwerte in der gesetzlichen Rentenversicherung und in der Alterssicherung der Land...,2021-06-04T00:00:00Z

── topic 122  (n=1)  top words: einkommen, bundesversorgungsgesetz, anrechnungsverordnung, 53, einigungsvertrag, fnfundvierzigst

,title,date_published
0,Zweiundzwanzigste Verordnung über das anzurechnende Einkommen nach dem Bundesversorgungsgesetz in dem in Artikel 3 d...,2008-07-25T00:00:00Z

── topic 123  (n=11)  top words: wirkung, gefhrdung, 25 eg, nderung arbeitsschutzverordnunge, regelung schutz, richtlinie 2006

,title,date_published
0,Erstes Gesetz zur Änderung des Strahlenschutzvorsorgegesetzes,2008-04-11T00:00:00Z
1,Gesetz zur Regelung des Schutzes vor nichtionisierender Strahlung,2009-08-03T00:00:00Z
2,Verordnung zur Umsetzung der Richtlinie 2006/25/EG zum Schutz der Arbeitnehmer vor Gefährdungen durch künstliche opt...,2010-07-26T00:00:00Z
3,Verordnung zum Schutz vor schädlichen Wirkungen künstlicher ultravioletter Strahlung (UV-Schutz-Verordnung  UVSV),2011-07-25T00:00:00Z
4,Erste Verordnung zur Änderung der Strahlenschutzverordnung,2020-04-01T00:00:00Z
5,Zweite Verordnung zur Änderung der Strahlenschutzverordnung,2020-11-26T00:00:00Z
6,Erstes Gesetz zur Änderung des Strahlenschutzgesetzes,2021-06-04T00:00:00Z
7,Dritte Verordnung zur Änderung der Strahlenschutzverordnung,2021-10-14T00:00:00Z
8,Berichtigung der Verordnung zur weiteren Modernisierung des Strahlenschutzrechts,2021-12-29T00:00:00Z
9,Bekanntmachung über das Inkrafttreten des Artikels 2 Nummer 1 des Gesetzes zur Neuordnung des Rechts zum Schutz vor ...,2022-01-11T00:00:00Z
10,Bekanntmachung über das Inkrafttreten des Artikels 2 des Ersten Gesetzes zur Änderung des Strahlenschutzgesetzes,2022-01-11T00:00:00Z

── topic 125  (n=11)  top words: nderung sonderurlaubsverordnung, sonderurlaubsverordnung, zwlft nderung, heimaturlaubsverordnung, zwlft, vierzehnt nderung

,title,date_published
0,Achte Verordnung zur Änderung der Ferienreiseverordnung,2008-06-19T00:00:00Z
1,Zwölfte Verordnung zur Änderung der Erholungsurlaubsverordnung,2009-07-24T00:00:00Z
2,Zweite Verordnung zur Änderung der Heimaturlaubsverordnung,2010-06-18T00:00:00Z
3,Neunte Verordnung zur Änderung der Ferienreiseverordnung,2012-06-22T00:00:00Z
4,Dreizehnte Verordnung zur Änderung der Erholungsurlaubsverordnung,2012-12-13T00:00:00Z
5,Zehnte Verordnung zur Änderung der Ferienreiseverordnung,2013-06-20T00:00:00Z
6,Vierzehnte Verordnung zur Änderung der Erholungsurlaubsverordnung,2014-11-28T00:00:00Z
7,Elfte Verordnung zur Änderung der Ferienreiseverordnung,2015-06-29T00:00:00Z
8,Erste Verordnung zur Änderung der Sonderurlaubsverordnung,2021-06-08T00:00:00Z
9,Zweite Verordnung zur Änderung der Sonderurlaubsverordnung,2021-12-29T00:00:00Z
10,Zwölfte Verordnung zur Änderung der Ferienreiseverordnung,2022-06-30T00:00:00Z

── topic 131  (n=8)  top words: bundesbesoldungsgesetz, 77, 78, 5a, anlage iv, iv

,title,date_published
0,Bekanntmachung nach § 77 Abs. 2 und 3 des Bundesbesoldungsgesetzes und nach § 2 Abs. 1 und § 3 Abs. 2 der Zweiten Be...,2008-08-01T00:00:00Z
1,Bekanntmachung nach § 77 Absatz 1 und 2 sowie nach § 78 Absatz 1 des Bundesbesoldungsgesetzes und nach § 6 Absatz 2 ...,2009-07-02T00:00:00Z
2,Berichtigung der Bekanntmachung nach § 77 Absatz 1 und 2 sowie nach § 78 Absatz 1 des Bundesbesoldungsgesetzes und n...,2009-08-19T00:00:00Z
3,Bekanntmachung nach § 77 Absatz 4 und § 78 Absatz 2 des Bundesbesoldungsgesetzes sowie nach § 6 Absatz 3 des Besoldu...,2012-08-23T00:00:00Z
4,Bekanntmachung nach § 77 Absatz 4 und § 78 Absatz 2 des Bundesbesoldungsgesetzes sowie nach § 5a Absatz 2 und § 6 Ab...,2014-12-04T00:00:00Z
5,Bekanntmachung nach § 78 Absatz 2 des Bundesbesoldungsgesetzes,2019-12-20T00:00:00Z
6,Bekanntmachung nach Anlage IV Nummer 1 und 4 des Bundesbesoldungsgesetzes,2020-03-05T00:00:00Z
7,"Bekanntmachung nach § 77 Absatz 4, § 78 Absatz 2 und Anlage IV Nummer 1 und 4 des Bundesbesoldungsgesetzes sowie nac...",2021-08-13T00:00:00Z

── topic 133  (n=6)  top words: ii, trger, rente, bundesagentur arbeit, zahlung, bundesagentur

,title,date_published
0,Erste Verordnung zur Änderung der Arbeitslosengeld II/Sozialgeld-Verordnung,2008-12-23T00:00:00Z
1,Dritte Verordnung zur Änderung der Arbeitslosengeld II/Sozialgeld-Verordnung,2010-05-12T00:00:00Z
2,Erste Verordnung zur Änderung der Verordnung über die Pauschalierung und Zahlung des Ausgleichsbetrags der Bundesage...,2010-12-22T00:00:00Z
3,Fünfte Verordnung zur Änderung der Arbeitslosengeld II/Sozialgeld-Verordnung,2011-06-25T00:00:00Z
4,Neunte Verordnung zur Änderung der Arbeitslosengeld II/Sozialgeld-Verordnung,2020-12-16T00:00:00Z
5,Zehnte Verordnung zur Änderung der Arbeitslosengeld II/Sozialgeld-Verordnung,2021-03-24T00:00:00Z

### §6a. Decision — System 2 only (topic level)

Review the topic groups above. Enter the **topic IDs** you want to keep in `S2_KEPT_TOPICS` below — all documents in those topics are included, all others are excluded.  
Leave as `[]` to exclude all System-2-only policies.

In [ ]:
# ── DECISION: System 2 only ───────────────────────────────────────────────────
# BERTopic topic IDs to keep in full (all documents in those topics are included).
# Topic IDs are shown in the "── topic N" headers above.
# Example: S2_KEPT_TOPICS = [3, 7, 12]
# Leave as [] to exclude all System-2-only policies.

S2_KEPT_TOPICS = [7, 16, 17, 20, 39, 42, 86, 100, 109, 121, 122, 125, 131, 133]   # ← edit this list

# Individual picks from topics NOT fully kept above.
# Keys: topic ID (from §6 "── topic N" header).
# Values: 0-based row indices within that topic's table (left-most column in §6 display).
# Example: S2_INDIVIDUAL_PICKS = {5: [0, 3], 14: [2]}

S2_INDIVIDUAL_PICKS = {15: [10, 11], 44: [7, 11], 46: [6, 7, 15], 51: [4, 10, 9], 
                       54: [4, 5, 6, 8, 11, 18, 28, 29], 76: [3, 5]}   # ← edit this dict

## §7. Noise pool spot-check

Topic -1: documents HDBSCAN could not assign to any cluster. Spot-check a sample
to verify they are correctly excluded as non-welfare-policy laws.

In [ ]:
SAMPLE_N = 30
if noise_docs:
    sample   = random.sample(noise_docs, min(SAMPLE_N, len(noise_docs)))
    df_noise = pd.DataFrame(sample)
    cols     = [c for c in ['title', 'date_published'] if c in df_noise.columns]
    df_noise = df_noise[cols].sort_values('date_published').reset_index(drop=True)
    print(f'Random sample of {len(df_noise)} from {len(noise_docs)} noise docs (topic -1)')
    display(df_noise)
else:
    print('No noise pool file found.')

---

*Add further inspection cells below.*

## §8. Final policy set — compile & save

Applies the decisions from §5a and §6a.  
All "both" candidates are always included; System-1-only and System-2-only policies are filtered based on your selections above.

In [ ]:
# ── Apply decisions ───────────────────────────────────────────────────────────
df_both_docs   = df_union[df_union['system_sources'] == 'both'].copy()
df_s1_selected = df_s1.iloc[S1_INCLUDED_INDICES].copy() if S1_INCLUDED_INDICES else df_s1.iloc[[]]
df_s2_selected = (
    df_s2[df_s2['berttopic_topic'].isin(S2_KEPT_TOPICS)].copy()
    if S2_KEPT_TOPICS else df_s2.iloc[[]]
)

# Individual picks from topics not fully kept
_pick_frames = []
for _topic_id, _indices in S2_INDIVIDUAL_PICKS.items():
    if _topic_id in S2_KEPT_TOPICS:
        continue  # already fully included
    _group = df_s2[df_s2['berttopic_topic'] == _topic_id].reset_index(drop=True)
    _pick_frames.append(_group.iloc[_indices])
df_s2_individual = pd.concat(_pick_frames, ignore_index=True) if _pick_frames else df_s2.iloc[[]]

keep_titles = (
    set(df_both_docs['title'].str.strip())
    | set(df_s1_selected['title'].str.strip())
    | set(df_s2_selected['title'].str.strip())
    | set(df_s2_individual['title'].str.strip())
)

final_records = [r for r in union if r['title'].strip() in keep_titles]
final_records.sort(key=lambda x: x.get('date_published', ''))

FINAL_FILE = BASE / f'{OUTPUT_PREFIX}_final_policy_set.json'
FINAL_FILE.write_text(json.dumps(final_records, ensure_ascii=False, indent=2), encoding='utf-8')

n_both_final       = len(df_both_docs)
n_s1_final         = len(df_s1_selected)
n_s2_final         = len(df_s2_selected)
n_s2_individual    = len(df_s2_individual)
n_total_final      = len(final_records)

print(f'Accepted from both systems:           {n_both_final:>4}')
print(f'Accepted from System 1 only:          {n_s1_final:>4}  (of {n_s1} candidates)')
print(f'Accepted from System 2 only (topics): {n_s2_final:>4}  (of {n_s2} candidates, {len(S2_KEPT_TOPICS)} topic(s) kept)')
print(f'Accepted from System 2 (individual):  {n_s2_individual:>4}  (across {len(S2_INDIVIDUAL_PICKS)} topic(s))')
print(f'─────────────────────────────────────────────')
print(f'Final policy set (total):             {n_total_final:>4}')
print(f'Saved to: {FINAL_FILE.name}')

## §9. Export evaluation log

Generates a dated Markdown log documenting all inputs, counts, decisions, and outputs.  
**Run after §8.**

In [ ]:
import datetime

today = datetime.date.today().isoformat()
log_path = BASE / f'pooled_eval_log_{today}.md'

s2_topics_detail = ', '.join(
    f'topic {t} ({", ".join(str(w) for w in topic_to_words.get(t, [])[:5])})'
    for t in sorted(S2_KEPT_TOPICS)
) if S2_KEPT_TOPICS else '*(none)*'

log_md = f"""# Pooled Union Evaluation Log
Generated: {today}

## 1. Input files

| role | file |
|---|---|
| System 1 (cosine similarity) | `{S1_FILE.name}` |
| System 2 (BERTopic candidates) | `{S2_FILE.name}` |
| System 2 noise pool | `{NOISE_FILE.name}` |
| BERTopic topic assignments | `{TOPIC_ASSIGN_FILE.name}` |
| BERTopic topic info | `{TOPIC_INFO_FILE.name}` |

## 2. §1 — Candidate counts (raw input)

| source | n |
|---|---|
| System 1 (cosine similarity) | {len(s1_docs)} |
| System 2 (BERTopic) | {len(s2_docs)} |
| System 2 noise pool (topic -1) | {len(noise_docs)} |

## 3. §3 — Pooled union overview

| group | n | share |
|---|---|---|
| Both systems (high confidence) | {n_both} | {n_both/n_total:.0%} |
| System 1 only (cosine sim) | {n_s1} | {n_s1/n_total:.0%} |
| System 2 only (BERTopic) | {n_s2} | {n_s2/n_total:.0%} |
| **Total** | **{n_total}** | **100%** |

## 4. §5a — System 1 only decision

- Candidates reviewed: {n_s1}
- Row indices included: {S1_INCLUDED_INDICES if S1_INCLUDED_INDICES else '(none)'}
- **Policies included: {n_s1_final}**

## 5. §6a — System 2 only decision (topic level)

- Candidates reviewed: {n_s2} across {df_s2['berttopic_topic'].nunique()} topics
- Topics kept: {len(S2_KEPT_TOPICS)} — {s2_topics_detail}
- **Policies included: {n_s2_final}**

## 6. §8 — Final policy set

| group | n |
|---|---|
| Accepted by both systems | {n_both_final} |
| Accepted from System 1 only | {n_s1_final} |
| Accepted from System 2 only | {n_s2_final} |
| **Final total** | **{n_total_final}** |

## 7. Output file

`{FINAL_FILE.name}`
"""

log_path.write_text(log_md, encoding='utf-8')
print(f'Log saved to: {log_path.name}')